//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSIndexPath;

@interface _SCTableRowMove : NSObject
{
    NSIndexPath *_from;
    NSIndexPath *_to;
}

+ (id)moveFrom:(id)arg1 to:(id)arg2;
- (void).cxx_destruct;
@property(retain) NSIndexPath *from; // @synthesize from=_from;
@property(retain) NSIndexPath *to; // @synthesize to=_to;

@end

