//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface ADLSpeechActivityEvent : NSObject
{
    NSString *_scopeId;
    NSArray *_speechActivity;
    NSArray *_activeSpeakers;
}

+ (id)SpeechActivityEventWithScopeId:(id)arg1 speechActivity:(id)arg2 activeSpeakers:(id)arg3;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSArray *activeSpeakers; // @synthesize activeSpeakers=_activeSpeakers;
- (id)description;
- (id)initWithScopeId:(id)arg1 speechActivity:(id)arg2 activeSpeakers:(id)arg3;
@property(readonly, nonatomic) NSString *scopeId; // @synthesize scopeId=_scopeId;
@property(readonly, nonatomic) NSArray *speechActivity; // @synthesize speechActivity=_speechActivity;

@end

