//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCBaseAPIClient.h"

@class NSDateFormatter, NSURL, SCQueuePerformer;

@interface b59a95c4ef8 : SCBaseAPIClient
{
    NSURL *_defaultBaseURL;
    SCQueuePerformer *_reachabilityQueuePerformer;
    long long _prevReachabilityStatus;
    double _loggingRate;
    NSDateFormatter *_dateFormatter;
}

+ (long long)ReachabilityForTweakedStatus:(unsigned long long)arg1;
+ (void)addListener:(id)arg1;
+ (void)alertView:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
+ (void)apiClientDidFinishRequest:(id)arg1 response:(id)arg2 parameters:(id)arg3;
+ (id)defaultAuthServiceUrl;
+ (id)defaultSnapConnectUrl;
+ (id)defaultSnaptokenUrl;
+ (id)defaultUrl;
+ (id)getCarrierMCC;
+ (id)getCarrierMNC;
+ (id)getCarrierName;
+ (id)getConnectionType;
+ (void)initialize;
+ (_Bool)isDevAuthService;
+ (_Bool)isDevSnapConnect;
+ (_Bool)isDevSnapchat;
+ (void)removeListener:(id)arg1;
+ (id)sharedAuthServiceClient;
+ (id)sharedClient;
+ (id)sharedSnapConnectClient;
+ (id)sharedSnaptokenClient;
+ (void)showAlertAndWaitForDismissalWithUrl:(id)arg1;
+ (id)updateSharedAuthServiceClientWithUrl:(id)arg1;
+ (id)updateSharedClientWithUrl:(id)arg1;
+ (id)updateSharedSnapConnectClientWithUrl:(id)arg1;
+ (id)updateSharedSnaptokenClientWithUrl:(id)arg1;
- (void).cxx_destruct;
- (id)00a30fa0be6c5788f:(id)arg1 5d24:(id)arg2 364e250b43:(id)arg3;
- (id)5980cc8d0139bd2bd:(id)arg1 43c:(id)arg2 1b2b863b24:(id)arg3 9fd0dc7339afd:(_Bool)arg4;
- (id)80d3edb875521584468a40d3bc9a50:(id)arg1 fd57:(id)arg2 7b4d9944b6:(id)arg3 0c074fc9dbfa76057a537f240:(CDUnknownBlockType)arg4;
- (_Bool)_shouldLogPayloadGeneration;
- (void)c6a11af65b35d929337:(id)arg1 1cff:(id)arg2 1372c18ea3:(id)arg3;
@property(retain, nonatomic) NSDateFormatter *dateFormatter; // @synthesize dateFormatter=_dateFormatter;
@property(retain, nonatomic) NSURL *defaultBaseURL; // @synthesize defaultBaseURL=_defaultBaseURL;
- (void)enqueueHTTPRequestOperation:(id)arg1;
- (id)initWithBaseURL:(id)arg1;
- (_Bool)isCustomEndpoint;
@property(readonly, nonatomic) double loggingRate; // @synthesize loggingRate=_loggingRate;
- (long long)networkReachabilityStatus;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
@property long long prevReachabilityStatus; // @synthesize prevReachabilityStatus=_prevReachabilityStatus;
@property(retain, nonatomic) SCQueuePerformer *reachabilityQueuePerformer; // @synthesize reachabilityQueuePerformer=_reachabilityQueuePerformer;

@end

