//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GRPCCallOptions.h"

#import "NSCopying-Protocol.h"
#import "NSMutableCopying-Protocol.h"

@class NSDictionary, NSString;
@protocol GRPCAuthorizationProtocol;

@interface GRPCMutableCallOptions : GRPCCallOptions <NSCopying, NSMutableCopying>
{
}

- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
@property(copy) NSDictionary *additionalChannelArgs; // @dynamic additionalChannelArgs;
@property(retain) id <GRPCAuthorizationProtocol> authTokenProvider; // @dynamic authTokenProvider;
@property unsigned long long channelID; // @dynamic channelID;
@property(copy) NSString *channelPoolDomain; // @dynamic channelPoolDomain;
@property unsigned long long compressionAlgorithm; // @dynamic compressionAlgorithm;
@property double connectInitialBackoff; // @dynamic connectInitialBackoff;
@property double connectMaxBackoff; // @dynamic connectMaxBackoff;
@property double connectMinTimeout; // @dynamic connectMinTimeout;
@property(copy) NSString *hostNameOverride; // @dynamic hostNameOverride;
@property(copy) NSDictionary *initialMetadata; // @dynamic initialMetadata;
@property double keepaliveInterval; // @dynamic keepaliveInterval;
@property double keepaliveTimeout; // @dynamic keepaliveTimeout;
@property(retain) id logContext; // @dynamic logContext;
@property(copy) NSString *oauth2AccessToken; // @dynamic oauth2AccessToken;
@property(copy) NSString *PEMCertificateChain; // @dynamic PEMCertificateChain;
@property(copy) NSString *PEMPrivateKey; // @dynamic PEMPrivateKey;
@property(copy) NSString *PEMRootCertificates; // @dynamic PEMRootCertificates;
@property unsigned long long responseSizeLimit; // @dynamic responseSizeLimit;
@property _Bool retryEnabled; // @dynamic retryEnabled;
@property(copy) NSString *serverAuthority; // @dynamic serverAuthority;
@property double timeout; // @dynamic timeout;
@property unsigned long long transportType; // @dynamic transportType;
@property(copy) NSString *userAgentPrefix; // @dynamic userAgentPrefix;

@end

