//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class GPBInt32Value, GPBStringValue, IMPTrailerProperties, IMPUUIDValue, SCCOREUUID;

@interface IMPCreateOrUpdateExtraRequest : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasSeasonDisplayName; // @dynamic hasSeasonDisplayName;
@property(nonatomic) _Bool hasSeasonId; // @dynamic hasSeasonId;
@property(nonatomic) _Bool hasSeasonNumber; // @dynamic hasSeasonNumber;
@property(nonatomic) _Bool hasShowId; // @dynamic hasShowId;
@property(readonly, nonatomic) int propertiesOneOfCase; // @dynamic propertiesOneOfCase;
@property(retain, nonatomic) GPBStringValue *seasonDisplayName; // @dynamic seasonDisplayName;
@property(retain, nonatomic) IMPUUIDValue *seasonId; // @dynamic seasonId;
@property(retain, nonatomic) GPBInt32Value *seasonNumber; // @dynamic seasonNumber;
@property(retain, nonatomic) SCCOREUUID *showId; // @dynamic showId;
@property(retain, nonatomic) IMPTrailerProperties *trailerProperties; // @dynamic trailerProperties;

@end

