//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class LCVCameraData, LCVImage, NSMutableArray;

@interface LCVDepthFrameData : NSObject
{
    int frameIndex;
    double timeStamp;
    LCVCameraData *depthCamera;
    LCVCameraData *rgbCamera;
    LCVImage *depth;
    LCVImage *rgb;
    LCVImage *rgbThumbnail;
    LCVImage *disparity;
    LCVImage *confidence;
    NSMutableArray *alignmentComp;
    NSMutableArray *imuAlignmentComp;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *alignmentComp; // @synthesize alignmentComp;
@property(retain, nonatomic) LCVImage *confidence; // @synthesize confidence;
@property(retain, nonatomic) LCVImage *depth; // @synthesize depth;
@property(retain, nonatomic) LCVCameraData *depthCamera; // @synthesize depthCamera;
@property(retain, nonatomic) LCVImage *disparity; // @synthesize disparity;
@property(nonatomic) int frameIndex; // @synthesize frameIndex;
@property(retain, nonatomic) NSMutableArray *imuAlignmentComp; // @synthesize imuAlignmentComp;
- (id)init;
@property(retain, nonatomic) LCVImage *rgb; // @synthesize rgb;
@property(retain, nonatomic) LCVCameraData *rgbCamera; // @synthesize rgbCamera;
@property(retain, nonatomic) LCVImage *rgbThumbnail; // @synthesize rgbThumbnail;
@property(nonatomic) double timeStamp; // @synthesize timeStamp;

@end

