//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "CLLocationManagerDelegate-Protocol.h"

@class CLLocationManager, NSDate, NSString, NSTimer;
@protocol MGLLocationManagerDelegate;

@interface MGLLocationManager : NSObject <CLLocationManagerDelegate>
{
    _Bool _hostAppHasBackgroundCapability;
    _Bool _updatingLocation;
    id <MGLLocationManagerDelegate> _delegate;
    CLLocationManager *_standardLocationManager;
    NSDate *_backgroundLocationServiceTimeoutAllowedDate;
    NSTimer *_backgroundLocationServiceTimeoutTimer;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSDate *backgroundLocationServiceTimeoutAllowedDate; // @synthesize backgroundLocationServiceTimeoutAllowedDate=_backgroundLocationServiceTimeoutAllowedDate;
@property(retain, nonatomic) NSTimer *backgroundLocationServiceTimeoutTimer; // @synthesize backgroundLocationServiceTimeoutTimer=_backgroundLocationServiceTimeoutTimer;
- (void)configurePassiveStandardLocationManager;
@property(nonatomic) __weak id <MGLLocationManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)establishRegionMonitoringForLocation:(id)arg1;
@property(nonatomic) _Bool hostAppHasBackgroundCapability; // @synthesize hostAppHasBackgroundCapability=_hostAppHasBackgroundCapability;
@property(nonatomic, getter=isUpdatingLocation) _Bool updatingLocation; // @synthesize updatingLocation=_updatingLocation;
- (void)locationManager:(id)arg1 didChangeAuthorizationStatus:(int)arg2;
- (void)locationManager:(id)arg1 didExitRegion:(id)arg2;
- (void)locationManager:(id)arg1 didUpdateLocations:(id)arg2;
- (void)locationManagerDidPauseLocationUpdates:(id)arg1;
@property(retain, nonatomic) CLLocationManager *standardLocationManager; // @synthesize standardLocationManager=_standardLocationManager;
- (void)startBackgroundTimeoutTimer;
- (void)startLocationServices;
- (void)startUpdatingLocation;
- (void)stopUpdatingLocation;
- (void)timeoutAllowedCheck;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

