//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MGLMapView, NSString;

@interface MGLSource : NSObject
{
    unique_ptr_75027eea _pendingSource;
    NSString *_identifier;
    struct Source *_rawSource;
    MGLMapView *_mapView;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)addToMapView:(id)arg1;
- (id)description;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (id)initWithIdentifier:(id)arg1;
- (id)initWithPendingSource:(unique_ptr_75027eea)arg1;
- (id)initWithRawSource:(struct Source *)arg1 mapView:(id)arg2;
@property(readonly, nonatomic) __weak MGLMapView *mapView; // @synthesize mapView=_mapView;
@property(readonly, nonatomic) struct Source *rawSource; // @synthesize rawSource=_rawSource;
- (void)removeFromMapView:(id)arg1;

@end

