//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCAUserTrackedEvent.h"

@class NSNumber, NSString;

@interface SCABackgroundPrefetchFinished : SCAUserTrackedEvent
{
    NSNumber *processLatencyMs;
    long long appState;
    NSString *batteryState;
    NSString *networkState;
    NSString *mediaType;
    NSString *prefetchResult;
    NSString *prefetchId;
}

- (void).cxx_destruct;
- (id)asDictionary;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (long long)getAppState;
- (id)getBatteryState;
- (id)getEventName;
- (long long)getEventQoS;
- (id)getMediaType;
- (id)getNetworkState;
- (double)getPerUserSamplingRate;
- (id)getPrefetchId;
- (id)getPrefetchResult;
- (long long)getProcessLatencyMs;
- (id)init;
- (void)setAppState:(long long)arg1;
- (void)setBatteryState:(id)arg1;
- (void)setMediaType:(id)arg1;
- (void)setNetworkState:(id)arg1;
- (void)setPrefetchId:(id)arg1;
- (void)setPrefetchResult:(id)arg1;
- (void)setProcessLatencyMs:(long long)arg1;

@end

