//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCACommerceEventBase.h"

@class NSNumber, NSString;

@interface SCACommerceRestActionEvent : SCACommerceEventBase
{
    NSNumber *requestResult;
    NSNumber *statusCode;
    NSNumber *latency;
    long long endpoint;
    long long action;
    NSString *commerceErrorCode;
}

- (void).cxx_destruct;
- (id)asDictionary;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (long long)getAction;
- (id)getCommerceErrorCode;
- (long long)getEndpoint;
- (id)getEventName;
- (long long)getEventQoS;
- (long long)getLatency;
- (double)getPerUserSamplingRate;
- (_Bool)getRequestResult;
- (long long)getStatusCode;
- (id)init;
- (void)setAction:(long long)arg1;
- (void)setCommerceErrorCode:(id)arg1;
- (void)setEndpoint:(long long)arg1;
- (void)setLatency:(long long)arg1;
- (void)setRequestResult:(_Bool)arg1;
- (void)setStatusCode:(long long)arg1;

@end

