//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCAUserTrackedEvent.h"

@class NSNumber;

@interface SCACameraPageView : SCAUserTrackedEvent
{
    NSNumber *filterGeolensCount;
    NSNumber *filterLensCount;
    NSNumber *filterGeofilterCount;
    NSNumber *filterLensStoreCount;
    NSNumber *withGeolocation;
    NSNumber *viewTimeSec;
    NSNumber *withFilterLensSwipe;
    long long pageName;
    long long exitEvent;
}

- (void).cxx_destruct;
- (id)asDictionary;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)getEventName;
- (long long)getEventQoS;
- (long long)getExitEvent;
- (long long)getFilterGeofilterCount;
- (long long)getFilterGeolensCount;
- (long long)getFilterLensCount;
- (long long)getFilterLensStoreCount;
- (long long)getPageName;
- (double)getPerUserSamplingRate;
- (double)getViewTimeSec;
- (_Bool)getWithFilterLensSwipe;
- (_Bool)getWithGeolocation;
- (id)init;
- (void)setExitEvent:(long long)arg1;
- (void)setFilterGeofilterCount:(long long)arg1;
- (void)setFilterGeolensCount:(long long)arg1;
- (void)setFilterLensCount:(long long)arg1;
- (void)setFilterLensStoreCount:(long long)arg1;
- (void)setPageName:(long long)arg1;
- (void)setViewTimeSec:(double)arg1;
- (void)setWithFilterLensSwipe:(_Bool)arg1;
- (void)setWithGeolocation:(_Bool)arg1;

@end

