//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCACommerceApiEventBase.h"

@class NSNumber, NSString;

@interface SCACommerceShippingMethodApiEvent : SCACommerceApiEventBase
{
    NSNumber *shippingAmount;
    long long currencyType;
    NSString *shippingMethodId;
}

- (void).cxx_destruct;
- (id)asDictionary;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (long long)getCurrencyType;
- (id)getEventName;
- (long long)getEventQoS;
- (double)getPerUserSamplingRate;
- (double)getShippingAmount;
- (id)getShippingMethodId;
- (id)init;
- (void)setCurrencyType:(long long)arg1;
- (void)setShippingAmount:(double)arg1;
- (void)setShippingMethodId:(id)arg1;

@end

