//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"
#import "NamedEvent-Protocol.h"

@class NSNumber, NSString;

@interface SCAChatDockMetadata : NSObject <NamedEvent, NSCopying>
{
    NSNumber *groupSize;
    NSString *chatDockId;
}

- (void).cxx_destruct;
- (id)asDictionary;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)getChatDockId;
- (id)getEventName;
- (long long)getEventQoS;
- (long long)getGroupSize;
- (double)getPerEventSamplingRate;
- (double)getPerUserSamplingRate;
- (void)setChatDockId:(id)arg1;
- (void)setGroupSize:(long long)arg1;

@end

