//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCACommercePageEventBase.h"

@class NSNumber;

@interface SCACommercePageCloseEvent : SCACommercePageEventBase
{
    NSNumber *timeSpent;
    long long destinationPage;
}

- (void).cxx_destruct;
- (id)asDictionary;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (long long)getDestinationPage;
- (id)getEventName;
- (long long)getEventQoS;
- (double)getPerUserSamplingRate;
- (long long)getTimeSpent;
- (id)init;
- (void)setDestinationPage:(long long)arg1;
- (void)setTimeSpent:(long long)arg1;

@end

