//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, UIImage;

@interface SCActionMenuItemConfig : NSObject
{
    _Bool _enabled;
    NSString *_title;
    UIImage *_icon;
    CDUnknownBlockType _tapHandler;
    CDUnknownBlockType _disabledTapHandler;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) CDUnknownBlockType disabledTapHandler; // @synthesize disabledTapHandler=_disabledTapHandler;
@property(readonly, nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
@property(readonly, nonatomic) UIImage *icon; // @synthesize icon=_icon;
- (id)initWithTitle:(id)arg1 icon:(id)arg2 enabled:(_Bool)arg3 tapHandler:(CDUnknownBlockType)arg4 disabledTapHandler:(CDUnknownBlockType)arg5;
@property(readonly, copy, nonatomic) CDUnknownBlockType tapHandler; // @synthesize tapHandler=_tapHandler;
@property(readonly, copy, nonatomic) NSString *title; // @synthesize title=_title;

@end

