//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class SCExperimentManager, SCLazy, SCPreferences;
@protocol SCAddFriendsBadgedIncomingFriendCountProviding;

@interface SCAddFriendsButtonFriendRequestTipAnimationDecider : NSObject
{
    id <SCAddFriendsBadgedIncomingFriendCountProviding> _addFriendsBadgedIncomingFriendCountProvider;
    SCPreferences *_userPreferences;
    SCExperimentManager *_experimentManager;
    SCLazy *_snapchattersDataProvider;
}

- (void).cxx_destruct;
- (void)_updateFriendRequestTipsTriggerDate;
- (id)initWithUserPreferences:(id)arg1 experimentManager:(id)arg2 snapchattersDataFetcher:(id)arg3 addFriendsBadgedIncomingFriendCountProvider:(id)arg4;
- (_Bool)shouldShowTip;

@end

