//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCAUserTrackedEvent.h"

@class NSNumber, NSString;

@interface SCADiscoverAdLongformShareCreate : SCAUserTrackedEvent
{
    NSNumber *snapIndexCount;
    NSNumber *snapIndexPos;
    NSNumber *timeViewed;
    NSNumber *adIndexCount;
    NSNumber *adIndexPos;
    long long entryEvent;
    long long mediaType;
    long long longformType;
    long long source;
    NSString *editionId;
    NSString *publisherId;
    NSString *adsnapId;
    NSString *adRequestClientId;
    NSString *adId;
    NSString *adsnapPlacementId;
    NSString *adsnapLineItemId;
    NSString *videoPartnerId;
}

- (void).cxx_destruct;
- (id)asDictionary;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)getAdId;
- (long long)getAdIndexCount;
- (long long)getAdIndexPos;
- (id)getAdRequestClientId;
- (id)getAdsnapId;
- (id)getAdsnapLineItemId;
- (id)getAdsnapPlacementId;
- (id)getEditionId;
- (long long)getEntryEvent;
- (id)getEventName;
- (long long)getEventQoS;
- (long long)getLongformType;
- (long long)getMediaType;
- (double)getPerUserSamplingRate;
- (id)getPublisherId;
- (long long)getSnapIndexCount;
- (long long)getSnapIndexPos;
- (long long)getSource;
- (double)getTimeViewed;
- (id)getVideoPartnerId;
- (id)init;
- (void)setAdId:(id)arg1;
- (void)setAdIndexCount:(long long)arg1;
- (void)setAdIndexPos:(long long)arg1;
- (void)setAdRequestClientId:(id)arg1;
- (void)setAdsnapId:(id)arg1;
- (void)setAdsnapLineItemId:(id)arg1;
- (void)setAdsnapPlacementId:(id)arg1;
- (void)setEditionId:(id)arg1;
- (void)setEntryEvent:(long long)arg1;
- (void)setLongformType:(long long)arg1;
- (void)setMediaType:(long long)arg1;
- (void)setPublisherId:(id)arg1;
- (void)setSnapIndexCount:(long long)arg1;
- (void)setSnapIndexPos:(long long)arg1;
- (void)setSource:(long long)arg1;
- (void)setTimeViewed:(double)arg1;
- (void)setVideoPartnerId:(id)arg1;

@end

