//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FriendStories.h"

@class NSArray, NSDate, NSString, SCSnapAdsAdResponse, Story;

@interface SCAdsStories : FriendStories
{
    NSDate *_creationTime;
    _Bool _isNoFill;
    _Bool _shouldTrack;
    NSString *_adUnitId;
    Story *_story;
    NSArray *_snapStories;
    SCSnapAdsAdResponse *_adResponseV2;
    NSString *_adId;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *adId; // @synthesize adId=_adId;
- (id)adRequestClientId;
@property(readonly, nonatomic) SCSnapAdsAdResponse *adResponseV2; // @synthesize adResponseV2=_adResponseV2;
@property(readonly, nonatomic) NSString *adUnitId; // @synthesize adUnitId=_adUnitId;
- (id)cacheMediaIds;
- (void)fetchAdMediaCompletion:(CDUnknownBlockType)arg1;
- (id)initWithAdResponse:(id)arg1 adUnitId:(id)arg2;
- (id)initWithAdResponse:(id)arg1 adUnitId:(id)arg2 shouldTrack:(_Bool)arg3;
- (_Bool)isMultiSnapsAd;
@property(readonly, nonatomic) _Bool isNoFill; // @synthesize isNoFill=_isNoFill;
- (_Bool)isNormalFriendStories;
- (_Bool)isValid:(long long)arg1;
- (void)mediaDownloadCompleteForSnapIndex:(long long)arg1 downloadTimeInSec:(double)arg2 isSuccess:(_Bool)arg3 error:(id)arg4;
- (_Bool)mediaExists;
- (_Bool)mediaExistsInCache;
- (id)mediaFileNames;
- (long long)mediaState;
@property(nonatomic) _Bool shouldTrack; // @synthesize shouldTrack=_shouldTrack;
@property(retain, nonatomic) NSArray *snapStories; // @synthesize snapStories=_snapStories;
@property(readonly, nonatomic) Story *story; // @synthesize story=_story;
- (void)updateMediaTypeForStory:(id)arg1;
- (id)username;

@end

