//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCOperaLayer-Protocol.h"

@class NSArray, NSString, NSURL, SCOperaPage;

@interface SCAdWebViewTopSnapLayer : NSObject <SCOperaLayer>
{
    NSURL *_url;
    NSArray *_cookies;
    long long _interactionZoneType;
    SCOperaPage *_page;
}

+ (id)layerWithProperties:(id)arg1 page:(id)arg2;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSArray *cookies; // @synthesize cookies=_cookies;
- (id)initWithProperties:(id)arg1 page:(id)arg2;
@property(nonatomic) long long interactionZoneType; // @synthesize interactionZoneType=_interactionZoneType;
- (_Bool)isEqual:(id)arg1;
@property(nonatomic) __weak SCOperaPage *page; // @synthesize page=_page;
- (unsigned long long)type;
@property(readonly, nonatomic) NSURL *url; // @synthesize url=_url;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

