//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCAUserTrackedEvent.h"

@class NSNumber;

@interface SCAFriendWidgetAction : SCAUserTrackedEvent
{
    NSNumber *widgetCount;
    NSNumber *widgetFriendCount;
    long long widgetType;
    long long action;
    long long target;
}

- (void).cxx_destruct;
- (id)asDictionary;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (long long)getAction;
- (id)getEventName;
- (long long)getEventQoS;
- (double)getPerUserSamplingRate;
- (long long)getTarget;
- (long long)getWidgetCount;
- (long long)getWidgetFriendCount;
- (long long)getWidgetType;
- (id)init;
- (void)setAction:(long long)arg1;
- (void)setTarget:(long long)arg1;
- (void)setWidgetCount:(long long)arg1;
- (void)setWidgetFriendCount:(long long)arg1;
- (void)setWidgetType:(long long)arg1;

@end

