//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCAUserTrackedEvent.h"

@class NSNumber, NSString;

@interface SCAGeofilterOndemandEventBase : SCAUserTrackedEvent
{
    NSNumber *pageSequenceId;
    long long pageName;
    long long productType;
    NSString *odgSessionId;
    NSString *adAccountId;
    NSString *source;
    NSString *referrer;
}

- (void).cxx_destruct;
- (id)asDictionary;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)getAdAccountId;
- (id)getEventName;
- (long long)getEventQoS;
- (id)getOdgSessionId;
- (long long)getPageName;
- (long long)getPageSequenceId;
- (double)getPerUserSamplingRate;
- (long long)getProductType;
- (id)getReferrer;
- (id)getSource;
- (id)init;
- (void)setAdAccountId:(id)arg1;
- (void)setOdgSessionId:(id)arg1;
- (void)setPageName:(long long)arg1;
- (void)setPageSequenceId:(long long)arg1;
- (void)setProductType:(long long)arg1;
- (void)setReferrer:(id)arg1;
- (void)setSource:(id)arg1;

@end

