//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCAUserTrackedEvent.h"

@class NSString;

@interface SCAGalleryException : SCAUserTrackedEvent
{
    NSString *exceptionType;
    NSString *errorMessage;
    NSString *extraParams;
}

- (void).cxx_destruct;
- (id)asDictionary;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)getErrorMessage;
- (id)getEventName;
- (long long)getEventQoS;
- (id)getExceptionType;
- (id)getExtraParams;
- (double)getPerUserSamplingRate;
- (void)setErrorMessage:(id)arg1;
- (void)setExceptionType:(id)arg1;
- (void)setExtraParams:(id)arg1;

@end

