//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCAGalleryBrowseSnapBase.h"

@class NSNumber, NSString;

@interface SCAGeofilterGalleryBrowseSnapView : SCAGalleryBrowseSnapBase
{
    NSNumber *filterIndexPos;
    NSNumber *filterIndexCount;
    NSString *adsnapPlacementId;
    NSString *encGeoData;
    NSString *filterGeofilterId;
    NSString *filterGeolensId;
    NSString *lensOptionId;
}

- (void).cxx_destruct;
- (id)asDictionary;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)getAdsnapPlacementId;
- (id)getEncGeoData;
- (id)getEventName;
- (long long)getEventQoS;
- (id)getFilterGeofilterId;
- (id)getFilterGeolensId;
- (long long)getFilterIndexCount;
- (long long)getFilterIndexPos;
- (id)getLensOptionId;
- (double)getPerUserSamplingRate;
- (void)setAdsnapPlacementId:(id)arg1;
- (void)setEncGeoData:(id)arg1;
- (void)setFilterGeofilterId:(id)arg1;
- (void)setFilterGeolensId:(id)arg1;
- (void)setFilterIndexCount:(long long)arg1;
- (void)setFilterIndexPos:(long long)arg1;
- (void)setLensOptionId:(id)arg1;

@end

