//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCAUserTrackedEvent.h"

@class NSString;

@interface SCAGalleryCellView : SCAUserTrackedEvent
{
    long long entryType;
    NSString *entryId;
    NSString *externalId;
    NSString *galleryCollectionCategory;
    NSString *galleryCollectionId;
}

- (void).cxx_destruct;
- (id)asDictionary;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)getEntryId;
- (long long)getEntryType;
- (id)getEventName;
- (long long)getEventQoS;
- (id)getExternalId;
- (id)getGalleryCollectionCategory;
- (id)getGalleryCollectionId;
- (double)getPerUserSamplingRate;
- (id)init;
- (void)setEntryId:(id)arg1;
- (void)setEntryType:(long long)arg1;
- (void)setExternalId:(id)arg1;
- (void)setGalleryCollectionCategory:(id)arg1;
- (void)setGalleryCollectionId:(id)arg1;

@end

