//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@interface SCApplicationLifecycleEvent : NSObject <NSCopying>
{
    unsigned long long _subtype;
}

+ (id)didBecomeActive;
+ (id)didEnterBackground;
+ (id)didFinishLaunching;
+ (id)didReceiveMemoryWarning;
+ (id)willEnterForeground;
+ (id)willResignActive;
+ (id)willTerminate;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)hash;
- (id)internalInit;
- (_Bool)isEqual:(id)arg1;
- (void)matchDidFinishLaunching:(CDUnknownBlockType)arg1 willEnterForeground:(CDUnknownBlockType)arg2 didBecomeActive:(CDUnknownBlockType)arg3 willResignActive:(CDUnknownBlockType)arg4 didEnterBackground:(CDUnknownBlockType)arg5 didReceiveMemoryWarning:(CDUnknownBlockType)arg6 willTerminate:(CDUnknownBlockType)arg7;

@end

