//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCNotificationManager-Protocol.h"
#import "SCTraceEnabled-Protocol.h"

@class NSMutableArray, NSMutableDictionary, NSString;

@interface SCAppNotificationProvider : NSObject <SCTraceEnabled, SCNotificationManager>
{
    NSMutableArray *_processorDelegates;
    NSMutableDictionary *_activeNotifications;
    NSMutableDictionary *_talkNotificationStartTimes;
    NSMutableDictionary *_notificationExpirationTimers;
    NSMutableDictionary *_notificationPresenters;
    NSMutableDictionary *_receivedPushNotifications;
}

- (void).cxx_destruct;
- (void)addNotification:(id)arg1;
- (void)addNotification:(id)arg1 withSystemCompletion:(id)arg2;
- (void)addNotificationToReceivedPushNotification:(id)arg1;
- (void)addProcessor:(id)arg1;
- (void)addToActiveNotificationExpirations:(id)arg1 withDuration:(double)arg2;
- (void)applicationDidBackground:(id)arg1;
- (void)applicationDidChangeState:(_Bool)arg1;
- (void)applicationWillForeground:(id)arg1;
- (_Bool)canDisplayNotification:(id)arg1;
- (void)checkHasNotificationExpired:(id)arg1;
- (void)clearExpiredPushNotification:(double)arg1;
- (id)currentNotifications;
- (id)delegateForAppState;
- (id)init;
- (void)initReceivedPushNotificationList;
- (void)prepareToReplaceNotification:(id)arg1;
- (id)receivedPushNotificationForTargetScreen:(unsigned long long)arg1;
- (void)registerPushNotificationPresenter:(id)arg1 presenter:(id)arg2;
- (void)removeNotification:(id)arg1;
- (void)removeProcessor:(id)arg1;
- (void)removePushNotificationsForTargetScreen:(unsigned long long)arg1;
- (void)removePushNotificationsFromReceivedPushNotificationList:(id)arg1;
- (void)unregisterPushNotificationPresenter:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

