//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCASpectaclesTrackedEvent.h"

@class NSNumber, NSString;

@interface SCASpectaclesPairingEventBase : SCASpectaclesTrackedEvent
{
    NSNumber *retryCount;
    NSNumber *durationSec;
    long long pairingType;
    long long pairingSource;
    long long bleState;
    long long btcState;
    NSString *pairingSessionId;
}

- (void).cxx_destruct;
- (id)asDictionary;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (long long)getBleState;
- (long long)getBtcState;
- (double)getDurationSec;
- (id)getEventName;
- (long long)getEventQoS;
- (id)getPairingSessionId;
- (long long)getPairingSource;
- (long long)getPairingType;
- (double)getPerUserSamplingRate;
- (long long)getRetryCount;
- (id)init;
- (void)setBleState:(long long)arg1;
- (void)setBtcState:(long long)arg1;
- (void)setDurationSec:(double)arg1;
- (void)setPairingSessionId:(id)arg1;
- (void)setPairingSource:(long long)arg1;
- (void)setPairingType:(long long)arg1;
- (void)setRetryCount:(long long)arg1;

@end

