//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCAsyncCommandVisitorDelegate-Protocol.h"
#import "SCConcurrentGraphTraverserDelegate-Protocol.h"

@class NSMapTable, NSString, SCConcurrentGraphTraverser, SCMutableGraphVertex, SCPerformerPool, SCQueuePerformer;

@interface SCAsyncCommandRunner : NSObject <SCAsyncCommandVisitorDelegate, SCConcurrentGraphTraverserDelegate>
{
    NSMapTable *_asyncCommandMap;
    SCPerformerPool *_performerPool;
    SCMutableGraphVertex *_rootVertex;
    unsigned long long _state;
    SCConcurrentGraphTraverser *_traverser;
    long long _vertexCount;
    long long _visitCount;
    SCQueuePerformer *_runPerfomer;
    SCQueuePerformer *_teardownPerfomer;
}

+ (id)_createErrorWithMessage:(id)arg1 code:(long long)arg2;
- (void).cxx_destruct;
- (void)_finishIfNeeded;
- (_Bool)_transitionToState:(unsigned long long)arg1;
- (id)concurrentGraphTraverser:(id)arg1 perfomerToExecuteFromVertexConcurrently:(id)arg2;
- (_Bool)concurrentGraphTraverser:(id)arg1 shouldExecuteFromVertexConcurrently:(id)arg2;
@property(readonly, nonatomic) long long count;
- (id)initWithPerformerPool:(id)arg1;
- (void)insertCommand:(id)arg1;
- (void)insertCommand:(id)arg1 dependUponCommand:(id)arg2;
- (void)insertCommand:(id)arg1 dependUponCommand:(id)arg2 performerPool:(id)arg3;
- (void)insertCommand:(id)arg1 performerPool:(id)arg2;
- (void)run:(id *)arg1;
@property(readonly, nonatomic) unsigned long long state;
- (void)visitor:(id)arg1 didVisit:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

