//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCASpectaclesTrackedEvent.h"

@class NSNumber;

@interface SCASpectaclesTemperatureTrackedEvent : SCASpectaclesTrackedEvent
{
    NSNumber *ambaTemperature;
    NSNumber *nordicTemperature;
    NSNumber *coulombCtrlTemperature;
    NSNumber *wifiTemperature;
    NSNumber *qcaTemperature;
    NSNumber *temperatureReportUtc;
}

- (void).cxx_destruct;
- (id)asDictionary;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (long long)getAmbaTemperature;
- (long long)getCoulombCtrlTemperature;
- (id)getEventName;
- (long long)getEventQoS;
- (long long)getNordicTemperature;
- (double)getPerUserSamplingRate;
- (long long)getQcaTemperature;
- (long long)getTemperatureReportUtc;
- (long long)getWifiTemperature;
- (void)setAmbaTemperature:(long long)arg1;
- (void)setCoulombCtrlTemperature:(long long)arg1;
- (void)setNordicTemperature:(long long)arg1;
- (void)setQcaTemperature:(long long)arg1;
- (void)setTemperatureReportUtc:(long long)arg1;
- (void)setWifiTemperature:(long long)arg1;

@end

