//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCAUserTrackedEvent.h"

@class NSNumber, NSString;

@interface SCASnapcodeManagerScan : SCAUserTrackedEvent
{
    NSNumber *snapcodeCount;
    NSNumber *snapcodeWithImageCount;
    NSString *scanData;
    NSString *scannableId;
    NSString *snapcodeSessionId;
}

- (void).cxx_destruct;
- (id)asDictionary;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)getEventName;
- (long long)getEventQoS;
- (double)getPerUserSamplingRate;
- (id)getScanData;
- (id)getScannableId;
- (long long)getSnapcodeCount;
- (id)getSnapcodeSessionId;
- (long long)getSnapcodeWithImageCount;
- (void)setScanData:(id)arg1;
- (void)setScannableId:(id)arg1;
- (void)setSnapcodeCount:(long long)arg1;
- (void)setSnapcodeSessionId:(id)arg1;
- (void)setSnapcodeWithImageCount:(long long)arg1;

@end

