//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SCAudioConfigurationMaker : NSObject
{
}

+ (id)_configurationForAudioAnalysis;
+ (id)_configurationForAudioNotePlayer;
+ (id)_configurationForAudioNoteRecorder;
+ (id)_configurationForCallKitEarpiece;
+ (id)_configurationForCallKitSpeakers;
+ (id)_configurationForCameraRecording;
+ (id)_configurationForPreview;
+ (id)_configurationForShazam;
+ (id)_configurationForTalk;
+ (id)_configurationForTalkListener;
+ (id)_configurationForVideoNotePlayer;
+ (id)_configurationForVideoNoteRecorder;
+ (id)_templateBuilder;
+ (id)makeConfigurationFor:(long long)arg1;

@end

