//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCAUnifiedProfileBaseEvent.h"

@class NSNumber, NSString;

@interface SCAUnifiedProfilePageView : SCAUnifiedProfileBaseEvent
{
    NSNumber *hasBitmojiInstalled;
    NSString *sourcePageType;
}

- (void).cxx_destruct;
- (id)asDictionary;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)getEventName;
- (long long)getEventQoS;
- (_Bool)getHasBitmojiInstalled;
- (double)getPerUserSamplingRate;
- (id)getSourcePageType;
- (void)setHasBitmojiInstalled:(_Bool)arg1;
- (void)setSourcePageType:(id)arg1;

@end

