//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCBaseMediaMessageOperaDataSource.h"

@class NSString, SCBaseDiscoverMediaImageProvider, SCBaseMediaThumbnailViewModel, SCOperaViewModel;
@protocol SCOperaGifProvider><SCOperaImageProvider;

@interface SCBaseDiscoverMediaOperaDataSource : SCBaseMediaMessageOperaDataSource
{
    SCBaseMediaThumbnailViewModel *_viewModel;
    SCBaseDiscoverMediaImageProvider *_mediaProvider;
    struct CGSize _lowResolImageSize;
    _Bool _shouldEnableZoom;
    _Bool _containsMultipleMedias;
    _Bool _needToAnimationBaseThumbnailViewWhenClosing;
    NSString *_conversationId;
    SCOperaViewModel *_rootViewModel;
    id <SCOperaGifProvider><SCOperaImageProvider> _imageProvider;
    long long _messageType;
}

- (void).cxx_destruct;
- (id)_actionMenuPageProperties;
- (void)_appenedPropertiesToPage:(id)arg1 newProperties:(id)arg2;
- (id)_footerBarAndActionMenuHeaderPageProperties;
- (id)_footerBarDeepLinkTextBasedOnContents:(id)arg1;
- (void)_initWithRootViewModel;
- (_Bool)containsMultipleMedias;
- (id)conversationId;
- (id)discoverMediaBlobMetadata;
- (id)imageProvider;
- (id)initWithViewModel:(id)arg1;
- (id)messageIdForPage:(id)arg1;
- (long long)messageType;
- (_Bool)needToAnimationBaseThumbnailViewWhenClosing;
- (id)rootViewModel;
- (void)setRootIndex:(unsigned long long)arg1;
- (void)setRootViewModel:(id)arg1;
- (_Bool)shouldEnableZoom;
- (void)updateFooterIfNecessary;
- (id)viewModelForPageId:(id)arg1;

@end

