//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCStickerImageLoaderProtocol-Protocol.h"
#import "SCStickerThumbnailImageLoaderProtocol-Protocol.h"

@class NSString, SCBitmojiManager, SCQueuePerformer;

@interface SCBitmojiStickerImageLoader : NSObject <SCStickerImageLoaderProtocol, SCStickerThumbnailImageLoaderProtocol>
{
    SCBitmojiManager *_bitmojiManager;
    SCQueuePerformer *_performer;
}

- (void).cxx_destruct;
- (id)_buildContexts:(id)arg1 withSticker:(id)arg2;
- (long long)_determineAttributionFromContext:(id)arg1;
- (id)_issueStickerFetchForSticker:(id)arg1 forThumbnail:(_Bool)arg2 contexts:(id)arg3 isDecoded:(_Bool)arg4 completionQueue:(id)arg5 completionBlock:(CDUnknownBlockType)arg6;
@property(readonly, nonatomic) SCBitmojiManager *bitmojiManager; // @synthesize bitmojiManager=_bitmojiManager;
- (id)initWithBitmojiManager:(id)arg1 performer:(id)arg2;
- (id)loadStickerImageForSticker:(id)arg1 contexts:(id)arg2 willAcceptLowRes:(_Bool)arg3 isDecoded:(_Bool)arg4 completionQueue:(id)arg5 completionBlock:(CDUnknownBlockType)arg6;
- (id)loadStickerThumbnailImageForSticker:(id)arg1 size:(struct CGSize)arg2 contexts:(id)arg3 completionQueue:(id)arg4 completionBlock:(CDUnknownBlockType)arg5;
@property(readonly, nonatomic) SCQueuePerformer *performer; // @synthesize performer=_performer;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

