//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSError, NSString;

@protocol SCChunk <NSObject>
@property(readonly, copy, nonatomic) NSString *chunkHash;
- (void)clearLoadedSections;
- (void)didFinishLoadingSectionsWithSuccess:(_Bool)arg1 error:(NSError *)arg2 downloadTimeInSec:(double)arg3;
- (void)didLoadSections:(NSArray *)arg1;
@property(readonly, copy, nonatomic) NSString *endpoint;
- (_Bool)isLoaded;
@property(readonly, nonatomic) _Bool isLoading;
@property(readonly, nonatomic) NSArray *loadedSections;
@property(readonly, nonatomic) NSError *loadingError;
- (NSString *)mediaId;
@property(readonly, nonatomic) long long numBytes;
- (void)setNumBytes:(long long)arg1;
- (NSString *)uniqueId;
- (void)willStartLoadingSections;
@end

