//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCDataCoordinating-Protocol.h"
#import "SCUpdateListener-Protocol.h"

@class NSMutableDictionary, NSString, SCDataCoordinatorListenerAnnouncer, SCLazy, SCQueuePerformer, SCSnapchatterFriendStatusProvider;

@interface SCChatSnapchattersDataCoordinator : NSObject <SCUpdateListener, SCDataCoordinating>
{
    SCDataCoordinatorListenerAnnouncer *_eventAnnouncer;
    SCQueuePerformer *_performer;
    SCLazy *_snapchattersDataFetcher;
    SCLazy *_snapchatterPublicInfoFetcher;
    SCSnapchatterFriendStatusProvider *_friendStatusProvider;
    NSString *_activeConversationId;
    NSMutableDictionary *_userIdToSnapchatter;
    NSMutableDictionary *_userIdToFriendStatus;
}

+ (id)dataCoordinatorIdentifier;
- (void).cxx_destruct;
- (void)_announceDataCoordinatorUpdateWithDataRequest;
- (void)_fetchRemoteSnapchattersForUserIds:(id)arg1;
- (void)_fetchSnapchattersForUserIds:(id)arg1;
- (void)_handleActiveConversationDataRequest:(id)arg1;
- (void)_handleActiveRenderingConversationDataRequest:(id)arg1;
- (void)activeSnapchattersDataForConversationId:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)addDataUpdateListener:(id)arg1;
- (void)didUpdateWithAnnouncerIdentifier:(id)arg1;
- (void)handleDataRequest:(id)arg1;
- (id)initWithSnapchattersDataFetcher:(id)arg1 snapchattersPublicInfoFetcher:(id)arg2 snapchattersFriendStatusProvider:(id)arg3;
- (void)removeDataUpdateListener:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

