//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCCheetahLoggingSessionManaging-Protocol.h"

@class NSString, SCCheetahRankingEventLogger;
@protocol OS_dispatch_queue;

@interface SCCheetahLogger : NSObject <SCCheetahLoggingSessionManaging>
{
    SCCheetahRankingEventLogger *_rankingEventLogger;
    NSObject<OS_dispatch_queue> *_queue;
}

- (void).cxx_destruct;
- (void)_flushWithDate:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_logEvent:(id)arg1 data:(id)arg2;
- (id)_makeEventCriticalIfNecessary:(id)arg1 data:(id)arg2;
- (void)flushWithDate:(id)arg1 completion:(CDUnknownBlockType)arg2 extraData:(id)arg3;
- (id)initWithQueue:(id)arg1 snapTokenManager:(id)arg2 requestManager:(id)arg3;
- (void)logEvent:(id)arg1 data:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

