//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCActionable-Protocol.h"
#import "SCChatHamburgerTableSectionProtocol-Protocol.h"
#import "SCNotificationStatusCompletionDelegate-Protocol.h"
#import "SCRetentionPolicyDelegate-Protocol.h"
#import "SCSnapchattersDataRequestListener-Protocol.h"

@class NSArray, NSDictionary, NSString, SCLazy, SCSnapchatter;
@protocol SCActionHandling, SCChatHamburgerTableSectionDataSource, SCChatHamburgerTableSectionDelegate, SCChatHamburgerTableSectionPresentationDelegate;

@interface SCChatHamburgerOneOnOneSettingSection : NSObject <SCSnapchattersDataRequestListener, SCChatHamburgerTableSectionProtocol, SCActionable, SCNotificationStatusCompletionDelegate, SCRetentionPolicyDelegate>
{
    SCSnapchatter *_snapchatter;
    SCLazy *_dataProvider;
    SCLazy *_dataTrackor;
    _Bool _isDoNotDisturb;
    unsigned long long _messageRetentionInMinutes;
    NSArray *_cellTypeIndex;
    id <SCChatHamburgerTableSectionDataSource> _tableDataSource;
    id <SCChatHamburgerTableSectionDelegate> _tableDelegate;
    id <SCChatHamburgerTableSectionPresentationDelegate> _presentationDelegate;
    id <SCActionHandling> _actionHandler;
}

- (void).cxx_destruct;
- (void)_reloadSettingSection;
- (void)_setCellTypeIndex;
- (void)_setSnapchatterAndReloadIfNecessary;
@property(retain, nonatomic) id <SCActionHandling> actionHandler; // @synthesize actionHandler=_actionHandler;
- (id)cellForRowAtIndex:(unsigned long long)arg1;
- (void)didChangeNotificationStatusWithSuccess:(_Bool)arg1 isDotNotDisturb:(_Bool)arg2;
- (void)didChangeRetentionPolicyWithSuccess:(_Bool)arg1 retentionInMinutes:(unsigned long long)arg2;
- (void)didEndSnapchattersUpdateDataRequest:(id)arg1 withSuccess:(_Bool)arg2;
- (void)didStartChangeNotificationStatus:(_Bool)arg1;
- (void)didStartChangeRetentionPolicy;
- (void)didStartSnapchattersUpdateDataRequest:(id)arg1;
- (double)heightForCellAtIndex:(unsigned long long)arg1;
- (id)initWithSnapchatter:(id)arg1 dataProvider:(id)arg2 dataTracker:(id)arg3 isDoNotDisturb:(_Bool)arg4 messageRetentionPolicy:(unsigned long long)arg5;
- (unsigned long long)numberOfCells;
@property(nonatomic) __weak id <SCChatHamburgerTableSectionPresentationDelegate> presentationDelegate; // @synthesize presentationDelegate=_presentationDelegate;
- (void)resetSection;
@property(readonly, copy, nonatomic) NSDictionary *reuseCellClassesByIdentifiers;
- (unsigned long long)roundedCornerAtIndex:(unsigned long long)arg1;
@property(nonatomic) __weak id <SCChatHamburgerTableSectionDataSource> tableDataSource; // @synthesize tableDataSource=_tableDataSource;
@property(nonatomic) __weak id <SCChatHamburgerTableSectionDelegate> tableDelegate; // @synthesize tableDelegate=_tableDelegate;
- (id)settingCellViewModelAtIndex:(unsigned long long)arg1;
- (id)settingCellViewModelWithCellType:(unsigned long long)arg1 roundedCorner:(unsigned long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

