//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "SCChatInputBarStateManagerDatasource-Protocol.h"
#import "SCChatInputBarStateManagerDelegate-Protocol.h"
#import "SCChatInputStylable-Protocol.h"
#import "SCChatInputTextViewListener-Protocol.h"
#import "SCTraceEnabled-Protocol.h"

@class NSArray, NSLayoutConstraint, NSString, SCChatInputBarStateManager, SCChatInputStackView, SCChatInputTextView, SCChatInputTextViewContainer, SCChatInputViewController, SCLazy, UIViewPropertyAnimator;
@protocol SCChatInputTextViewPasteDelegate;

@interface SCChatInputBar : UIView <SCTraceEnabled, SCChatInputBarStateManagerDelegate, SCChatInputBarStateManagerDatasource, SCChatInputTextViewListener, SCChatInputStylable>
{
    UIView *_separator;
    NSLayoutConstraint *_textViewHeightAnchor;
    UIViewPropertyAnimator *_layoutAnimator;
    UIViewPropertyAnimator *_itemAnimator;
    NSLayoutConstraint *_textContainerBottomConstraint;
    SCChatInputBarStateManager *_stateManager;
    SCLazy *_backgroundView;
    unsigned long long _style;
    _Bool _gradientHidden;
    _Bool _ignoresSafeAreaLayoutGuides;
    SCChatInputViewController *_inputController;
    SCChatInputTextViewContainer *_inputTextViewContainer;
    SCChatInputStackView *_leadingStackView;
    SCChatInputStackView *_trailingStackView;
}

- (void).cxx_destruct;
- (void)_announceSizeUpdate;
- (void)_createConstraints;
- (void)_createLeftStackViewConstraints;
- (void)_createRightStackViewConstraints;
- (void)_createSeparatorConstraints;
- (void)_createTextViewContainerConstraints;
- (void)_initializeLeftStackView;
- (void)_initializeRightStackView;
- (void)_initializeSeparator;
- (void)_initializeTextViewContainer;
- (void)_initializeViews;
- (void)_insertGradientView;
- (id)_stackViewAtPosition:(unsigned long long)arg1;
- (void)_updateBottomConstraint;
- (void)_updateItems:(id)arg1 withVisibility:(unsigned long long)arg2;
- (void)_updateTextViewHeightConstraint;
- (void)addInputItem:(id)arg1 atPosition:(unsigned long long)arg2 animationStyle:(unsigned long long)arg3;
- (_Bool)becomeFirstResponder;
@property(nonatomic) _Bool ignoresSafeAreaLayoutGuides; // @synthesize ignoresSafeAreaLayoutGuides=_ignoresSafeAreaLayoutGuides;
- (id)init;
- (void)inputBarStateManager:(id)arg1 didUpdateInputBarState:(unsigned long long)arg2;
@property(nonatomic) __weak SCChatInputViewController *inputController; // @synthesize inputController=_inputController;
@property(readonly, nonatomic) NSArray *inputItems;
@property(readonly, nonatomic) SCChatInputTextView *inputTextView;
@property(readonly, nonatomic) SCChatInputTextViewContainer *inputTextViewContainer; // @synthesize inputTextViewContainer=_inputTextViewContainer;
- (void)inputViewController:(id)arg1 textView:(id)arg2 willChangeTextInRange:(struct _NSRange)arg3 replacementText:(id)arg4;
- (void)inputViewController:(id)arg1 textViewDidChange:(id)arg2;
- (void)inputViewController:(id)arg1 textViewWillBeginEditing:(id)arg2;
- (void)inputViewController:(id)arg1 textViewWillEndEditing:(id)arg2;
- (void)insertInputItem:(id)arg1 atIndex:(unsigned long long)arg2 position:(unsigned long long)arg3 animationStyle:(unsigned long long)arg4;
@property(readonly, nonatomic) SCChatInputStackView *internalStackView;
- (_Bool)isFirstResponder;
@property(nonatomic, getter=isGradientHidden) _Bool gradientHidden; // @synthesize gradientHidden=_gradientHidden;
@property(readonly, nonatomic) SCChatInputStackView *leadingStackView; // @synthesize leadingStackView=_leadingStackView;
- (_Bool)resignFirstResponder;
- (void)setInputItems:(id)arg1 forPosition:(unsigned long long)arg2;
- (void)setStyle:(unsigned long long)arg1;
@property(nonatomic) __weak id <SCChatInputTextViewPasteDelegate> textViewPasteDelegate;
- (id)stateManagerTextView;
@property(readonly, nonatomic) SCChatInputStackView *trailingStackView; // @synthesize trailingStackView=_trailingStackView;
- (void)updateVisibleItemsForState:(unsigned long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

