//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSDictionary;

@interface SCChecksums : NSObject <NSCoding>
{
    _Bool _isStoriesPaginated;
    NSDictionary *_checksums;
    long long _missingReason;
    long long _storiesSyncMetadataVersion;
}

- (void).cxx_destruct;
- (id)allUpdatesChecksumsString;
- (id)checksumForKey:(id)arg1;
@property(readonly, copy, nonatomic) NSDictionary *checksums; // @synthesize checksums=_checksums;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithChecksums:(id)arg1 missingReason:(long long)arg2 storiesSyncMetadataVersion:(long long)arg3 isStoriesPaginated:(_Bool)arg4;
- (id)initWithCoder:(id)arg1;
- (_Bool)isStoriesChecksumsMissing;
@property(readonly, nonatomic) _Bool isStoriesPaginated; // @synthesize isStoriesPaginated=_isStoriesPaginated;
@property(readonly, nonatomic) long long missingReason; // @synthesize missingReason=_missingReason;
@property(readonly, nonatomic) long long storiesSyncMetadataVersion; // @synthesize storiesSyncMetadataVersion=_storiesSyncMetadataVersion;
- (id)toStoriesSyncMetadata;

@end

