//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCChatConversationUpdaterListener-Protocol.h"
#import "SCChatHamburgerGroupStoryCellDelegate-Protocol.h"
#import "SCChatHamburgerRoundedCornerCellDelegate-Protocol.h"
#import "SCChatHamburgerTableSectionProtocol-Protocol.h"
#import "SCChatStoryIconUpdater-Protocol.h"

@class NSDictionary, NSString, SCChatHamburgerTableSectionGroupStoryCell, SCMyGroupStories, SCUserSession, UIView;
@protocol SCChatGroup, SCChatHamburgerTableSectionDataSource, SCChatHamburgerTableSectionDelegate, SCChatHamburgerTableSectionGroupStoryDelegate, SCChatHamburgerTableSectionPresentationDelegate, SCChatStoryDelegate, SCReplyDelegate;

@interface SCChatHamburgerTableSectionGroupStory : NSObject <SCChatHamburgerGroupStoryCellDelegate, SCChatHamburgerRoundedCornerCellDelegate, SCChatHamburgerTableSectionProtocol, SCChatStoryIconUpdater, SCChatConversationUpdaterListener>
{
    SCUserSession *_userSession;
    SCChatHamburgerTableSectionGroupStoryCell *_castCell;
    SCMyGroupStories *_groupStories;
    NSString *_title;
    id <SCChatGroup> _group;
    id <SCChatHamburgerTableSectionDataSource> tableDataSource;
    id <SCChatHamburgerTableSectionDelegate> tableDelegate;
    id <SCChatHamburgerTableSectionPresentationDelegate> presentationDelegate;
    id <SCChatHamburgerTableSectionGroupStoryDelegate> _delegate;
    id <SCChatStoryDelegate> _storyDelegate;
    id <SCReplyDelegate> _replyDelegate;
    NSDictionary *_reuseCellClassesByIdentifiers;
    NSString *_conversationId;
    UIView *_dismissView;
}

- (void).cxx_destruct;
- (id)_groupStoryName;
- (id)_groupStoryNameWithMaxWidth:(double)arg1 font:(id)arg2;
- (void)addToStoriesTapped:(id)arg1;
- (id)cellForRowAtIndex:(unsigned long long)arg1;
@property(copy, nonatomic) NSString *conversationId; // @synthesize conversationId=_conversationId;
@property(nonatomic) __weak id <SCChatHamburgerTableSectionGroupStoryDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didConversationViewModelChange:(id)arg1;
@property(nonatomic) __weak UIView *dismissView; // @synthesize dismissView=_dismissView;
- (void)hamburgerRoundedCornerCellTapped:(id)arg1;
- (void)handleAvatarTapped:(id)arg1 avatar:(id)arg2;
- (void)handleCellTapped:(id)arg1;
- (double)heightForCellAtIndex:(unsigned long long)arg1;
- (id)initWithConversationId:(id)arg1 userSession:(id)arg2 title:(id)arg3 group:(id)arg4;
- (unsigned long long)numberOfCells;
@property(nonatomic) __weak id <SCChatHamburgerTableSectionPresentationDelegate> presentationDelegate; // @synthesize presentationDelegate;
- (void)reloadStoryIcon;
@property(nonatomic) __weak id <SCReplyDelegate> replyDelegate; // @synthesize replyDelegate=_replyDelegate;
- (void)resetSection;
@property(copy, nonatomic) NSDictionary *reuseCellClassesByIdentifiers; // @synthesize reuseCellClassesByIdentifiers=_reuseCellClassesByIdentifiers;
@property(nonatomic) __weak id <SCChatStoryDelegate> storyDelegate; // @synthesize storyDelegate=_storyDelegate;
@property(nonatomic) __weak id <SCChatHamburgerTableSectionDataSource> tableDataSource; // @synthesize tableDataSource;
@property(nonatomic) __weak id <SCChatHamburgerTableSectionDelegate> tableDelegate; // @synthesize tableDelegate;
- (id)storyDismissView;
- (void)willDisplayCell:(id)arg1 forRowAtIndex:(unsigned long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

