//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDate, NSString;

@interface SCCloudSyncOperation : NSObject
{
    NSDate *_operationStartNetworkProcessingTimestampUtc;
}

+ (id)deserialize:(id)arg1 requestID:(id)arg2;
+ (unsigned long long)numberOfSnapsForPayload:(id)arg1 requestID:(id)arg2;
+ (void)snaps:(id *)arg1 details:(id *)arg2 private:(_Bool *)arg3 forPayload:(id)arg4 requestID:(id)arg5;
- (void).cxx_destruct;
- (_Bool)allMediaUploadsComplete;
- (id)changedSnapContextsWithEntryUpdate:(id)arg1;
- (id)cleanupContextForOutOfOrderDeletion;
- (void)cleanupWithContext:(id)arg1 cloudFS:(id)arg2 dataSource:(id)arg3;
- (id)commitWithEntryUpdates:(id)arg1 dataObjectContext:(id)arg2;
- (id)detectAndResolveConflictsWithCloudFS:(id)arg1 dataObjectContext:(id)arg2 logger:(id)arg3;
- (_Bool)doesNotRequireMediaUpload;
- (_Bool)eligibleForOutOfOrderExecution;
@property(readonly, copy, nonatomic) NSArray *entryIds;
- (double)estimatedUploadTimeWithUserSession:(id)arg1;
- (_Bool)executeOptimisticallyWithDataObjectContext:(id)arg1 logger:(id)arg2;
- (id)initWithSnapshot:(id)arg1 requestID:(id)arg2;
- (_Bool)isOperationFromRetryEntry;
- (_Bool)isOperationValidBeforeRemoteSync:(id)arg1;
- (id)logParameters;
- (id)makeSnapshot;
- (_Bool)needRunImmediately;
@property(copy, nonatomic) NSDate *operationStartNetworkProcessingTimestampUtc; // @synthesize operationStartNetworkProcessingTimestampUtc=_operationStartNetworkProcessingTimestampUtc;
- (void)prepareRemoteSyncWithDataObjectContext:(id)arg1 cloudFS:(id)arg2 dataVault:(id)arg3 networker:(id)arg4 logger:(id)arg5 queue:(id)arg6 completionHandler:(CDUnknownBlockType)arg7;
- (id)processAndCleanupForOutOfOrderDeletions:(id)arg1 dataSource:(id)arg2 logger:(id)arg3 queue:(id)arg4;
- (void)recordOperationStartNetworkProcessing;
- (void)remoteSyncFromSequenceNumber:(long long)arg1 cloudFS:(id)arg2 dataVault:(id)arg3 networker:(id)arg4 useProtobuf:(_Bool)arg5 logger:(id)arg6 filterInvalidSnaps:(_Bool)arg7 queue:(id)arg8 failureHandler:(CDUnknownBlockType)arg9 successHandler:(CDUnknownBlockType)arg10;
@property(readonly, copy, nonatomic) NSString *requestID;
- (_Bool)requiresSyncStatusUpdate;
- (id)serialize;
@property(readonly, nonatomic) unsigned long long type;

@end

