//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@interface SCCollectionViewSectionIndexMatch : NSObject <NSCopying>
{
    unsigned long long _subtype;
    long long _itemIndex_itemIndex;
}

+ (id)itemIndexWithItemIndex:(long long)arg1;
+ (id)noItem;
+ (id)notFound;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)hash;
- (id)internalInit;
- (_Bool)isEqual:(id)arg1;
- (void)matchItemIndex:(CDUnknownBlockType)arg1 noItem:(CDUnknownBlockType)arg2 notFound:(CDUnknownBlockType)arg3;

@end

