//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCCognacDataStorageUpdateResult-Protocol.h"

@class NSArray, NSString;

@interface SCCognacDataStorageUpdateResultAppInstanceArray : NSObject <SCCognacDataStorageUpdateResult>
{
    NSArray *_appInstanceDataModels;
    NSString *_conversationId;
    unsigned long long _triggerType;
}

+ (id)buildWithAppInstanceDataModels:(id)arg1 conversationId:(id)arg2 triggerType:(unsigned long long)arg3;
- (void).cxx_destruct;
- (id)_initWithAppInstanceDataModels:(id)arg1 conversationId:(id)arg2 triggerType:(unsigned long long)arg3;
@property(readonly, copy, nonatomic) NSArray *appInstanceDataModels; // @synthesize appInstanceDataModels=_appInstanceDataModels;
@property(readonly, copy, nonatomic) NSString *conversationId; // @synthesize conversationId=_conversationId;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) unsigned long long triggerType; // @synthesize triggerType=_triggerType;
- (unsigned long long)type;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

