//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCDocObject.h"

#import "NSCopying-Protocol.h"

@class NSArray, NSString;

@interface SCCognacAppListData : SCDocObject <NSCopying>
{
    NSString *_appListId;
    double _timestamp;
    NSArray *_apps;
}

+ (id)immutableObjectParse:(const void *)arg1 bufferSize:(unsigned long long)arg2;
+ (struct SCDocObjectClassFunctionPointer)objectClassFunctionPointer;
+ (const char *)table;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *appListId; // @synthesize appListId=_appListId;
@property(readonly, copy, nonatomic) NSArray *apps; // @synthesize apps=_apps;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)hash;
- (id)initWithAppListId:(id)arg1 timestamp:(double)arg2 apps:(id)arg3;
- (_Bool)isEqual:(id)arg1;
@property(readonly, nonatomic) double timestamp; // @synthesize timestamp=_timestamp;

@end

