//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "SCAddFriendsInterstitialView-Protocol.h"
#import "SCTraceEnabled-Protocol.h"

@class NSString, SCPrePromptPermissionCustomDialogView, TTTAttributedLabel, UIImageView;

@interface SCContactSyncPrePromptView : UIView <SCTraceEnabled, SCAddFriendsInterstitialView>
{
    SCPrePromptPermissionCustomDialogView *_dialogView;
    UIImageView *_backgroundImageView;
    TTTAttributedLabel *_privacyPolicyLabel;
}

- (void).cxx_destruct;
- (void)_initBackgroundImageView;
- (void)_initDialogViewWithAllowButtonHandler:(CDUnknownBlockType)arg1 denyButtonHandler:(CDUnknownBlockType)arg2;
- (void)_initPrivacyPolicyLabel;
- (void)didMoveToSuperview;
- (_Bool)hasAllowButton;
- (_Bool)hasDenyButton;
- (id)initWithFrame:(struct CGRect)arg1 allowButtonHandler:(CDUnknownBlockType)arg2 denyButtonHandler:(CDUnknownBlockType)arg3;
- (void)layoutSubviews;
@property(retain, nonatomic) TTTAttributedLabel *privacyPolicyLabel; // @synthesize privacyPolicyLabel=_privacyPolicyLabel;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

