//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FriendStories, NSString, SCR2StoryCard, SCStoryManifest, UIView, UIViewController;
@protocol SCContextV2Logger;

@protocol SCContextV2StoryHandler <NSObject>
- (void)playFriendStories:(FriendStories *)arg1 baseView:(UIView *)arg2 baseViewController:(UIViewController *)arg3 logger:(id <SCContextV2Logger>)arg4;
- (void)playStoriesForUsername:(NSString *)arg1 baseView:(UIView *)arg2 baseViewController:(UIViewController *)arg3 logger:(id <SCContextV2Logger>)arg4;
- (void)playStoryWithManifest:(SCStoryManifest *)arg1 baseView:(UIView *)arg2 baseViewController:(UIViewController *)arg3 logger:(id <SCContextV2Logger>)arg4;
- (void)playStoryWithStoryCard:(SCR2StoryCard *)arg1 baseView:(UIView *)arg2 baseViewController:(UIViewController *)arg3 logger:(id <SCContextV2Logger>)arg4;
@end

