//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCContextV2PresenterDelegate-Protocol.h"
#import "SCOperaContextMenuOverlayProvider-Protocol.h"

@class NSMapTable, NSString, SCUserSession;
@protocol NavigationDelegate, SCContextDelegate;

@interface SCContextV2OverlayProvider : NSObject <SCContextV2PresenterDelegate, SCOperaContextMenuOverlayProvider>
{
    SCUserSession *_userSession;
    NSMapTable *_presentersForLayerVCs;
    id <SCContextDelegate> _contextDelegate;
    id <NavigationDelegate> _navigationDelegate;
}

- (void).cxx_destruct;
- (id)_createContextSessionWithLayerViewController:(id)arg1;
- (id)_createPresenterWithLayerViewController:(id)arg1;
- (id)_layerViewControllerForPresenter:(id)arg1;
@property(nonatomic) __weak id <SCContextDelegate> contextDelegate; // @synthesize contextDelegate=_contextDelegate;
- (void)contextLayerWillFullyAppear:(id)arg1;
- (id)contextMenuControllerWithLayerViewController:(id)arg1;
- (void)contextV2Presenter:(id)arg1 wantsCTAToBeHidden:(_Bool)arg2;
- (void)contextV2PresenterCardsViewDidAppear:(id)arg1;
- (void)contextV2PresenterDidDismissSwipeUpContent:(id)arg1;
- (void)contextV2PresenterDidFinishPresentingAccessoryView:(id)arg1;
- (void)contextV2PresenterDidPresentAccessoryView:(id)arg1;
- (void)contextV2PresenterDidPresentSwipeUpContent:(id)arg1;
- (id)currentSnapViewMetricsWithLayerViewController:(id)arg1;
- (id)customCtaViewWithLayerViewController:(id)arg1;
- (id)initWithUserSession:(id)arg1 contextDelegate:(id)arg2 navigationDelegate:(id)arg3;
@property(nonatomic) __weak id <NavigationDelegate> navigationDelegate; // @synthesize navigationDelegate=_navigationDelegate;
- (void)prepareContextMenuWithProperties:(id)arg1;
- (void)prepareToPresentContextMenu:(id)arg1;
- (void)setupWithOperaViewController:(id)arg1;
- (_Bool)shouldAnimateTransition:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

