//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSArray, NSString, SCCommerceContactDetailsDataModel, SCCommerceCurrency, SCCommercePaymentObfuscatedCardDataModel, SCCommerceShippingAddressDataModel;

@interface SCCommerceCheckoutDataModel : NSObject <NSCopying>
{
    NSString *_identifier;
    NSString *_storeId;
    SCCommerceCurrency *_total;
    NSArray *_lineItems;
    NSArray *_tax;
    SCCommerceContactDetailsDataModel *_contactDetails;
    SCCommerceShippingAddressDataModel *_shippingAddress;
    SCCommercePaymentObfuscatedCardDataModel *_paymentDetails;
    NSString *_discountCode;
    NSString *_selectedShippingId;
    NSArray *_selectableShippingOptions;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) SCCommerceContactDetailsDataModel *contactDetails; // @synthesize contactDetails=_contactDetails;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, copy, nonatomic) NSString *discountCode; // @synthesize discountCode=_discountCode;
- (unsigned long long)hash;
@property(readonly, copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (id)initWithIdentifier:(id)arg1 storeId:(id)arg2 total:(id)arg3 lineItems:(id)arg4 tax:(id)arg5 contactDetails:(id)arg6 shippingAddress:(id)arg7 paymentDetails:(id)arg8 discountCode:(id)arg9 selectedShippingId:(id)arg10 selectableShippingOptions:(id)arg11;
- (_Bool)isEqual:(id)arg1;
@property(readonly, copy, nonatomic) NSArray *lineItems; // @synthesize lineItems=_lineItems;
@property(readonly, copy, nonatomic) SCCommercePaymentObfuscatedCardDataModel *paymentDetails; // @synthesize paymentDetails=_paymentDetails;
@property(readonly, copy, nonatomic) NSArray *selectableShippingOptions; // @synthesize selectableShippingOptions=_selectableShippingOptions;
@property(readonly, copy, nonatomic) NSString *selectedShippingId; // @synthesize selectedShippingId=_selectedShippingId;
@property(readonly, copy, nonatomic) SCCommerceShippingAddressDataModel *shippingAddress; // @synthesize shippingAddress=_shippingAddress;
@property(readonly, copy, nonatomic) NSString *storeId; // @synthesize storeId=_storeId;
@property(readonly, copy, nonatomic) NSArray *tax; // @synthesize tax=_tax;
@property(readonly, copy, nonatomic) SCCommerceCurrency *total; // @synthesize total=_total;

@end

