//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCExperimentContext.h"

@interface SCContentManagerExperimentContext : SCExperimentContext
{
    _Bool _useListOfQueues;
    _Bool _unzipOnDownload;
    _Bool _saveAllContentStatesToDB;
    unsigned long long _numberOfQueuesPerMediaContextType;
}

- (id)experimentName;
@property(readonly, nonatomic) unsigned long long numberOfQueuesPerMediaContextType; // @synthesize numberOfQueuesPerMediaContextType=_numberOfQueuesPerMediaContextType;
@property(readonly, nonatomic) _Bool saveAllContentStatesToDB; // @synthesize saveAllContentStatesToDB=_saveAllContentStatesToDB;
- (void)setupParameters;
@property(readonly, nonatomic) _Bool unzipOnDownload; // @synthesize unzipOnDownload=_unzipOnDownload;
@property(readonly, nonatomic) _Bool useListOfQueues; // @synthesize useListOfQueues=_useListOfQueues;

@end

