//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableSet, SCAutoStickerLogger, SCFaceDetector, SCPreferences, SCQueuePerformer, SCUserSession;
@protocol OS_dispatch_group;

@interface SCCustomStickerFaceCutAnalyzer : NSObject
{
    SCUserSession *_userSession;
    SCPreferences *_userPreferences;
    SCAutoStickerLogger *_logger;
    SCFaceDetector *_faceDetector;
    SCQueuePerformer *_performer;
    struct unique_ptr<SnapCutExt, std::__1::default_delete<SnapCutExt>> _snapCut;
    NSMutableSet *_dedupMemoriesIds;
    NSMutableSet *_dedupCameraRollIds;
    NSObject<OS_dispatch_group> *_addStickerCompleteGroup;
    _Bool _isProblematicDevice;
    _Bool _isGenerating;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (long long)_analyze:(id)arg1 originId:(id)arg2 creationTime:(id)arg3;
- (void)_filterOutSnapchatAlbum;
- (void)_generateFaceCustomStickerWithCompletion:(CDUnknownBlockType)arg1;
- (void)_getFaceCutStickers:(CDUnknownBlockType)arg1;
- (id)_getFetchResultsFromCameraRoll;
- (id)_getSnapsFromMemories;
- (void)_loadSnapCutModelCompletion:(CDUnknownBlockType)arg1;
- (void)_setSnapCutModelIfNecessary;
- (_Bool)_shouldAutoUpdate;
- (void)_stickerFromMemoriesWithCompletion:(id)arg1 currentIdx:(unsigned long long)arg2 totalScanCount:(long long)arg3 totalSkipCount:(long long)arg4 totalStickerCount:(long long)arg5 completionHandler:(CDUnknownBlockType)arg6;
- (void)_stickersFromCameraAndMemoriesWithCompletion:(long long)arg1 scanCount:(long long)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (id)debugString;
- (void)generateFaceCustomStickerWithCompletion:(CDUnknownBlockType)arg1;
- (id)initAnalyzerWithUserSession:(id)arg1;
- (_Bool)isFirstTime;
@property(nonatomic) _Bool isGenerating; // @synthesize isGenerating=_isGenerating;
- (void)updateAutoSticker;

@end

