//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SCDeviceName : NSObject
{
}

+ (id)chipName;
+ (_Bool)currentDeviceMeetsMinimumDeviceRequirement:(id)arg1;
+ (float)defaultFieldOfView;
+ (unsigned long long)deviceClass;
+ (id)deviceClassAsString;
+ (id)devicePlatform;
+ (long long)deviceScore;
+ (id)deviceVersionStringForDeviceName:(id)arg1;
+ (_Bool)is3xRendering;
+ (_Bool)isA12Chip;
+ (_Bool)isA12XChip;
+ (_Bool)isA8Chip;
+ (_Bool)isIpad;
+ (_Bool)isIpad:(id)arg1;
+ (_Bool)isIphone;
+ (_Bool)isIphone:(id)arg1;
+ (_Bool)isIpod;
+ (_Bool)isIpod:(id)arg1;
+ (_Bool)isSimilarToIphone5SorNewer;
+ (_Bool)isSimilarToIphone5orNewer;
+ (_Bool)isSimilarToIphone6SorNewer;
+ (_Bool)isSimilarToIphone6orNewer;
+ (_Bool)isSimilarToIphone7orNewer;
+ (_Bool)isSimilarToIphone8orNewer;
+ (_Bool)isSimilarToIphoneXSorNewer;
+ (_Bool)isSimilarToIphoneXorNewer;
+ (_Bool)isSimulator;
+ (_Bool)isSimulator:(id)arg1;
+ (unsigned long long)lsaDeviceClass;
+ (id)osVersion;
+ (id)platformString;
+ (double)timeIntervalSinceSystemBoot;

@end

