//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@interface SCDiscoverFeedWhiteSpaceABConfiguration : NSObject <NSCopying>
{
    _Bool _enableCarouselThreeAcross;
    _Bool _enableCarouselFourAcross;
    _Bool _enableCarouselLegacyWithProfile;
    _Bool _disableHeadlineCarousel;
    _Bool _disableTimestampCarousel;
    _Bool _disableLegacyProfileCarousel;
    _Bool _enableForyouTwoAcross;
    _Bool _enableForyouLegacyWithProfile;
    _Bool _disableHeadlineForyou;
    _Bool _disableTimestampForyou;
    _Bool _disableLegacyProfileForyou;
}

- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, nonatomic) _Bool disableHeadlineCarousel; // @synthesize disableHeadlineCarousel=_disableHeadlineCarousel;
@property(readonly, nonatomic) _Bool disableHeadlineForyou; // @synthesize disableHeadlineForyou=_disableHeadlineForyou;
@property(readonly, nonatomic) _Bool disableLegacyProfileCarousel; // @synthesize disableLegacyProfileCarousel=_disableLegacyProfileCarousel;
@property(readonly, nonatomic) _Bool disableLegacyProfileForyou; // @synthesize disableLegacyProfileForyou=_disableLegacyProfileForyou;
@property(readonly, nonatomic) _Bool disableTimestampCarousel; // @synthesize disableTimestampCarousel=_disableTimestampCarousel;
@property(readonly, nonatomic) _Bool disableTimestampForyou; // @synthesize disableTimestampForyou=_disableTimestampForyou;
@property(readonly, nonatomic) _Bool enableCarouselFourAcross; // @synthesize enableCarouselFourAcross=_enableCarouselFourAcross;
@property(readonly, nonatomic) _Bool enableCarouselLegacyWithProfile; // @synthesize enableCarouselLegacyWithProfile=_enableCarouselLegacyWithProfile;
@property(readonly, nonatomic) _Bool enableCarouselThreeAcross; // @synthesize enableCarouselThreeAcross=_enableCarouselThreeAcross;
@property(readonly, nonatomic) _Bool enableForyouLegacyWithProfile; // @synthesize enableForyouLegacyWithProfile=_enableForyouLegacyWithProfile;
@property(readonly, nonatomic) _Bool enableForyouTwoAcross; // @synthesize enableForyouTwoAcross=_enableForyouTwoAcross;
- (unsigned long long)hash;
- (id)initWithEnableCarouselThreeAcross:(_Bool)arg1 enableCarouselFourAcross:(_Bool)arg2 enableCarouselLegacyWithProfile:(_Bool)arg3 disableHeadlineCarousel:(_Bool)arg4 disableTimestampCarousel:(_Bool)arg5 disableLegacyProfileCarousel:(_Bool)arg6 enableForyouTwoAcross:(_Bool)arg7 enableForyouLegacyWithProfile:(_Bool)arg8 disableHeadlineForyou:(_Bool)arg9 disableTimestampForyou:(_Bool)arg10 disableLegacyProfileForyou:(_Bool)arg11;
- (_Bool)isEqual:(id)arg1;

@end

