//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCDiscoverFeedCollectionViewSectionCreating-Protocol.h"
#import "SCDiscoverFeedRemoteSectionParsing-Protocol.h"

@class NSString, SCLazy;
@protocol SCImageDownloading;

@interface SCDiscoverFeedPivotSectionCreator : NSObject <SCDiscoverFeedRemoteSectionParsing, SCDiscoverFeedCollectionViewSectionCreating>
{
    id <SCImageDownloading> _imageDownloader;
    SCLazy *_docObjectContext;
}

- (void).cxx_destruct;
- (id)initWithImageDownloader:(id)arg1 docObjectContext:(id)arg2;
- (id)parseSectionMetadataWithResponse:(id)arg1;
- (id)remoteSectionDescriptorWithSectionMetadata:(id)arg1;
- (id)sectionDataProviderForDescriptor:(id)arg1;
- (id)sectionTitleForDescriptor:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

