//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSString;

@interface SCDiscoverFeedPublisherSnapTileBadge : NSObject <NSCopying>
{
    NSString *_title;
    unsigned long long _backgroundColorArgb;
    unsigned long long _textColorArgb;
    long long _size;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) unsigned long long backgroundColorArgb; // @synthesize backgroundColorArgb=_backgroundColorArgb;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)hash;
- (id)initWithTitle:(id)arg1 backgroundColorArgb:(unsigned long long)arg2 textColorArgb:(unsigned long long)arg3 size:(long long)arg4;
- (_Bool)isEqual:(id)arg1;
@property(readonly, nonatomic) long long size; // @synthesize size=_size;
@property(readonly, nonatomic) unsigned long long textColorArgb; // @synthesize textColorArgb=_textColorArgb;
@property(readonly, copy, nonatomic) NSString *title; // @synthesize title=_title;
- (id)xLogObjectInfo;

@end

