//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSString, UIColor;

@interface SCDiscoverFeedDebugViewModel : NSObject <NSCopying>
{
    NSString *_debugButtonImageName;
    UIColor *_debugButtonColor;
    UIColor *_debugVisualElementColor;
}

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, copy, nonatomic) UIColor *debugButtonColor; // @synthesize debugButtonColor=_debugButtonColor;
@property(readonly, copy, nonatomic) NSString *debugButtonImageName; // @synthesize debugButtonImageName=_debugButtonImageName;
@property(readonly, copy, nonatomic) UIColor *debugVisualElementColor; // @synthesize debugVisualElementColor=_debugVisualElementColor;
- (unsigned long long)hash;
- (id)initWithDebugButtonImageName:(id)arg1 debugButtonColor:(id)arg2 debugVisualElementColor:(id)arg3;
- (_Bool)isEqual:(id)arg1;

@end

