//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSAttributedString, NSString;

@interface SCDiscoverFeedWhiteSpaceDynamicPostViewLayerViewModel : NSObject <NSCopying>
{
    unsigned long long _subtype;
    NSString *_singleIconViewModel_iconResourceName;
    NSAttributedString *_singleIconViewModel_iconSubtitle;
    NSString *_twoIconsViewModel_upperIconResouceName;
    NSAttributedString *_twoIconsViewModel_upperIconSubtitle;
    NSString *_twoIconsViewModel_lowerIconResourceName;
    NSAttributedString *_twoIconsViewModel_lowerIconSubtitle;
}

+ (id)singleIconViewModelWithIconResourceName:(id)arg1 iconSubtitle:(id)arg2;
+ (id)twoIconsViewModelWithUpperIconResouceName:(id)arg1 upperIconSubtitle:(id)arg2 lowerIconResourceName:(id)arg3 lowerIconSubtitle:(id)arg4;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)hash;
- (id)internalInit;
- (_Bool)isEqual:(id)arg1;
- (void)matchSingleIconViewModel:(CDUnknownBlockType)arg1 twoIconsViewModel:(CDUnknownBlockType)arg2;

@end

