//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCFeature.h"

#import "SCCameraToolbarItemProvider-Protocol.h"
#import "SCFeatureDepthCaptureMode-Protocol.h"
#import "SCManagedCapturerListener-Protocol.h"

@class NSString, SCCameraToolbarItem, SCDepthCaptureLiveCameraCropModule, SCDisposableObserverLifecycle, UIView;
@protocol SCCameraViewControllerLensDelegate, SCCapturer, SCFeatureCameraToolbar, SCFeatureContainerView;

@interface SCFeatureDepthCaptureModeImpl : SCFeature <SCManagedCapturerListener, SCFeatureDepthCaptureMode, SCCameraToolbarItemProvider>
{
    id <SCCapturer> _capturer;
    UIView<SCFeatureContainerView> *_containerView;
    id <SCFeatureCameraToolbar> _cameraToolbar;
    SCDisposableObserverLifecycle *_appLifecycle;
    SCDisposableObserverLifecycle *_vcLifecycle;
    SCCameraToolbarItem *_toolbarItem;
    unsigned long long _lastDevicePosition;
    SCDepthCaptureLiveCameraCropModule *_liveCameraCropModule;
    _Bool _enabled;
    id <SCCameraViewControllerLensDelegate> _lensDelegate;
}

- (void).cxx_destruct;
- (id)_createToolbarItem;
- (_Bool)_isDepthCaptureDevicePosition:(unsigned long long)arg1;
- (_Bool)_onFrontCamera:(unsigned long long)arg1;
- (void)_updateToolbarItemVisibility;
- (void)activate;
- (void)configureWithCameraToolbar:(id)arg1;
- (void)configureWithView:(id)arg1;
- (void)dealloc;
@property(readonly, nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
- (id)initWithCapturer:(id)arg1 applicationLifecycleEvents:(id)arg2;
@property(nonatomic) __weak id <SCCameraViewControllerLensDelegate> lensDelegate; // @synthesize lensDelegate=_lensDelegate;
- (void)managedCapturer:(id)arg1 didChangeCaptureDevicePosition:(id)arg2;
- (void)managedCapturer:(id)arg1 didChangeDepthCaptureModeActive:(id)arg2;
- (void)managedCapturer:(id)arg1 didChangeLensesActive:(id)arg2;
- (void)setEnabled:(_Bool)arg1 force:(_Bool)arg2;
- (void)startIfInactive;
- (void)stopIfActive;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

