//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class UIGestureRecognizer, UIView;
@protocol SCCameraTimer;

@protocol SCFeatureContainerView
@property(readonly, nonatomic) UIView<SCCameraTimer> *cameraTimer;
- (struct CGRect)cameraTimerFrameInView:(UIView *)arg1;
- (UIView *)hidableViewContainer;
- (struct CGRect)initialCameraTimerFrame;
- (void)insertSubview:(UIView *)arg1 atIndexInFrontOfLiveDisplay:(long long)arg2;
- (void)interruptButtonTouchesBeforeRecording;
- (_Bool)isTapGestureRecognizer:(UIGestureRecognizer *)arg1;
- (UIView *)liveDisplayContainerView;
- (void)resetCameraHelpTooltipVisibility;
- (void)restoreLongPressOnCameraTimerGestureRecognizer;
- (void)setPanGestureRecognizerEnabled:(_Bool)arg1;
- (void)stopCameraTimerAnimationAndSaveState:(_Bool)arg1;
- (double)yPositionForNavigationItemControlsInView:(UIView *)arg1;
@end

