//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, SCFeature;

@interface SCFeatureSetReference : NSObject
{
    long long _arrayIndex;
    SCFeature *_feature;
    NSString *_key;
    long long _responderChainPriority;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) long long arrayIndex; // @synthesize arrayIndex=_arrayIndex;
- (long long)compareToReference:(id)arg1;
@property(readonly, nonatomic) SCFeature *feature; // @synthesize feature=_feature;
- (id)initWithFeature:(id)arg1 withArrayIndex:(long long)arg2 responderChainPriority:(long long)arg3 key:(id)arg4;
@property(readonly, nonatomic) NSString *key; // @synthesize key=_key;
@property(readonly, nonatomic) long long responderChainPriority; // @synthesize responderChainPriority=_responderChainPriority;
- (void)updateArrayIndex:(long long)arg1;

@end

