//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class SCEllipticCurveCrypto, SCFideliusUserIdentity, SCQueuePerformer;

@interface SCFideliusIdentityArchiveManager : NSObject
{
    SCQueuePerformer *_performer;
    SCFideliusUserIdentity *_archiveIdentity;
    SCEllipticCurveCrypto *_archiveBeta;
    _Bool _isArchiveUnavailable;
}

+ (_Bool)archiveFileExists;
+ (id)shared;
+ (id)sharedFakePerformer;
- (void).cxx_destruct;
- (void)_clearInMemoryForTesting;
- (void)_setArchiveIdentity;
- (id)archiveBeta;
- (id)archiveIdentity;
- (void)clear;
- (id)init;
- (id)initWithPerformer:(id)arg1;
- (id)iwek;
- (_Bool)save:(id)arg1;

@end

