//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCOperaEventListener-Protocol.h"

@class NSString, SCExperimentManager, SCFilterAttachmentOperaViewingSession, SCOperaViewController, SCSafeBrowsingAPI, SCUnlockableGeoFilterTracker, SOJUUnlockablesAttachment, UIViewController;
@protocol SCFilterAttachmentOperaControllerProtocol;

@interface SCFilterAttachmentOperaController : NSObject <SCOperaEventListener>
{
    SOJUUnlockablesAttachment *_activeAttachment;
    NSString *_filterId;
    SCExperimentManager *_experimentManager;
    UIViewController *_fromViewController;
    SCOperaViewController *_operaViewController;
    SCFilterAttachmentOperaViewingSession *_operaViewingSession;
    SCUnlockableGeoFilterTracker *_geofilterTracker;
    SCSafeBrowsingAPI *_safeBrowsingAPI;
    id <SCFilterAttachmentOperaControllerProtocol> _delegate;
}

- (void).cxx_destruct;
- (id)_operaViewModelForAttachment:(id)arg1;
- (id)_registeredEventsForOperaSession;
- (id)_viewModelWithAppId:(id)arg1;
- (id)_viewModelWithVideoId:(id)arg1;
- (id)_viewModelWithWebUrl:(id)arg1 shouldAutoFill:(_Bool)arg2;
- (id)configurationWithOperaViewModel:(id)arg1;
@property(nonatomic) __weak id <SCFilterAttachmentOperaControllerProtocol> delegate; // @synthesize delegate=_delegate;
- (id)initWithExperimentManager:(id)arg1 fromViewController:(id)arg2 geofilterTracker:(id)arg3 safeBrowsingAPI:(id)arg4;
- (void)operaViewDidSendEvent:(id)arg1 context:(id)arg2 params:(id)arg3;
- (void)presentAttachment:(id)arg1 forFilterId:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

