//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSSet, SCFriendsFeedFetchContext;

@interface SCFriendsFeedMessagingUpdateDataRequest : NSObject <NSCopying>
{
    NSSet *_updatedFeedIds;
    SCFriendsFeedFetchContext *_fetchContext;
}

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, copy, nonatomic) SCFriendsFeedFetchContext *fetchContext; // @synthesize fetchContext=_fetchContext;
- (unsigned long long)hash;
- (id)initWithUpdatedFeedIds:(id)arg1 fetchContext:(id)arg2;
- (_Bool)isEqual:(id)arg1;
@property(readonly, copy, nonatomic) NSSet *updatedFeedIds; // @synthesize updatedFeedIds=_updatedFeedIds;

@end

