//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol SCGallerySnap;

@interface SCGalleryIndexPending : NSObject
{
    id <SCGallerySnap> _snap;
    id <SCGallerySnap> _fromSnap;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) id <SCGallerySnap> fromSnap; // @synthesize fromSnap=_fromSnap;
- (unsigned long long)hash;
- (id)initWithSnap:(id)arg1 fromSnap:(id)arg2;
- (_Bool)isEqual:(id)arg1;
- (_Bool)isEqualToPendingSnap:(id)arg1;
@property(readonly, nonatomic) id <SCGallerySnap> snap; // @synthesize snap=_snap;

@end

