//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface SCGalleryCameraRollTabHeaderView : UIView
{
    double _coveredHeight;
}

+ (id)attributedText;
+ (struct CGSize)preferredSize;
- (void)_updateAlpha;
- (void)_updateMask;
@property(nonatomic) double coveredHeight; // @synthesize coveredHeight=_coveredHeight;
- (id)initWithFrame:(struct CGRect)arg1;
- (struct CGSize)intrinsicContentSize;
- (void)layoutSubviews;

@end

