//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCGalleryTabBarDelegate-Protocol.h"

@class NSArray, NSString, SCGalleryTabBar, SCUserSession, UIView;
@protocol SCGalleryTabBarsControllerDelegate;

@interface SCGalleryTabBarsController : NSObject <SCGalleryTabBarDelegate>
{
    SCUserSession *_userSession;
    NSArray *_tabControllers;
    SCGalleryTabBar *_primaryTabBar;
    id <SCGalleryTabBarsControllerDelegate> _delegate;
    UIView *_containerView;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) double containerHeight;
@property(readonly, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(nonatomic) __weak id <SCGalleryTabBarsControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)galleryTabBar:(id)arg1 didSelectItemAtIndex:(long long)arg2;
- (id)initWithUserSession:(id)arg1;
@property(readonly, nonatomic) double tabBarsHeight;
- (void)updateTabBarCornerRadius:(double)arg1;
- (void)updateWithHighlightedIndex:(double)arg1;
- (void)updateWithTabControllers:(id)arg1 highlightedTabController:(id)arg2;
@property(readonly, nonatomic) double visibleTabBarsHeight;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

