//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "PHPhotoLibraryChangeObserver-Protocol.h"

@class NSArray, NSString, SCGalleryPhotoLibraryFetcherListenerAnnouncer, SCQueuePerformer;

@interface SCGalleryPhotoLibraryFetcher : NSObject <PHPhotoLibraryChangeObserver>
{
    SCQueuePerformer *_performer;
    unsigned long long _resultType;
    _Bool _observesChange;
    CDUnknownBlockType _resultHandler;
    _Bool _didFireFetch;
    _Bool _didSetupFetch;
    id _photoPermissionDeterminedNotificationObserver;
    NSArray *_fetchResults;
    NSArray *_photoAssets;
    SCGalleryPhotoLibraryFetcherListenerAnnouncer *_announcer;
    unsigned long long _fetchRetryAttempts;
    _Bool _returnFetchResultWithoutIterating;
    _Bool _isInBackground;
    _Bool _didChangeInBackground;
}

- (void).cxx_destruct;
- (void)_didEnterBackground;
- (void)_fetchPhotoAssets;
- (_Bool)_needsRefetchPhotoAssetsForChange:(id)arg1;
- (void)_notifyWithFetchResult:(id)arg1;
- (void)_notifyWithPhotoAssets:(id)arg1;
- (void)_setupFetch;
- (void)_willEnterForeground;
- (void)addListener:(id)arg1;
- (void)dealloc;
@property _Bool didChangeInBackground; // @synthesize didChangeInBackground=_didChangeInBackground;
- (void)fetchWithResultType:(unsigned long long)arg1 observesChange:(_Bool)arg2 resultHandler:(CDUnknownBlockType)arg3;
- (id)init;
@property _Bool isInBackground; // @synthesize isInBackground=_isInBackground;
- (void)photoLibraryDidChange:(id)arg1;
- (void)removeListener:(id)arg1;
@property(nonatomic) _Bool returnFetchResultWithoutIterating; // @synthesize returnFetchResultWithoutIterating=_returnFetchResultWithoutIterating;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

