//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDate, SCQueuePerformer, SOJUSnapCreatorAttribution;

@protocol SCGalleryItemSending <NSObject>
- (NSDate *)captureTime;
- (double)duration;
- (_Bool)isCameraRollItem;
- (_Bool)isInfiniteDuration;
- (void)mediaData:(void (^)(NSData *, NSData *))arg1 performer:(SCQueuePerformer *)arg2;
- (long long)mediaType;
- (long long)orientation;
- (void)remoteCheckSmartShareEligibility:(void (^)(_Bool, SCGallerySmartShareSnapPackage *))arg1 performer:(SCQueuePerformer *)arg2;
- (SOJUSnapCreatorAttribution *)repostAttribution;

@optional
- (void)prepare:(SCQueuePerformer *)arg1;
@end

