//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCTraceEnabled-Protocol.h"
#import "SCUnifiedProfileSectionCreating-Protocol.h"

@class NSString, SCCharmsBlizzardLogger, SCCharmsDataCoordinator, SCCharmsViewingDataCoordinator, SCEventListenerAnnouncer, SCGroupUnifiedProfileActionHandler, SCGroupUnifiedProfileDataSource, SCGroupUnifiedProfilePromptSectionDataCoordinator, SCGroupUnifiedProfileStoriesDataSource, SCLazy, SCProfileChatAttachmentDataStore, SCProfileChatMediaDataSource, SCUnifiedProfileViewLayoutConfiguration, SCUserSession, UIViewController;
@protocol NavigationDelegate, SCImageDownloading, SCLegacyItemDownloading, SCUnifiedProfileTabScrollHandling;

@interface SCGroupUnifiedProfileSectionCreator : NSObject <SCTraceEnabled, SCUnifiedProfileSectionCreating>
{
    SCGroupUnifiedProfileDataSource *_dataSource;
    SCGroupUnifiedProfileStoriesDataSource *_storiesDataSource;
    id <SCImageDownloading> _imageDownloader;
    id <SCLegacyItemDownloading> _labelInfoFetcher;
    SCGroupUnifiedProfileActionHandler *_actionHandler;
    UIViewController *_presentingViewController;
    id <NavigationDelegate> _navigationDelegate;
    SCUserSession *_userSession;
    SCProfileChatMediaDataSource *_profileChatMediaDataSource;
    SCProfileChatAttachmentDataStore *_chatAttachmentDataStore;
    SCCharmsDataCoordinator *_charmsDataCoordinator;
    SCCharmsViewingDataCoordinator *_charmsViewingDataCoordinator;
    SCGroupUnifiedProfilePromptSectionDataCoordinator *_promptSectionDataCoordinator;
    SCLazy *_pinnedConversationsDataCoordinator;
    SCCharmsBlizzardLogger *_charmsBlizzardLogger;
    SCUnifiedProfileViewLayoutConfiguration *_layoutConfiguration;
    SCEventListenerAnnouncer *_lifecycleAnnouncer;
    id <SCUnifiedProfileTabScrollHandling> _tabSectionScrollHandler;
}

- (void).cxx_destruct;
- (id)_charmsSection;
- (id)_chatAttachmentSection;
- (id)_eventMetadataSection;
- (id)_identitySection;
- (id)_mapSection;
- (id)_membersSection;
- (id)_privacyAffirmationSection;
- (id)_promptSection;
- (id)_savedInChatSection;
- (id)_storiesSection;
- (id)initWithDataSource:(id)arg1 groupStoriesDataSource:(id)arg2 imageDownloader:(id)arg3 labelInfoFetcher:(id)arg4 actionHandler:(id)arg5 presentingViewController:(id)arg6 navigationDelegate:(id)arg7 profileChatMediaDataSource:(id)arg8 userSession:(id)arg9 chatAttachmentDataStore:(id)arg10 charmsDataCoordinator:(id)arg11 charmsViewingDataCoordinator:(id)arg12 promptSectionDataCoordinator:(id)arg13 pinnedConversationsDataCoordinator:(id)arg14 charmsBlizzardLogger:(id)arg15;
@property(nonatomic) __weak SCUnifiedProfileViewLayoutConfiguration *layoutConfiguration; // @synthesize layoutConfiguration=_layoutConfiguration;
@property(nonatomic) __weak SCEventListenerAnnouncer *lifecycleAnnouncer; // @synthesize lifecycleAnnouncer=_lifecycleAnnouncer;
- (id)sectionForDescriptor:(id)arg1;
@property(nonatomic) __weak id <SCUnifiedProfileTabScrollHandling> tabSectionScrollHandler; // @synthesize tabSectionScrollHandler=_tabSectionScrollHandler;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

