//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "SCGroupInviteViewDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class NSString, SCEventStickerView, SCGroupInvite, UILabel, UIScrollView;
@protocol SCGroupInviteSingleStickerViewControllerDelegate, SCGroupInviteVenueSearchProvider;

@interface SCGroupInviteSingleStickerViewController : UIViewController <UIScrollViewDelegate, SCGroupInviteViewDelegate>
{
    SCGroupInvite *_invite;
    _Bool _editable;
    id <SCGroupInviteVenueSearchProvider> _venueSearchProvider;
    UIScrollView *_stickerScroller;
    UILabel *_hintLabel;
    SCEventStickerView *_stickerView;
    double _topInsets;
    double _bottomInsets;
    id <SCGroupInviteSingleStickerViewControllerDelegate> _delegate;
}

+ (double)preferredWidth;
- (void).cxx_destruct;
- (void)_expandFromHybridModeToFullMode;
- (void)beginEnteringLocation;
- (void)beginEnteringTime;
@property(nonatomic) __weak id <SCGroupInviteSingleStickerViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)focusTitleField;
- (void)groupStickerViewDidEditSticker:(id)arg1;
- (id)initWithInvite:(id)arg1 venueSearchProvider:(id)arg2 editingEnabled:(_Bool)arg3;
- (id)invite;
- (void)resignFocus;
- (void)scrollViewDidScroll:(id)arg1;
- (_Bool)shouldShowTimeAndLocationButtons;
- (void)updateTopInsets:(double)arg1 bottomInsets:(double)arg2;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

