//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UILabel.h>

@class SCGroupStoryPublication;

@interface SCGroupStoryDescriptionLabel : UILabel
{
    _Bool _geoDescriptionDisplayPrivacy;
    SCGroupStoryPublication *_groupStory;
}

- (void).cxx_destruct;
- (id)_customOrPrivateStoryDescription;
- (void)_dispatchGeoStoryToggle;
- (id)_groupStoryDescription;
- (void)_toggleGeoStoryDescription;
@property(retain, nonatomic) SCGroupStoryPublication *groupStory; // @synthesize groupStory=_groupStory;
- (void)setFrame:(struct CGRect)arg1;

@end

