//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCMiniProfileCollectionViewCell.h"

#import "SCAvatarViewDelegate-Protocol.h"

@class FriendStories, SCAvatarView, SCPieSliceView, SCUserSession, UILabel, UITapGestureRecognizer, UIView;
@protocol SCGroupMiniProfileGroupStoryCellDelegate;

@interface SCGroupMiniProfileGroupStoryViewCell : SCMiniProfileCollectionViewCell <SCAvatarViewDelegate>
{
    UILabel *_nameLabel;
    UILabel *_subLabel;
    UIView *_subView;
    SCPieSliceView *_pieSliceView;
    SCAvatarView *_avatarView;
    UITapGestureRecognizer *_tapGestureRecognizer;
    SCUserSession *_userSession;
    FriendStories *_friendStories;
    id <SCGroupMiniProfileGroupStoryCellDelegate> _storyDelegate;
}

- (void).cxx_destruct;
- (id)_displayNameForStoryAttribution:(id)arg1;
- (void)_setup;
- (void)handleLongPressOnStoryIconFromAvatarView:(id)arg1;
- (void)handleTapOnBitmojiFromAvatarView:(id)arg1;
- (void)handleTapOnStoryIconFromAvatarView:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutLabels;
- (void)layoutSubviews;
- (id)nameLabelFont;
- (double)nameLabelWidth;
- (id)pieSliceView;
- (void)prepareForReuse;
@property(nonatomic) __weak id <SCGroupMiniProfileGroupStoryCellDelegate> storyDelegate; // @synthesize storyDelegate=_storyDelegate;
- (void)setUserSession:(id)arg1;
- (void)updateGroupStoryName:(id)arg1;
- (void)updateLabel:(id)arg1 withStatusText:(id)arg2 date:(id)arg3 showTimestamp:(_Bool)arg4;
- (void)updateSubLabelWithFriendStories:(id)arg1;
- (void)updateWithFriendStories:(id)arg1 groupStoryName:(id)arg2 groupId:(id)arg3 groupStoryMuted:(_Bool)arg4;

@end

