//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "SCComposerViewOwner-Protocol.h"
#import "SCEventProfileContentContext-Protocol.h"
#import "SCGroupInviteJoinContextDelegate-Protocol.h"

@class NSString, SCGroupInviteJoinContext, SCGroupInviteUIDependencies;
@protocol SCGroupInviteEventProfileContentViewControllerDelegate, SCGroupInviteJoinContext, SCGroupInviteProfileActionHandler;

@interface SCGroupInviteEventProfileContentViewController : UIViewController <SCEventProfileContentContext, SCComposerViewOwner, SCGroupInviteJoinContextDelegate>
{
    SCGroupInviteUIDependencies *_dependencies;
    id <SCGroupInviteProfileActionHandler> _actionHandler;
    long long _mode;
    NSString *_legacyGroupInviteId;
    NSString *_inviteId;
    NSString *_groupId;
    long long _refreshCount;
    SCGroupInviteJoinContext *_joinContext;
    NSString *contextBaseUrl;
    id <SCGroupInviteJoinContext> joinContext;
    id <SCGroupInviteEventProfileContentViewControllerDelegate> _delegate;
}

- (void).cxx_destruct;
- (id)_contentView;
- (id)_createViewModel;
- (void)_refreshInvite;
- (id)composerWillCreateViewForClass:(Class)arg1 nodeId:(id)arg2;
@property(copy, nonatomic) NSString *contextBaseUrl; // @synthesize contextBaseUrl;
@property(nonatomic) __weak id <SCGroupInviteEventProfileContentViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)dismiss;
- (id)initWithGroupId:(id)arg1 inviteId:(id)arg2 legacyGroupInviteId:(id)arg3 dependencies:(id)arg4 mode:(long long)arg5 actionHandler:(id)arg6;
@property(retain, nonatomic) id <SCGroupInviteJoinContext> joinContext; // @synthesize joinContext;
- (void)joinLegacyEventChatWithGroupInviteId:(id)arg1 groupId:(id)arg2 mischiefInviteId:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)loadView;
- (void)logContextActionMetricWithActionTypeString:(id)arg1;
- (id)parentViewControllerForJoinContext:(id)arg1;
- (void)presentMembersListWithParticipants:(id)arg1;
- (id)toJavaScript;
- (void)wantsToEditEvent;
- (void)wantsToInviteFriends;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

