//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCGrapheneMetricId.h"

@interface SCGrapheneOptInNotificationMetrics : SCGrapheneMetricId
{
}

+ (id)all;
+ (id)errAlreadyPushed;
+ (id)errAlreadyWatched;
+ (id)errCantLoadSnapchatter;
+ (id)errExceedAppSessionLimit;
+ (id)errInappDeltaSyncFail;
+ (id)errNoLocalStory;
+ (id)errNotInAb;
+ (id)errNotInDatastore;
+ (id)errNotOptedIn;
+ (id)errNotifAlreadyWatched;
+ (id)errNotifNoStoryPlay;
+ (id)errNotifStoryDeleted;
+ (id)errNotifTooLong;
+ (id)errPointLookupFailure;
+ (id)errPublicuserIsFriend;
+ (id)mediaPrefetched;
+ (id)notifClicked;
+ (id)notifReceived;
+ (id)notifSentToDisplay;
+ (id)optInSetCompute;
+ (id)storyPlayed;
+ (id)waitForChannelModelLoad;
+ (id)waitForModelLoad;

@end

