//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"
#import "SCDataCoordinatorListener-Protocol.h"
#import "SCGroupsDataRequestListener-Protocol.h"

@class NSArray, NSCache, NSDictionary, NSLock, NSMutableArray, NSString;

@interface SCGroupStoryCollection : NSObject <NSCoding, SCGroupsDataRequestListener, SCDataCoordinatorListener>
{
    NSMutableArray *_newlyCreatedPublicationIds;
    _Bool _hasReceivedPostablesThisSession;
    NSDictionary *_pubLookupByMischiefId;
    NSCache *_storyByServedIdLookup;
    NSDictionary *_groupStoriesPublicationDict;
    NSLock *_groupStoriesPublicationLock;
    _Bool _hasSyncedToChatGroups;
    NSArray *_postableGroupStoryIds;
    NSDictionary *_myGroupStoriesPublicationDict;
}

+ (void)syncChatGroupsIfLoadedForUnarchivedCollection;
- (void).cxx_destruct;
- (id)_createNewMyGroupStoriesPublicationForId:(id)arg1;
- (void)_didBeginLeavingGroupWithId:(id)arg1;
- (void)_didChangeInfoForGroupWithId:(id)arg1;
- (void)_didFinishLoadingGroups;
- (void)_ensureNonNilObjects;
- (id)_groupStoriesForUniqueStoriesId:(id)arg1;
- (_Bool)_isGroupChatNewlyCreatedByMe:(id)arg1;
- (_Bool)_isGroupChatStoryNewlyCreatedByMe:(id)arg1;
- (void)_mergeFriendStoriesForPublications:(id)arg1;
- (id)_myPublicationForMischiefId:(id)arg1;
- (id)_myStoriesForUniqueStoriesId:(id)arg1;
- (CDUnknownBlockType)_publicationIdComparatorWithMyGroupPublicationsDict:(id)arg1 groupPublicationsDict:(id)arg2 chatGroups:(id)arg3;
- (id)_publicationsByMischiefId;
- (void)_reconstructTypeSafeGroupStoriesPublicationDict;
- (void)_removeFromMyGroupStoriesPublicationIds:(id)arg1;
- (void)_removeFromViewableGroupStoriesPublicationIds:(id)arg1;
- (void)_syncChatGroupsIfLoadedAfterStartup;
- (void)_updateGroupStoryCollectionWithPBPostableGroupStoryInfo:(id)arg1;
- (void)_updateWithPBPostableGroupStoryInfo:(id)arg1;
- (id)addPublicationForChatGroup:(id)arg1 addToPostables:(_Bool)arg2;
- (void)addStoryNotesToMyMischiefStorySnaps;
- (_Bool)canCreateGroupStory;
- (_Bool)clearExpiredStories;
- (void)dataCoordinatorDidUpdateWithIdentifier:(id)arg1 dataRequest:(id)arg2;
- (void)didCreateNewPublication:(id)arg1;
- (void)didUpdateGroupsDataRequest:(long long)arg1 groupId:(id)arg2;
- (void)didUpdateSettings:(id)arg1 publicationId:(id)arg2;
- (void)encodeWithCoder:(id)arg1;
- (id)findStoryWithServerId:(id)arg1;
- (void)generateStoryDescriptionTextForPublicationId:(id)arg1;
- (id)getOrCreateMyStoriesPublicationForId:(id)arg1;
- (id)groupStories;
- (id)groupStoriesForId:(id)arg1;
- (id)groupStoriesForMischiefId:(id)arg1;
- (id)groupStoriesForStory:(id)arg1;
@property(copy) NSDictionary *groupStoriesPublicationDict;
@property(readonly, nonatomic) _Bool hasSyncedToChatGroups; // @synthesize hasSyncedToChatGroups=_hasSyncedToChatGroups;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)mischiefIdForPublicationId:(id)arg1;
- (id)myGroupStories;
- (id)myGroupStoriesForId:(id)arg1;
@property(copy, nonatomic) NSDictionary *myGroupStoriesPublicationDict; // @synthesize myGroupStoriesPublicationDict=_myGroupStoriesPublicationDict;
- (id)myStoriesForStory:(id)arg1;
- (id)postTargetPublicationWithId:(id)arg1;
@property(copy, nonatomic) NSArray *postableGroupStoryIds; // @synthesize postableGroupStoryIds=_postableGroupStoryIds;
- (id)postableGroupStoryPublicationsSorted:(_Bool)arg1;
- (id)privatePublicationsCreatedByUsername:(id)arg1;
- (id)publicationForMischiefId:(id)arg1;
- (void)removePublicationWithId:(id)arg1;
- (id)settingsPublicationForId:(id)arg1;
- (id)settingsPublicationsForGroupStoryPublicationIds:(id)arg1;
- (id)storiesForStory:(id)arg1;
- (void)syncChatGroupsIfLoaded;
- (_Bool)updateCreatedMischiefIds:(id)arg1;
- (void)updateMyGroupStoriesPublicationDictWithMyGroupStories:(id)arg1;
- (void)updateWithSOJUGroupStoriesArray:(id)arg1 isDelta:(_Bool)arg2;
- (_Bool)updateWithSOJUGroupStoryMetadata:(id)arg1 requestedIDs:(id)arg2;
- (void)updateWithUnarchivedGroupStoryCollection:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

