//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCExperimentContext.h"

@interface SCGtqProtoViewTrackExperimentContext : SCExperimentContext
{
    _Bool _enableSojuTrack;
    _Bool _enableProtoTrack;
}

@property(readonly, nonatomic) _Bool enableProtoTrack; // @synthesize enableProtoTrack=_enableProtoTrack;
@property(readonly, nonatomic) _Bool enableSojuTrack; // @synthesize enableSojuTrack=_enableSojuTrack;
- (id)experimentName;
- (void)setupParameters;

@end

