//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"
#import "SCComposerJsConvertible-Protocol.h"

@protocol SCImpalaPublicProfileHandling <NSObject, SCComposerJsConvertible>
- (void)getStateWithCallback:(void (^)(SCImpalaPublicProfileState *, NSString *))arg1;
- (void (^)(void))observeWithCallback:(void (^)(void))arg1;
- (void)updateOptInNotificationsWithOptedIn:(_Bool)arg1 callback:(void (^)(NSString *))arg2;
- (void)updateSubscribedWithSubscribed:(_Bool)arg1 callback:(void (^)(NSString *))arg2;
@end

