//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCImageProcessLensCommandProcessToTextureBlock.h"

@class SCLazy;

@interface SCImageProcessLensCommandProcessSpectaclesToTextureBlock : SCImageProcessLensCommandProcessToTextureBlock
{
    _Bool _requiresYUVOutput;
    _Bool _isPhoto;
    SCLazy *_primaryCamera;
    SCLazy *_lookupTable;
    SCLazy *_defaultAlignment;
    SCLazy *_fieldOfView;
}

+ (unsigned long long)_frameIndexFromStereoCamera:(unsigned long long)arg1;
+ (long long)_versionFromMediaType:(unsigned long long)arg1;
- (void).cxx_destruct;
- (void)_setupWithLookupTable:(id)arg1;
@property(retain, nonatomic) SCLazy *defaultAlignment; // @synthesize defaultAlignment=_defaultAlignment;
- (long long)drawingOrientationWithInputOrientation:(long long)arg1 exportMode:(_Bool)arg2;
- (id)executeWithContext:(id)arg1 pixelBuffer:(struct __CVBuffer *)arg2 pixelWidth:(unsigned long long)arg3 pixelHeight:(unsigned long long)arg4 outputPixelWidth:(unsigned long long)arg5 outputPixelHeight:(unsigned long long)arg6 lensComponentManager:(id)arg7 command:(id)arg8 error:(id *)arg9;
@property(retain, nonatomic) SCLazy *fieldOfView; // @synthesize fieldOfView=_fieldOfView;
- (id)initWithMetadata:(id)arg1 requiresYUVOutput:(_Bool)arg2 isPhoto:(_Bool)arg3;
@property(nonatomic) _Bool isPhoto; // @synthesize isPhoto=_isPhoto;
@property(retain, nonatomic) SCLazy *lookupTable; // @synthesize lookupTable=_lookupTable;
@property(retain, nonatomic) SCLazy *primaryCamera; // @synthesize primaryCamera=_primaryCamera;
- (id)processingInfoWithPresentationTimestamp:(CDStruct_1b6d18a9)arg1 fieldOfView:(float)arg2 outputPixelWidth:(unsigned long long)arg3 outputPixelHeight:(unsigned long long)arg4 captureSource:(unsigned long long)arg5;
@property(nonatomic) _Bool requiresYUVOutput; // @synthesize requiresYUVOutput=_requiresYUVOutput;
- (struct CGAffineTransform)viewPortTransformWithInputTransform:(struct CGAffineTransform)arg1 exportMode:(_Bool)arg2;

@end

