//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCComposerView.h"

@class SCComposerScrollView, SCImpalaPublisherProfileViewModel, UIView;
@protocol SCImpalaPublisherProfileViewActionHandler;

@interface SCImpalaPublisherProfileView : SCComposerView
{
}

@property(nonatomic) __weak id <SCImpalaPublisherProfileViewActionHandler> actionHandler;
@property(readonly, nonatomic) UIView *actionSheet;
@property(readonly, nonatomic) UIView *backgroundColor;
@property(readonly, nonatomic) UIView *backgroundImage;
- (id)bundleName;
@property(readonly, nonatomic) UIView *episodeActionSheet;
@property(readonly, nonatomic) UIView *episodeView;
@property(readonly, nonatomic) UIView *errorView;
@property(readonly, nonatomic) UIView *header;
- (id)init;
- (id)initWithViewModel:(id)arg1 componentContext:(id)arg2;
@property(readonly, nonatomic) UIView *notificationView;
@property(readonly, nonatomic) SCComposerScrollView *scrollView;
@property(retain, nonatomic) SCImpalaPublisherProfileViewModel *viewModel;
@property(readonly, nonatomic) UIView *subscribeButton;
@property(readonly, nonatomic) UIView *subscribeButtonArea;
- (id)viewName;

@end

