//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSDictionary, NSString, SCImageProcessCPUCommand, SCImageProcessCommand, SCImageProcessLensCommand, SCImageProcessLensCommandSpectaclesMetadata, SCSpectaclesLookupTable;

@protocol SCImageProcessCommandProvider <NSObject>
- (SCImageProcessCommand *)imageCommandForFilterName:(NSString *)arg1 config:(NSDictionary *)arg2;
- (NSArray *)imageCommandForMultiSnapV2ThumbnailFromFilterName:(NSString *)arg1;
- (SCImageProcessCommand *)imageDistortionCorrectionCommandForLookupTable:(SCSpectaclesLookupTable *)arg1;
- (SCImageProcessLensCommand *)spectaclesNoOpLensCommandWithMetadata:(SCImageProcessLensCommandSpectaclesMetadata *)arg1;
- (SCImageProcessCPUCommand *)videoCPUCommandForFilterName:(NSString *)arg1;
- (SCImageProcessCommand *)videoCommandForFilterName:(NSString *)arg1;
- (SCImageProcessCommand *)videoCommandForFilterName:(NSString *)arg1 config:(NSDictionary *)arg2;
- (SCImageProcessCommand *)videoDistortionCorrectionCommandForLookupTable:(SCSpectaclesLookupTable *)arg1;
@end

