//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCLagunaFirmwareUpdateEventListener-Protocol.h"

@class NSString;

@interface SCLagunaFirmwareUpdateEventListenerAnnouncer : NSObject <SCLagunaFirmwareUpdateEventListener>
{
    struct mutex _mutex;
    struct shared_ptr<std::__1::vector<__weak id<SCLagunaFirmwareUpdateEventListener>, std::__1::allocator<__weak id<SCLagunaFirmwareUpdateEventListener>>>> _listeners;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (_Bool)addListener:(id)arg1;
@property(readonly, copy) NSString *description;
- (void)lagunaOnFirmwareUpdateEvent:(unsigned long long)arg1 device:(id)arg2;
- (void)lagunaOnFirmwareUpdateForDevice:(id)arg1 changedState:(unsigned long long)arg2 progress:(float)arg3;
- (void)lagunaOnFirmwareUpdateForDevice:(id)arg1 failedFromState:(unsigned long long)arg2;
- (void)lagunaOnNewFirmwareVersionFetched;
- (void)removeListener:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

