//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, SCSectionWithConfiguration, UICollectionView;
@protocol SCLensExplorerEventsController;

@interface SCLensExplorerSection : NSObject
{
    UICollectionView *_collectionView;
    _Bool _isCarouselSection;
    NSString *_sectionIdentifier;
    unsigned long long _sectionIndex;
    SCSectionWithConfiguration *_sectionConfiguration;
    id <SCLensExplorerEventsController> _eventsController;
}

- (void).cxx_destruct;
- (id)_sectionDataProvider;
- (id)_targetCollectionView;
- (void)bindToCollectionView:(id)arg1;
- (id)carouselCollectionViewFromCollectionView:(id)arg1;
- (long long)dataLoadingStatus;
@property(readonly, nonatomic) id <SCLensExplorerEventsController> eventsController; // @synthesize eventsController=_eventsController;
- (id)initWithSectionIdentifier:(id)arg1 sectionIndex:(unsigned long long)arg2 sectionConfiguration:(id)arg3 eventsController:(id)arg4 isCarouselSection:(_Bool)arg5;
@property(readonly, nonatomic) SCSectionWithConfiguration *sectionConfiguration; // @synthesize sectionConfiguration=_sectionConfiguration;
- (id)sectionDataProvider;
@property(readonly, nonatomic) NSString *sectionIdentifier; // @synthesize sectionIdentifier=_sectionIdentifier;
@property(readonly, nonatomic) unsigned long long sectionIndex; // @synthesize sectionIndex=_sectionIndex;
- (void)trackImpressions;
- (void)visibleItemsChanged;

@end

