//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCLensScanCardActionProtocol-Protocol.h"

@class NSString, SCCameraViewController, SCUnlockableDataStore, SCUnlockedLensRemover;
@protocol SCLensExplorerStudySettingsProviderProtocol;

@interface SCLensScanCardActionHandler : NSObject <SCLensScanCardActionProtocol>
{
    SCCameraViewController *_lensCameraViewController;
    SCUnlockedLensRemover *_lensRemover;
    SCUnlockableDataStore *_unlockableDataStore;
    id <SCLensExplorerStudySettingsProviderProtocol> _lensExplorerStudySettingsProvider;
    CDUnknownBlockType _dismissBlock;
}

- (void).cxx_destruct;
- (id)_presentingViewControllerFromView:(id)arg1;
- (void)blockLensCreatorForLens:(id)arg1;
- (void)dismissPresentedLensScanCard;
- (id)initWithLensCameraViewController:(id)arg1 lensRemover:(id)arg2 unlockableDataStore:(id)arg3 lensExplorerStudySettingsProvider:(id)arg4;
- (id)lensExplorerStyleUserNameWithLens:(id)arg1 redirectsToCreator:(_Bool)arg2;
- (void)openLensExplorerFromView:(id)arg1;
- (_Bool)redirectToCreatorPageEnabled;
- (void)removeLens:(id)arg1;
- (void)showCreatorPageForLens:(id)arg1 fromView:(id)arg2 dismissBlock:(CDUnknownBlockType)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

