//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCLensCacheLedgerEntry-Protocol.h"

@class NSDate, NSString, SCLensCacheMetadata;

@interface SCLensCacheLedgerEntry : NSObject <SCLensCacheLedgerEntry>
{
    SCLensCacheMetadata *_metadata;
    NSDate *_contentModificationDate;
    NSDate *_contentLastAccessDate;
    long long _accessCount;
    NSString *_ledgerKey;
    NSString *_storageMethod;
    unsigned long long _sizeInBytes;
}

+ (unsigned long long *)fasterCodingKeys;
+ (unsigned long long)fasterCodingVersion;
- (void).cxx_destruct;
@property(readonly, nonatomic) long long accessCount; // @synthesize accessCount=_accessCount;
@property(readonly, copy, nonatomic) NSDate *contentLastAccessDate; // @synthesize contentLastAccessDate=_contentLastAccessDate;
@property(readonly, copy, nonatomic) NSDate *contentModificationDate; // @synthesize contentModificationDate=_contentModificationDate;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)decodeWithFasterDecoder:(id)arg1;
@property(readonly, copy) NSString *description;
- (void)encodeWithCoder:(id)arg1;
- (void)encodeWithFasterCoder:(id)arg1;
@property(readonly) unsigned long long hash;
- (id)initWithCoder:(id)arg1;
- (id)initWithMetadata:(id)arg1 contentModificationDate:(id)arg2 contentLastAccessDate:(id)arg3 accessCount:(long long)arg4 ledgerKey:(id)arg5 storageMethod:(id)arg6 sizeInBytes:(unsigned long long)arg7;
- (_Bool)isEqual:(id)arg1;
@property(readonly, copy, nonatomic) NSString *ledgerKey; // @synthesize ledgerKey=_ledgerKey;
@property(readonly, copy, nonatomic) SCLensCacheMetadata *metadata; // @synthesize metadata=_metadata;
- (_Bool)preferFasterCoding;
- (void)setObject:(id)arg1 forUInt64Key:(unsigned long long)arg2;
- (void)setSInt64:(long long)arg1 forUInt64Key:(unsigned long long)arg2;
- (void)setUInt64:(unsigned long long)arg1 forUInt64Key:(unsigned long long)arg2;
@property(readonly, nonatomic) unsigned long long sizeInBytes; // @synthesize sizeInBytes=_sizeInBytes;
@property(readonly, copy, nonatomic) NSString *storageMethod; // @synthesize storageMethod=_storageMethod;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

