//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class SCNetworkImageView;
@protocol SCImageDownloading;

@interface SCLensExplorerBlurredImageView : UIView
{
    SCNetworkImageView *_imageView;
    id <SCImageDownloading> _imageDownloader;
}

- (void).cxx_destruct;
- (void)_prepareBlurView;
- (void)_prepareImageView;
@property(retain, nonatomic) id <SCImageDownloading> imageDownloader; // @synthesize imageDownloader=_imageDownloader;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setNetworkImageWithURL:(id)arg1;

@end

