//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCLensExplorerRouting-Protocol.h"
#import "SCLensExplorerSearchViewControllerDelegate-Protocol.h"
#import "SCLensExplorerTransitionControllerDelegate-Protocol.h"
#import "SCLensLiveLensPreviewCameraPresenterDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"

@class NSString, SCLazy, SCLensExplorerAnalytics, SCLensExplorerEventsController, SCLensExplorerEventsControllerManager, SCLensExplorerFactory, SCLensExplorerModalTransitionController, SCLensExplorerTransitionController, SCLensExplorerViewController, SCMusicLensChallengesViewController, UINavigationController, UIViewController, UIVisualEffectView;
@protocol SCLensChallengesScheduleProtocol, SCLensExplorerDependencyProviderProtocol, SCLensExplorerProfilePresenterProtocol, SCLensExplorerPrompter, SCLensExplorerRouterDelegate, SCLensLiveLensPreviewCameraPresenterProtocol;

@interface SCLensExplorerRouter : NSObject <SCLensExplorerSearchViewControllerDelegate, UINavigationControllerDelegate, SCLensExplorerTransitionControllerDelegate, SCLensLiveLensPreviewCameraPresenterDelegate, SCLensExplorerRouting>
{
    SCLensExplorerViewController *_lensFeedMainViewController;
    SCLazy *_searchViewController;
    id <SCLensExplorerDependencyProviderProtocol> _lensExplorerDependencyProvider;
    SCLensExplorerAnalytics *_lensExplorerLoggingSession;
    SCLensExplorerFactory *_lensExplorerFactory;
    SCLensExplorerEventsControllerManager *_eventsControllerManager;
    SCMusicLensChallengesViewController *_musicLensChallengesViewController;
    id <SCLensLiveLensPreviewCameraPresenterProtocol> _cameraPresenter;
    id <SCLensExplorerProfilePresenterProtocol> _profilePresenter;
    UIViewController *_rootViewController;
    id <SCLensExplorerPrompter> _lensExplorerPrompter;
    UIVisualEffectView *_navigationControllersBlurView;
    id <SCLensChallengesScheduleProtocol> _lensChallengesSchedule;
    id <SCLensExplorerRouterDelegate> _delegate;
    SCLensExplorerEventsController *_lensEventsController;
    UINavigationController *_navigationController;
    SCLensExplorerModalTransitionController *_childVCTransition;
    SCLensExplorerTransitionController *_rootVCTransition;
}

- (void).cxx_destruct;
- (id)_currentlyPresentingLensExplorerViewController;
@property(retain, nonatomic) SCLensExplorerModalTransitionController *childVCTransition; // @synthesize childVCTransition=_childVCTransition;
@property(nonatomic) __weak id <SCLensExplorerRouterDelegate> delegate; // @synthesize delegate=_delegate;
- (void)dismissIfNeededAnimated:(_Bool)arg1;
- (void)dismissLensChallengesChildViewControllers;
- (void)dismissMusicLensChallengesViewController;
- (void)finishDismissWorkflow;
- (void)handleApplicationDidEnterBackground;
- (id)initWithLensExplorerFactory:(id)arg1 searchViewController:(id)arg2 lensExplorerDependencyProvider:(id)arg3 lensChallengesSchedule:(id)arg4;
@property(readonly, nonatomic) _Bool isPresenting;
@property(readonly, nonatomic) _Bool isPresentingLensChallenges;
- (void)lensCameraPresenter:(id)arg1 didUseLens:(id)arg2;
- (void)lensCameraPresenterDidComplete:(id)arg1;
@property(retain, nonatomic) SCLensExplorerEventsController *lensEventsController; // @synthesize lensEventsController=_lensEventsController;
- (void)lensExplorerSearchControllerDidPressBackButton:(id)arg1;
- (void)lensExplorerTransitionController:(id)arg1 didBeginTransitionPresenting:(_Bool)arg2;
@property(retain, nonatomic) UINavigationController *navigationController; // @synthesize navigationController=_navigationController;
- (id)navigationController:(id)arg1 animationControllerForOperation:(long long)arg2 fromViewController:(id)arg3 toViewController:(id)arg4;
- (id)navigationController:(id)arg1 interactionControllerForAnimationController:(id)arg2;
- (id)navigationControllersBlurView;
- (void)presentChallengesViewControllerWithChallengeId:(id)arg1 fromViewController:(id)arg2 entryPoint:(long long)arg3;
- (void)presentCreatorViewControllerWithCreator:(id)arg1 fromViewController:(id)arg2 sourcePageType:(long long)arg3;
- (void)presentCreatorViewControllerWithCreator:(id)arg1 sourcePageType:(long long)arg2;
- (void)presentDebugViewControllerForStoryId:(id)arg1 debugHtml:(id)arg2 lastStreamToken:(id)arg3;
- (void)presentLensChallengeCameraWithLens:(id)arg1;
- (void)presentLensChallengesDisclaimerAlert;
- (void)presentLensExplorerViewControllerFromViewController:(id)arg1 touchableViews:(id)arg2 entryPoint:(long long)arg3;
- (void)presentLiveLensPreviewCameraWithLensItem:(id)arg1 lens:(id)arg2;
- (void)presentMusicLensChallengesViewControllerWithItem:(id)arg1;
- (void)refreshSubscriptionSection;
@property(retain, nonatomic) SCLensExplorerTransitionController *rootVCTransition; // @synthesize rootVCTransition=_rootVCTransition;
- (void)swipeTransitionController:(id)arg1 didCancelTransitionPresenting:(_Bool)arg2;
- (void)swipeTransitionController:(id)arg1 didCompleteTransitionPresenting:(_Bool)arg2;
- (void)transitWithVerticalOffset:(double)arg1 velocity:(double)arg2 panGestureState:(long long)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

