//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class SCLogger;

@interface SCLensUnlockLogger : NSObject
{
    SCLogger *_logger;
}

- (void).cxx_destruct;
- (id)initWithLogger:(id)arg1;
- (void)logLensWasUnlocked:(id)arg1 source:(long long)arg2;
- (void)logLensWasUnlocked:(id)arg1 unlockSource:(long long)arg2;
- (void)logLensWasUnlockedWithId:(id)arg1 scanSource:(long long)arg2 deepLinkSource:(long long)arg3;
- (void)logLensWasUnlockedWithId:(id)arg1 source:(long long)arg2;
- (void)logLensWasUnlockedWithId:(id)arg1 unlockSource:(long long)arg2;

@end

