//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCLensUriServiceProviderRouteHandler-Protocol.h"

@class NSDictionary, NSString, SCSnapTokenManager;
@protocol SCRequestManager;

@interface SCLensUriServiceWhitelistedHttpHandler : NSObject <SCLensUriServiceProviderRouteHandler>
{
    id <SCRequestManager> _requestManager;
    SCSnapTokenManager *_snapTokenManager;
    NSDictionary *_snapTokenAccessTypesByUrl;
}

- (void).cxx_destruct;
- (id)devHostnameWhitelist;
- (void)fetchSnapTokenAndMakeRequest:(id)arg1 headers:(id)arg2 accessType:(unsigned long long)arg3 completion:(CDUnknownBlockType)arg4;
- (void)handleRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)initWithRequestManager:(id)arg1 snapTokenManager:(id)arg2;
- (void)makeRequest:(id)arg1 headers:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)prodHostnameWhitelist;
- (id)snapTokenAccessTypesByUrl;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

