//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCLensRemoteAssetsUrlResolver-Protocol.h"

@class SCScopedAccess;

@interface SCLensCofBasedRemoteAssetsUrlResolver : NSObject <SCLensRemoteAssetsUrlResolver>
{
    SCScopedAccess *_circumstanceEngine;
}

+ (id)_urlStringFromConfigValue:(id)arg1 error:(id *)arg2;
- (void).cxx_destruct;
- (id)initWithCircumstanceEngine:(id)arg1;
- (void)urlStringForLensAsset:(id)arg1 completion:(CDUnknownBlockType)arg2;

@end

