//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSDate;
@protocol SCLensMetadataFetcherDelegate;

@interface SCLensMetadataFetcher : NSObject <NSCoding>
{
    NSDate *_retryTimestamp;
    long long _onceTokenForPreviousUpdateTimestamp;
    _Bool _isFetching;
    id <SCLensMetadataFetcherDelegate> _delegate;
    NSDate *_previousUpdateTimestamp;
}

- (void).cxx_destruct;
- (void)clearCache;
@property(nonatomic) __weak id <SCLensMetadataFetcherDelegate> delegate; // @synthesize delegate=_delegate;
- (void)encodeWithCoder:(id)arg1;
- (void)fetchDataWithRequestManager:(id)arg1;
- (void)fetchDataWithRequestManagerIfNecessary:(id)arg1;
- (id)initWithCoder:(id)arg1;
@property(nonatomic) _Bool isFetching; // @synthesize isFetching=_isFetching;
@property(retain, nonatomic) NSDate *previousUpdateTimestamp; // @synthesize previousUpdateTimestamp=_previousUpdateTimestamp;
- (void)retryFetchDataWithRequestManager:(id)arg1 delay:(float)arg2 error:(id)arg3;
- (double)retryInterval;
@property(retain, nonatomic) NSDate *retryTimestamp; // @synthesize retryTimestamp=_retryTimestamp;
- (double)updateInterval;

@end

