//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, UIColor, UIFont;

@protocol SCLensLayoutTextConfigurable <NSObject>
@property(retain, nonatomic) UIFont *font;
@property(nonatomic) long long lineBreakMode;
@property(nonatomic) long long numberOfLines;
- (void)sc_applyStyles:(NSArray *)arg1;
@property(nonatomic) long long textAlignment;
@property(retain, nonatomic) UIColor *textColor;
@end

