//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDate, NSString;

@protocol SCLensUser <NSObject>
- (NSString *)bitmojiAvatarId;
- (NSString *)bitmojiSelfieId;
- (_Bool)isActiveLensesUser;
- (_Bool)isCheetahNewUser;
- (_Bool)isLoggedIn;
- (_Bool)isNewUser;
@property(retain, nonatomic) NSDate *lastLensesActivationDate;
@property(retain, nonatomic) NSDate *lastSpectaclesLensesActivationDate;
- (NSString *)lensStudioId;
@property(nonatomic) unsigned long long lensesActivationTooltipShownCount;
- (NSString *)userId;
- (NSString *)usernameDisplayOnly;
@end

