//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCOperaPlaylistDataSource-Protocol.h"

@class NSDictionary, NSString, SCUserSession;
@protocol SCOperaMediaManager, SCStreamingURLProviding;

@interface SCLongformShowOperaDataSource : NSObject <SCOperaPlaylistDataSource>
{
    SCUserSession *_userSession;
    NSDictionary *_editionIdToDataSource;
    NSDictionary *_editionIdToShow;
    id <SCOperaMediaManager> _mediaManager;
    id <SCStreamingURLProviding> _streamingURLProvider;
}

- (void).cxx_destruct;
- (id)_showDataSourceForEditionId:(id)arg1;
- (_Bool)canResolvePlaylistItemGroupDataModel:(id)arg1;
- (id)dataModelForGroup:(id)arg1;
- (id)dataModelForItem:(id)arg1;
- (id)initWithUserSession:(id)arg1 mediaManager:(id)arg2;
- (void)loadMediaForPlaylistItemGroup:(id)arg1;
- (_Bool)needToPrepareMediaBeforeDisplay;
- (void)pagesPropertiesForDataModel:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)playlistItemGroupForDataModel:(id)arg1;
- (void)prepareMediaForItem:(id)arg1 waitForDownloading:(_Bool)arg2 startWaitingForDownloadCallback:(CDUnknownBlockType)arg3 completion:(CDUnknownBlockType)arg4;
- (void)removeMediaForItem:(id)arg1;
- (void)resolvePlaylistItemGroup:(id)arg1;
- (void)teardownDataModelForItem:(id)arg1;
- (void)unresolvePlaylistItemGroup:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

