//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCMapPersonLocationsListener-Protocol.h"

@class NSString, SCFeatureSettingsManager, SCLocationSharingPreferencesV1, SCMapBitmojiAvatarGenerator;
@protocol SCMapPeopleFriendsProvider, SCMapPersonLocationsProviding;

@interface SCMapBitmojiPreloader : NSObject <SCMapPersonLocationsListener>
{
    NSString *_currentUserId;
    SCFeatureSettingsManager *_featureSettingsManager;
    SCLocationSharingPreferencesV1 *_locationSharingPreferences;
    SCMapBitmojiAvatarGenerator *_mapBitmojiAvatarGenerator;
    id <SCMapPeopleFriendsProvider> _mapPeopleFriendsProvider;
    id <SCMapPersonLocationsProviding> _mapPersonLocationsProvider;
}

- (void).cxx_destruct;
- (void)_preloadStickerForCurrentUserLocation:(id)arg1;
- (id)initWithCurrentUserId:(id)arg1 featureSettingsManager:(id)arg2 locationSharingPreferences:(id)arg3 mapBitmojiAvatarGenerator:(id)arg4 mapPeopleFriendsProvider:(id)arg5 mapPersonLocationsProvider:(id)arg6;
- (void)personLocationsProviderDidUpdate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

