//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "SCMapExploreSpriteManagerDelegate-Protocol.h"
#import "SCMapExplorerCarouselViewDelegate-Protocol.h"
#import "SCMapScreenshotOverlayViewsProvider-Protocol.h"
#import "SCMapTouchResponder-Protocol.h"
#import "SCPassthroughDataSource-Protocol.h"
#import "SCShakeToReportDelegate-Protocol.h"

@class NSMutableSet, NSOrderedSet, NSString, SCContextV2Manager, SCExperimentManager, SCLocationSharingPreferencesV1, SCMapExploreDataStoreV1, SCMapExploreLogger, SCMapExploreSpriteManager, SCMapExploreStatus, SCMapExplorerCarouselView, SCMapUserPreferences, SCXRenderLayer, UIView;
@protocol SCContextV2DependencyProvider, SCImageDownloading, SCMapConfiguration, SCMapExploreUserInfoProvider, SCMapExploreViewControllerDelegate, SCMapPeopleFriendsProvider, SCMapPeopleGroupsProvider, SCMapPersonLocationsProviding, SCMapReplyMessageSender, SCMapViewport;

@interface SCMapExploreViewController : UIViewController <SCPassthroughDataSource, SCMapExplorerCarouselViewDelegate, SCMapExploreSpriteManagerDelegate, SCShakeToReportDelegate, SCMapScreenshotOverlayViewsProvider, SCMapTouchResponder>
{
    id <SCContextV2DependencyProvider> _contextDependencyProvider;
    SCContextV2Manager *_contextV2Manager;
    NSString *_currentUserId;
    id <SCMapExploreViewControllerDelegate> _delegate;
    SCExperimentManager *_experimentManager;
    SCMapExploreDataStoreV1 *_exploreDataStore;
    id <SCImageDownloading> _imageDownloader;
    SCLocationSharingPreferencesV1 *_locationSharingPreferences;
    id <SCMapConfiguration> _mapConfiguration;
    id <SCMapPeopleFriendsProvider> _mapPeopleFriendsProvider;
    id <SCMapPeopleGroupsProvider> _mapPeopleGroupsProvider;
    id <SCMapPersonLocationsProviding> _mapPersonLocationsProvider;
    SCMapUserPreferences *_mapUserPreferences;
    id <SCMapViewport> _mapViewport;
    UIView *_mapView;
    SCXRenderLayer *_renderLayer;
    id <SCMapExploreUserInfoProvider> _userInfoProvider;
    id <SCMapReplyMessageSender> _replyMessageSender;
    NSOrderedSet *_statuses;
    SCMapExploreStatus *_preferredInitialStatus;
    SCMapExploreLogger *_logger;
    unsigned long long _mapSessionId;
    SCMapExploreSpriteManager *_spriteManager;
    SCMapExplorerCarouselView *_carouselView;
    _Bool _hasAnimatedToStatus;
    NSMutableSet *_skippedStatuses;
    SCMapExploreStatus *_visibleStatus;
}

- (void).cxx_destruct;
- (void)_applicationDidBecomeActive:(id)arg1;
- (void)_applicationDidEnterBackground:(id)arg1;
- (struct CGRect)_desiredFrameForCarousel;
- (void)_didTakeScreenshot:(id)arg1;
- (void)_logCloseWithExitEvent:(long long)arg1;
- (void)_logOpen;
- (void)_renderStatus:(id)arg1 animated:(_Bool)arg2;
- (void)_showCarouselForStatus:(id)arg1 animated:(_Bool)arg2;
- (void)_updateUI;
- (id)defaultProjectNameV2;
- (void)didCancelTouchOnMapWithReason:(id)arg1;
- (struct SCMapTouchResponderResult)didLongPressOnMapAtPoint:(struct CGPoint)arg1;
- (struct SCMapTouchResponderResult)didTouchDownOnMapAtPoint:(struct CGPoint)arg1;
- (struct SCMapTouchResponderResult)didTouchUpOnMapAtPoint:(struct CGPoint)arg1;
- (void)didZoomMap;
- (id)hitTest:(struct CGPoint)arg1 forPassthroughView:(id)arg2;
- (id)initWithContextDependencyProvider:(id)arg1 contextV2Manager:(id)arg2 currentUserId:(id)arg3 delegate:(id)arg4 experimentManager:(id)arg5 exploreDataStore:(id)arg6 imageDownloader:(id)arg7 locationSharingPreferences:(id)arg8 loggerSession:(id)arg9 mapBitmojiAvatarGenerator:(id)arg10 mapConfiguration:(id)arg11 mapPeopleFriendsProvider:(id)arg12 mapPeopleGroupsProvider:(id)arg13 mapPersonLocationsProvider:(id)arg14 mapUserPreferences:(id)arg15 mapViewport:(id)arg16 mapView:(id)arg17 renderLayer:(id)arg18 userInfoProvider:(id)arg19 replyMessageSender:(id)arg20;
- (void)loadView;
- (void)mapExploreSpriteManager:(id)arg1 wantsToCenterOnCoordinate:(struct CLLocationCoordinate2D)arg2;
- (void)mapExploreSpriteManager:(id)arg1 wantsToShowMiniProfileForUserId:(id)arg2;
- (void)mapExplorerCarouselView:(id)arg1 didLongPressOnPerson:(id)arg2;
- (void)mapExplorerCarouselView:(id)arg1 didLongPressOnStatus:(id)arg2;
- (void)mapExplorerCarouselView:(id)arg1 didShowStatus:(id)arg2;
- (void)mapExplorerCarouselView:(id)arg1 didTapStatus:(id)arg2;
- (void)mapExplorerCarouselView:(id)arg1 didTapStoryForPerson:(id)arg2 sourceView:(id)arg3;
- (id)mapExplorerCarouselView:(id)arg1 screenshotGeneratorForUserId:(id)arg2;
- (void)mapExplorerCarouselView:(id)arg1 wantsChatForPeople:(id)arg2;
- (void)mapExplorerCarouselView:(id)arg1 wantsToNavigateToURL:(id)arg2;
- (void)mapExplorerCarouselView:(id)arg1 wantsToPresentReplyCameraForUserId:(id)arg2;
- (void)mapExplorerCarouselView:(id)arg1 wantsToSendReplyMessage:(id)arg2 toUserId:(id)arg3;
- (void)mapExplorerCarouselView:(id)arg1 willShowStatus:(id)arg2;
- (void)mapExplorerCarouselViewDidFocus:(id)arg1 forUserId:(id)arg2;
- (void)mapExplorerCarouselViewWantsToBeDismissed:(id)arg1;
- (void)mapExplorerCarouselViewWantsToPlayMapStory:(id)arg1 withPoiId:(id)arg2 fromSourceView:(id)arg3;
- (id)mapScreenshotOverlayViews;
- (long long)preferredStatusBarStyle;
- (void)prepareToDismissWithExitEvent:(long long)arg1 completion:(CDUnknownBlockType)arg2;
- (void)priorResponderDidHandleTouch:(id)arg1;
@property(retain, nonatomic) SCMapExploreStatus *visibleStatus; // @synthesize visibleStatus=_visibleStatus;
- (void)setVisibleStatus:(id)arg1 animated:(_Bool)arg2;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillLayoutSubviews;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

