//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSURLSessionDataTask.h>

@class SCRequest;

@interface SCMapboxURLSessionDataTask : NSURLSessionDataTask
{
    SCRequest *_request;
    CDUnknownBlockType _completionHandler;
}

- (void).cxx_destruct;
- (void)cancel;
@property(copy, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
- (id)initWithSCRequest:(id)arg1;
- (void)resume;
- (long long)state;
- (void)suspend;

@end

