//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"
#import "SCXClusterable-Protocol.h"

@class NSArray, NSString, NSURL, SCMapEffect;

@interface SCMapPersonLocationCluster : NSObject <NSCopying, SCXClusterable>
{
    _Bool _crowd;
    NSArray *_personLocations;
    NSURL *_floorRemoteImageURL;
    NSURL *_propRemoteImageURL;
    SCMapEffect *_mapEffect;
    struct CLLocationCoordinate2D _coordinate;
}

+ (id)personLocationClusterFromSCMTFriendCluster:(id)arg1 mapPeopleProvider:(id)arg2 mapPersonStatusProvider:(id)arg3 currentUserId:(id)arg4;
- (void).cxx_destruct;
- (id)clusterId;
@property(readonly, nonatomic) struct CLLocationCoordinate2D coordinate; // @synthesize coordinate=_coordinate;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, copy) NSString *description;
@property(readonly, copy, nonatomic) NSURL *floorRemoteImageURL; // @synthesize floorRemoteImageURL=_floorRemoteImageURL;
@property(readonly) unsigned long long hash;
- (id)initWithCoordinate:(struct CLLocationCoordinate2D)arg1 personLocations:(id)arg2 floorRemoteImageURL:(id)arg3 propRemoteImageURL:(id)arg4 mapEffect:(id)arg5 crowd:(_Bool)arg6;
@property(readonly, nonatomic, getter=isCrowd) _Bool crowd; // @synthesize crowd=_crowd;
- (_Bool)isEqual:(id)arg1;
@property(readonly, copy, nonatomic) SCMapEffect *mapEffect; // @synthesize mapEffect=_mapEffect;
@property(readonly, copy, nonatomic) NSArray *personLocations; // @synthesize personLocations=_personLocations;
@property(readonly, copy, nonatomic) NSURL *propRemoteImageURL; // @synthesize propRemoteImageURL=_propRemoteImageURL;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

