//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"
#import "SCComposerJsConvertible-Protocol.h"

@class NSString;

@interface SCMapPassportAchievementAlertViewModel : NSObject <SCComposerJsConvertible, NSCopying>
{
    NSString *_title;
    NSString *_subtitle;
    NSString *_bitmojiStickerId;
    NSString *_doneButtonTitle;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *bitmojiStickerId; // @synthesize bitmojiStickerId=_bitmojiStickerId;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(copy, nonatomic) NSString *doneButtonTitle; // @synthesize doneButtonTitle=_doneButtonTitle;
- (id)initWithTitle:(id)arg1 subtitle:(id)arg2 bitmojiStickerId:(id)arg3 doneButtonTitle:(id)arg4;
@property(copy, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (id)toJavaScript;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

