//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCMapTouchResponder-Protocol.h"

@class NSMutableArray, NSString, SCMapExploreStatus, SCXBitmojiSpriteTextureBinder, SCXFloorSpriteTextureBinder, SCXRenderLayer, SCXSpriteWidthInterpolatorProvider, UIView;
@protocol SCMapConfiguration, SCMapExploreSpriteManagerDelegate, SCMapPersonLocationsProviding, SCMapViewport, SCXBitmojiAssetProvider;

@interface SCMapExploreSpriteManager : NSObject <SCMapTouchResponder>
{
    NSString *_currentUserId;
    id <SCMapPersonLocationsProviding> _mapPersonLocationsProvider;
    _Bool _ignoreTouchUpAndLongPress;
    _Bool _depressedSprites;
    id <SCMapExploreSpriteManagerDelegate> _delegate;
    SCXRenderLayer *_renderLayer;
    UIView *_mapView;
    id <SCMapConfiguration> _mapConfiguration;
    id <SCMapViewport> _mapViewport;
    id <SCXBitmojiAssetProvider> _assetProvider;
    SCXBitmojiSpriteTextureBinder *_bitmojiTextureBinder;
    SCXFloorSpriteTextureBinder *_floorTextureBinder;
    SCXSpriteWidthInterpolatorProvider *_widthInterpolatorProvider;
    SCMapExploreStatus *_status;
    NSMutableArray *_spritesOnTheMap;
    NSMutableArray *_pathsOnTheMap;
    NSMutableArray *_nonCollidedPoiIds;
}

- (void).cxx_destruct;
- (void)_addNonCollidedPoiId:(id)arg1;
- (void)_addSpriteToMap:(id)arg1;
- (void)_addTravelPathToMap:(id)arg1;
- (id)_bitmojiSpritesAtPoint:(struct CGPoint)arg1;
- (void)_cleanUpDisplayedStatus;
- (void)_handleTapOnBitmojiSprite:(id)arg1 touchPoint:(struct CGPoint)arg2;
- (_Bool)_poiExistsOverSprite:(id)arg1 atTouchPoint:(struct CGPoint)arg2;
- (void)_renderGroupStatus:(id)arg1 animated:(_Bool)arg2;
- (void)_renderSoloStatus:(id)arg1 animated:(_Bool)arg2;
@property(retain, nonatomic) id <SCXBitmojiAssetProvider> assetProvider; // @synthesize assetProvider=_assetProvider;
@property(retain, nonatomic) SCXBitmojiSpriteTextureBinder *bitmojiTextureBinder; // @synthesize bitmojiTextureBinder=_bitmojiTextureBinder;
- (void)dealloc;
@property(nonatomic) __weak id <SCMapExploreSpriteManagerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool depressedSprites; // @synthesize depressedSprites=_depressedSprites;
- (void)didCancelTouchOnMapWithReason:(id)arg1;
- (struct SCMapTouchResponderResult)didLongPressOnMapAtPoint:(struct CGPoint)arg1;
- (struct SCMapTouchResponderResult)didTouchDownOnMapAtPoint:(struct CGPoint)arg1;
- (struct SCMapTouchResponderResult)didTouchUpOnMapAtPoint:(struct CGPoint)arg1;
@property(retain, nonatomic) SCXFloorSpriteTextureBinder *floorTextureBinder; // @synthesize floorTextureBinder=_floorTextureBinder;
@property(nonatomic) _Bool ignoreTouchUpAndLongPress; // @synthesize ignoreTouchUpAndLongPress=_ignoreTouchUpAndLongPress;
- (id)initWithCurrentUserId:(id)arg1 mapPersonLocationsProvider:(id)arg2 mapRenderLayer:(id)arg3 mapView:(id)arg4 mapConfiguration:(id)arg5 mapViewport:(id)arg6 mapBitmojiAssetProvider:(id)arg7 mapBitmojiAvatarGenerator:(id)arg8 minimumBitmojiSpriteWidth:(double)arg9 maximumBitmojiSpriteWidth:(double)arg10;
@property(nonatomic) __weak id <SCMapConfiguration> mapConfiguration; // @synthesize mapConfiguration=_mapConfiguration;
@property(nonatomic) __weak UIView *mapView; // @synthesize mapView=_mapView;
@property(nonatomic) __weak id <SCMapViewport> mapViewport; // @synthesize mapViewport=_mapViewport;
@property(retain, nonatomic) NSMutableArray *nonCollidedPoiIds; // @synthesize nonCollidedPoiIds=_nonCollidedPoiIds;
@property(retain, nonatomic) NSMutableArray *pathsOnTheMap; // @synthesize pathsOnTheMap=_pathsOnTheMap;
- (void)priorResponderDidHandleTouch:(id)arg1;
@property(nonatomic) __weak SCXRenderLayer *renderLayer; // @synthesize renderLayer=_renderLayer;
@property(retain, nonatomic) NSMutableArray *spritesOnTheMap; // @synthesize spritesOnTheMap=_spritesOnTheMap;
@property(retain, nonatomic) SCMapExploreStatus *status; // @synthesize status=_status;
- (void)setStatus:(id)arg1 animated:(_Bool)arg2;
@property(retain, nonatomic) SCXSpriteWidthInterpolatorProvider *widthInterpolatorProvider; // @synthesize widthInterpolatorProvider=_widthInterpolatorProvider;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

