//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "SCComposerViewOwner-Protocol.h"
#import "SCMapCurrentStatusViewControllerDelegate-Protocol.h"
#import "SCMapModalViewControllerSubclass-Protocol.h"
#import "SCMapStatusCreationContext-Protocol.h"
#import "SCMapStatusFetchingListener-Protocol.h"
#import "SCVenueFeedbackViewControllerDelegate-Protocol.h"

@class NSString, SCFeatureSettingsManager, SCLocationSharingAudienceChooser, SCLocationSharingPreferencesV1, SCMapExploreDataStoreV1, SCMapLoggerEventSender, SCMapModalViewController, SCMapSnapTokenService, SCMapStatusCreationView, SCMapUserPreferences, SCStopwatch;
@protocol SCBitmojiSettingsPresenting, SCLocationProvider, SCLocationSharingSettingsPresenting, SCMapGDPRComplianceProviding, SCMapPassportPresenting, SCMapPeopleFriendsProvider, SCMapPersonLocationsProviding, SCMapStatusCreationViewControllerDelegate, SCMapStatusCreationViewProvider, SCNearbyVenueProviding;

@interface SCMapStatusCreationViewController : UIViewController <SCComposerViewOwner, SCMapCurrentStatusViewControllerDelegate, SCMapStatusFetchingListener, SCMapStatusCreationContext, SCVenueFeedbackViewControllerDelegate, SCMapModalViewControllerSubclass>
{
    NSString *_bitmojiAvatarId;
    id <SCBitmojiSettingsPresenting> _bitmojiSettingsPresenter;
    NSString *_currentUserId;
    id <SCMapStatusCreationViewControllerDelegate> _delegate;
    SCMapExploreDataStoreV1 *_exploreDataStore;
    SCFeatureSettingsManager *_featureSettingsManager;
    id <SCLocationProvider> _locationProvider;
    SCLocationSharingPreferencesV1 *_locationSharingPreferences;
    id <SCLocationSharingSettingsPresenting> _locationSharingSettingsPresenter;
    id <SCMapGDPRComplianceProviding> _mapGDPRComplianceProvider;
    SCMapLoggerEventSender *_mapLoggerEventSender;
    id <SCMapPeopleFriendsProvider> _mapPeopleFriendsProvider;
    id <SCMapPersonLocationsProviding> _mapPersonLocationsProvider;
    SCMapUserPreferences *_mapUserPreferences;
    id <SCNearbyVenueProviding> _nearbyVenueProvider;
    id <SCMapPassportPresenting> _passportPresenter;
    SCMapSnapTokenService *_snapTokenService;
    long long _source;
    id <SCMapStatusCreationViewProvider> _viewProvider;
    SCMapStatusCreationView *_statusCreationView;
    unsigned long long _statusSessionId;
    SCStopwatch *_stopwatch;
    SCStopwatch *_onboardingPageStopwatch;
    long long _previousOnboardingPageName;
    SCLocationSharingAudienceChooser *_presentedAudienceChooser;
}

+ (id)_currentStatusViewModelFromStatus:(id)arg1;
+ (id)_subtitleForStatus:(id)arg1;
- (void).cxx_destruct;
- (id)_currentStatusViewModels;
- (_Bool)_isPassportEnabled;
- (void)_promptToShareLocationWithCompletion:(CDUnknownBlockType)arg1;
- (void)_removeOptionWithId:(id)arg1;
- (void)_setCurrentOnboardingPageName:(long long)arg1;
- (void)_setOnboarded;
- (void)_setStatusWithRequest:(id)arg1 type:(long long)arg2;
- (_Bool)_shouldShowOnboarding;
- (id)composerWillCreateViewForClass:(Class)arg1 nodeId:(id)arg2;
- (id)defaultProjectNameV2;
- (void)didChangeOnboardingPageWithIndex:(double)arg1;
- (void)didChooseStatusOptionWithIdentifier:(id)arg1 title:(id)arg2 type:(double)arg3 index:(double)arg4 stickerCount:(double)arg5 actionId:(id)arg6 prefix:(id)arg7 creatorUserId:(id)arg8;
- (void)didTapCreateBitmoji;
- (void)didTapCurrentStatusWithRequiresUpdate:(_Bool)arg1 statusId:(id)arg2;
- (void)didTapDeleteOptionWithIdentifier:(id)arg1 title:(id)arg2 type:(double)arg3;
- (void)didTapDismissButton;
- (void)didTapLetsGo;
- (void)didTapPassportButton;
- (void)didTapReportOptionWithIdentifier:(id)arg1 title:(id)arg2 type:(double)arg3 creatorUserId:(id)arg4;
- (void)didTapStatusOptionWithType:(double)arg1 index:(double)arg2 stickerCount:(double)arg3;
- (void)didViewCurrentStatusWithStatusId:(id)arg1;
- (id)initWithBitmojiAvatarId:(id)arg1 bitmojiSettingsPresenter:(id)arg2 currentUserId:(id)arg3 delegate:(id)arg4 exploreDataStore:(id)arg5 featureSettingsManager:(id)arg6 locationProvider:(id)arg7 locationSharingPreferences:(id)arg8 locationSharingSettingsPresenter:(id)arg9 mapGDPRComplianceProvider:(id)arg10 mapLoggerEventSender:(id)arg11 mapPeopleFriendsProvider:(id)arg12 mapPersonLocationsProvider:(id)arg13 mapUserPreferences:(id)arg14 nearbyVenueProvider:(id)arg15 passportPresenter:(id)arg16 snapTokenService:(id)arg17 source:(long long)arg18 viewProvider:(id)arg19;
- (void)mapCurrentStatusViewController:(id)arg1 didDeleteMyStatus:(id)arg2 wasMostRecentStatus:(_Bool)arg3;
- (void)mapCurrentStatusViewController:(id)arg1 wantsToPresentStoryForUserId:(id)arg2 fromBaseView:(id)arg3;
- (void)mapCurrentStatusViewController:(id)arg1 wantsToShowProfileForUserId:(id)arg2;
- (void)mapCurrentStatusViewControllerWantsToDismiss:(id)arg1;
- (void)mapStatusFetcherDidLoadMyStatus:(id)arg1;
- (_Bool)modalViewController:(id)arg1 panGestureRecognizer:(id)arg2 shouldBeginInView:(id)arg3;
- (void)modalViewControllerIsFullyPresented:(id)arg1;
- (long long)preferredStatusBarStyle;
- (id)toJavaScript;
- (void)venueFeedbackViewControllerWantsToDismiss:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillDisappear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(nonatomic) __weak SCMapModalViewController *parentModalViewController;
@property(readonly) Class superclass;

@end

