//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCAPIClientListener-Protocol.h"

@class NSString;

@interface SCMediaRequestLogger : NSObject <SCAPIClientListener>
{
}

+ (id)shared;
- (_Bool)_isDiscoverSnapPath:(id)arg1;
- (_Bool)_isMediaDownloadFromSearch:(id)arg1;
- (_Bool)_isStorySnapPath:(id)arg1;
- (void)_logBlizzardStorySnapDownloadWithParameters:(id)arg1 encodingResults:(id)arg2 request:(id)arg3 response:(id)arg4 isD2S:(_Bool)arg5;
- (void)_logMediaDownloadEventForSearchWithParameters:(id)arg1;
- (_Bool)_shouldLogMediaDownloadEventWithPath:(id)arg1;
- (void)apiClientDidFinishRequest:(id)arg1 response:(id)arg2 parameters:(id)arg3;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

