//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCMiniProfileSectionController.h"

#import "SCMiniProfileFooterRowControllerDelegate-Protocol.h"
#import "SCMiniProfileFriendRowControllerDelegate-Protocol.h"
#import "SCSnapchattersDataRequestListener-Protocol.h"

@class Friend, NSString, SCUserSession;
@protocol SCMiniProfileFriendIdentitySectionControllerDelegate;

@interface SCMiniProfileFriendIdentitySectionController : SCMiniProfileSectionController <SCMiniProfileFriendRowControllerDelegate, SCMiniProfileFooterRowControllerDelegate, SCSnapchattersDataRequestListener>
{
    Friend *_friend;
    SCUserSession *_userSession;
    _Bool _hideStory;
    _Bool _showMore;
    id <SCMiniProfileFriendIdentitySectionControllerDelegate> _delegate;
}

- (void).cxx_destruct;
- (void)didEndSnapchattersUpdateDataRequest:(id)arg1 withSuccess:(_Bool)arg2;
- (void)didStartSnapchattersUpdateDataRequest:(id)arg1;
- (double)extraBottomInsetSpacing;
- (void)footerRowControllerDidSelect:(id)arg1;
- (void)friendIdentityRowControllerDidTapAddFriend:(id)arg1;
- (void)friendIdentityRowControllerDidTapFriendStory:(id)arg1 baseView:(id)arg2;
- (id)initWithFriend:(id)arg1 userSession:(id)arg2 hideStory:(_Bool)arg3 delegate:(id)arg4;
- (long long)numberOfRows;
- (id)rowControllerAtIndex:(long long)arg1;
- (void)setShowsMore:(_Bool)arg1 animated:(_Bool)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

