//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class SCExtendedHitButton, SCLoadingIndicatorView, SCMiniProfileStorySubscribeButtonViewModel, UIImageView, UILabel;
@protocol SCMiniProfileStorySubscribeButtonDelegate;

@interface SCMiniProfileStorySubscribeButton : UIView
{
    id <SCMiniProfileStorySubscribeButtonDelegate> _delegate;
    SCMiniProfileStorySubscribeButtonViewModel *_viewModel;
    SCLoadingIndicatorView *_loadingIndicator;
    SCExtendedHitButton *_button;
    UIImageView *_buttonImageView;
    UILabel *_buttonTitleLabel;
}

- (void).cxx_destruct;
- (id)_getAttributedTitleWithTitle:(id)arg1;
- (id)_getBorderColor;
- (void)_subscribeButtonTapped;
@property(retain, nonatomic) SCExtendedHitButton *button; // @synthesize button=_button;
@property(retain, nonatomic) UIImageView *buttonImageView; // @synthesize buttonImageView=_buttonImageView;
@property(retain, nonatomic) UILabel *buttonTitleLabel; // @synthesize buttonTitleLabel=_buttonTitleLabel;
@property(nonatomic) __weak id <SCMiniProfileStorySubscribeButtonDelegate> delegate; // @synthesize delegate=_delegate;
- (double)expectedWidth;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
@property(retain, nonatomic) SCLoadingIndicatorView *loadingIndicator; // @synthesize loadingIndicator=_loadingIndicator;
@property(retain, nonatomic) SCMiniProfileStorySubscribeButtonViewModel *viewModel; // @synthesize viewModel=_viewModel;

@end

