//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSString, SCActionModel;

@interface SCModalCardHeaderViewModel : NSObject <NSCopying>
{
    _Bool _showSearchIcon;
    NSString *_backButtonImageName;
    NSString *_placeholderText;
    SCActionModel *_backButtonActionModel;
    double _backButtonLeadingPadding;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) SCActionModel *backButtonActionModel; // @synthesize backButtonActionModel=_backButtonActionModel;
@property(readonly, copy, nonatomic) NSString *backButtonImageName; // @synthesize backButtonImageName=_backButtonImageName;
@property(readonly, nonatomic) double backButtonLeadingPadding; // @synthesize backButtonLeadingPadding=_backButtonLeadingPadding;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)hash;
- (id)initWithBackButtonImageName:(id)arg1 placeholderText:(id)arg2 backButtonActionModel:(id)arg3 backButtonLeadingPadding:(double)arg4 showSearchIcon:(_Bool)arg5;
- (_Bool)isEqual:(id)arg1;
@property(readonly, copy, nonatomic) NSString *placeholderText; // @synthesize placeholderText=_placeholderText;
@property(readonly, nonatomic) _Bool showSearchIcon; // @synthesize showSearchIcon=_showSearchIcon;

@end

