//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class SCActionModel, SCModalCardBackgroundEffect, SCModalCardHeaderViewModel;

@interface SCModalCardRootViewModel : NSObject <NSCopying>
{
    SCModalCardHeaderViewModel *_headerViewModel;
    double _contentCustomTopOffset;
    double _extraContentHeight;
    SCModalCardBackgroundEffect *_backgroundEffect;
    SCActionModel *_backgroundActionModel;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) SCActionModel *backgroundActionModel; // @synthesize backgroundActionModel=_backgroundActionModel;
@property(readonly, copy, nonatomic) SCModalCardBackgroundEffect *backgroundEffect; // @synthesize backgroundEffect=_backgroundEffect;
@property(readonly, nonatomic) double contentCustomTopOffset; // @synthesize contentCustomTopOffset=_contentCustomTopOffset;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, nonatomic) double extraContentHeight; // @synthesize extraContentHeight=_extraContentHeight;
- (unsigned long long)hash;
@property(readonly, copy, nonatomic) SCModalCardHeaderViewModel *headerViewModel; // @synthesize headerViewModel=_headerViewModel;
- (id)initWithHeaderViewModel:(id)arg1 contentCustomTopOffset:(double)arg2 extraContentHeight:(double)arg3 backgroundEffect:(id)arg4 backgroundActionModel:(id)arg5;
- (_Bool)isEqual:(id)arg1;

@end

