//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSString;

@interface SCMockCaptureSession : NSObject
{
    _Bool _isRunning;
    _Bool _automaticallyConfiguresApplicationAudioSession;
    NSString *_sessionPreset;
    NSMutableArray *_outputs;
    NSMutableArray *_inputs;
}

- (void).cxx_destruct;
- (void)addInput:(id)arg1;
- (void)addOutput:(id)arg1;
@property(nonatomic) _Bool automaticallyConfiguresApplicationAudioSession; // @synthesize automaticallyConfiguresApplicationAudioSession=_automaticallyConfiguresApplicationAudioSession;
- (void)beginConfiguration;
- (_Bool)canAddInput:(id)arg1;
- (_Bool)canAddOutput:(id)arg1;
- (_Bool)canSetSessionPreset:(id)arg1;
- (void)commitConfiguration;
- (id)init;
@property(retain, nonatomic) NSMutableArray *inputs; // @synthesize inputs=_inputs;
- (_Bool)isRunning;
@property(retain, nonatomic) NSMutableArray *outputs; // @synthesize outputs=_outputs;
- (void)removeInput:(id)arg1;
- (void)removeOutput:(id)arg1;
@property(copy, nonatomic) NSString *sessionPreset; // @synthesize sessionPreset=_sessionPreset;
- (void)startRunning;
- (void)stopRunning;

@end

