//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class SCMossThumbnailMetadata, SCMossVideoMetadata;

@interface SCMossMediaVariantMetadata : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(readonly, nonatomic) int metadataOneOfCase; // @dynamic metadataOneOfCase;
@property(retain, nonatomic) SCMossThumbnailMetadata *thumbnailMetadata; // @dynamic thumbnailMetadata;
@property(retain, nonatomic) SCMossVideoMetadata *videoMetadata; // @dynamic videoMetadata;

@end

