//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCDataCoordinating-Protocol.h"

@class NSString, SCStoriesSnapViewerListInfo;

@protocol SCMyStoriesDataCoordinating <SCDataCoordinating>
- (void)fetchAllMyCustomStoriesWithCompletion:(void (^)(NSArray *))arg1;
- (void)fetchMyCustomStoryWithStoryId:(NSString *)arg1 completion:(void (^)(SCStoriesMyCustomStorySequence *))arg2;
- (void)fetchMyRegularStoriesWithCompletion:(void (^)(SCStoriesMyRegularStorySequence *))arg1;
- (SCStoriesSnapViewerListInfo *)viewerListInfoForStoryClientId:(NSString *)arg1 storyClusterId:(NSString *)arg2;
@end

