//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCNamedFriend-Protocol.h"

@class NSString;

@interface SCNamedFriendImpl : NSObject <SCNamedFriend>
{
    NSString *_name;
    NSString *_display;
    NSString *_userId;
    NSString *_bitmojiAvatarId;
    NSString *_bitmojiSelfieId;
}

- (void).cxx_destruct;
- (id)bitmojiAvatarId;
- (id)bitmojiSelfieId;
- (id)display;
- (_Bool)hasDisplay;
- (id)identifier;
- (id)initWithName:(id)arg1 display:(id)arg2 userId:(id)arg3 bitmojiAvatarId:(id)arg4 bitmojiSelfieId:(id)arg5;
- (id)name;
- (id)userId;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

