//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCNContentManagerContentManagerSupportInterfaces-Protocol.h"

@class NSDictionary, NSSet, NSString, SCFeatureSettingsManager, SCManagedDatastoreCollector, SCNGrapheneClientMetricsProcessor, SCQueuePerformer;
@protocol SCNContentManagerBlizzardLoggerInterface, SCNContentManagerInterimPayloadProcessor, SCNNetworkManagerNetworkManager, SCNShimsDataProviderFactory;

@interface SCNContentManagerContentManagerSupportInterfaces : NSObject <SCNContentManagerContentManagerSupportInterfaces>
{
    long long _cacheSizeLimitInMB;
    NSDictionary *_cacheManagers;
    NSDictionary *_oldCaches;
    id <SCNContentManagerInterimPayloadProcessor> _payloadProcessor;
    id <SCNNetworkManagerNetworkManager> _networkManager;
    SCNGrapheneClientMetricsProcessor *_clientMetricsProcessor;
    id <SCNShimsDataProviderFactory> _dataProviderFactory;
    NSDictionary *_isMediaContextUsingContentManagerMap;
    NSString *_dbLocation;
    NSSet *_streamingEnabledMediaContextTypeSet;
    SCFeatureSettingsManager *_featureSettingsManager;
    SCManagedDatastoreCollector *_managedDatastoreCollector;
    SCQueuePerformer *_queuePerformer;
    id <SCNContentManagerBlizzardLoggerInterface> _blizzardLogger;
    NSString *_userId;
    long long _initialChunkSizeInKBForStreaming;
    long long _cacheChunkSizeInKBForStreaming;
    _Bool _useListOfQueues;
    long long _numberOfQueuesPerMediaContextType;
    _Bool _unzipOnDownload;
    _Bool _shouldSaveAllContentStatesToDB;
}

- (void).cxx_destruct;
- (id)getBlizzardEventLogger;
- (long long)getCacheChunkSizeInKBForStreaming;
- (id)getCacheManagers;
- (long long)getCacheSizeLimitInMB;
- (id)getClientMetricsProcessor;
- (long long)getContentStateDeletionAgeInDays;
- (id)getDBLocation;
- (id)getDataProviderFactory;
- (long long)getInitialChunkSizeInKBForStreaming;
- (_Bool)getIsDataSaverModeEnabled;
- (id)getIsMediaContextUsingContentManagerMap;
- (_Bool)getIsUnzipOnDownloadEnabled;
- (id)getNetworkManager;
- (long long)getNumberOfQueuesPerMediaContextType;
- (id)getOldCaches;
- (id)getPayloadProcessor;
- (_Bool)getShouldSaveAllContentStatesToDB;
- (_Bool)getShouldUseMultipleQueuesPerMediaContextType;
- (id)getStreamingEnabledMediaContextTypeSet;
- (void)getUntrackedCaches:(id)arg1;
- (id)getUserId;
- (id)initWithCacheSizeLimit:(long long)arg1 withCacheManagers:(id)arg2 withOldCaches:(id)arg3 withPayloadProcessor:(id)arg4 withNetworkManager:(id)arg5 withClientMetricsProcessor:(id)arg6 withDataProviderFactory:(id)arg7 withIsMediaContextUsingContentManagerMap:(id)arg8 withDbLocation:(id)arg9 withStreamingEnabledMediaContextTypeSet:(id)arg10 withFeatureSettingsManager:(id)arg11 withManagedDatastoreCollector:(id)arg12 withBlizzardLogger:(id)arg13 withUserId:(id)arg14 initialChunkSizeInKBForStreaming:(long long)arg15 cacheChunkSizeInKBForStreaming:(long long)arg16 useListOfQueues:(_Bool)arg17 numberOfQueuesPerMediaContextType:(long long)arg18 unzipOnDownload:(_Bool)arg19 shouldSaveAllContentStatesToDB:(_Bool)arg20;
- (void)platformAssertFail:(id)arg1;

@end

