//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCNContentManagerContentResult-Protocol.h"

@class NSString, SCNContentManagerContentKey, SCNContentManagerContentRetrievalMetrics;
@protocol SCNContentManagerReadStream;

@interface SCNContentManagerContentResult : NSObject <SCNContentManagerContentResult>
{
    SCNContentManagerContentKey *_contentKey;
    long long _status;
    NSString *_statusMessage;
    id <SCNContentManagerReadStream> _readStream;
    SCNContentManagerContentRetrievalMetrics *_metrics;
    long long _errorReason;
    _Bool _isStreaming;
    _Bool _isZipArchive;
}

- (void).cxx_destruct;
- (void)cancelWriteStreamRequest:(id)arg1;
- (id)createReadStream;
- (void)free;
- (id)getContentKey;
- (long long)getErrorReason;
- (_Bool)getIsStreaming;
- (_Bool)getIsZipArchive;
- (id)getMetrics;
- (id)getNetworkStats;
- (long long)getStatus;
- (id)getStatusMessage;
- (long long)getTotalSize;
- (id)getZipEntryData:(id)arg1;
- (id)initWithContentKey:(id)arg1 status:(long long)arg2 statusMessage:(id)arg3 readStream:(id)arg4 isStreaming:(_Bool)arg5 isZipArchive:(_Bool)arg6 metrics:(id)arg7 errorReason:(long long)arg8;
- (id)pushBytesToWriteStream:(id)arg1 start:(long long)arg2 count:(long long)arg3;

@end

