//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol SCImageDownloading;

@interface SCNetworkImageServices : NSObject
{
    id <SCImageDownloading> _imageDownloader;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) id <SCImageDownloading> imageDownloader; // @synthesize imageDownloader=_imageDownloader;
- (id)initWithImageDownloader:(id)arg1;

@end

