//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCDownloadableContent.h"

@class NSArray, NSString;

@interface SCNotificationSoundsDownloadableContent : SCDownloadableContent
{
    NSString *_folderName;
    NSArray *_fileNameList;
}

- (void).cxx_destruct;
- (id)directoryName;
- (id)eventUniqueId;
- (id)fileNames;
- (id)initWithSoundsFolderName:(id)arg1 fileNameList:(id)arg2;
- (id)pathForResource:(id)arg1;
- (id)resourceName;

@end

