//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCOnDemandGeofilterBaseLeftSwipableViewController.h"

#import "SCHeaderDataSource-Protocol.h"
#import "SCHeaderDelegate-Protocol.h"
#import "SCOnDemandGeofilterCollectionViewCellDelegate-Protocol.h"
#import "SCOnDemandGeofilterDataControllerListener-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"

@class NSIndexPath, NSString, SCHeader, SCOnDemandGeofilterBlurredBackgroundView, SCOnDemandGeofilterCollectionViewLayout, SCOnDemandGeofilterDraftsEmptyStateView, SOJUUnlockablesOndemandAssetDraftList, SOJUUnlockablesOndemandTemplateCategory, UICollectionView, UIImageView;
@protocol SCOnDemandGeofilterSessionProtocol;

@interface SCOnDemandGeofilterTemplatesViewController : SCOnDemandGeofilterBaseLeftSwipableViewController <SCHeaderDataSource, SCHeaderDelegate, UICollectionViewDelegate, UICollectionViewDataSource, SCOnDemandGeofilterDataControllerListener, SCOnDemandGeofilterCollectionViewCellDelegate>
{
    id <SCOnDemandGeofilterSessionProtocol> _geofilterSession;
    SOJUUnlockablesOndemandTemplateCategory *_category;
    SOJUUnlockablesOndemandAssetDraftList *_assetDraftList;
    SCOnDemandGeofilterBlurredBackgroundView *_blurredBackgroundView;
    SCHeader *_header;
    UIImageView *_headerBGImageView;
    UICollectionView *_geofiltersCollectionView;
    NSIndexPath *_selectedIndexPath;
    SCOnDemandGeofilterCollectionViewLayout *_layout;
    unsigned long long _layoutType;
    unsigned long long _pickerType;
    SCOnDemandGeofilterDraftsEmptyStateView *_draftsEmptyStateView;
    _Bool _fromReviewView;
}

- (void).cxx_destruct;
- (void)_deleteAssetDraft:(id)arg1;
- (void)_presentDeleteActionSheet:(id)arg1;
- (void)_reloadDraftsCollectionView;
- (id)backgroundColorForHeader;
- (void)beginCellMoving:(id)arg1 forCell:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)dataController:(id)arg1 didFetchAssetDraftList:(id)arg2 success:(_Bool)arg3;
- (id)filterBitmojiTemplates:(id)arg1;
- (id)filterBitmojiTemplatesIfBitmojiAbsent:(id)arg1;
@property(nonatomic) _Bool fromReviewView; // @synthesize fromReviewView=_fromReviewView;
- (void)geofilterCellLoaded:(_Bool)arg1;
- (id)imageForLeftButtonInState:(unsigned long long)arg1;
- (id)imageForRightButtonInState:(unsigned long long)arg1;
- (id)initWithAssetDraftList:(id)arg1 andGeofilterSession:(id)arg2;
- (id)initWithTemplateCategory:(id)arg1 andGeofilterSession:(id)arg2;
- (void)leftButtonPressed;
- (void)leftSwipeSucceed;
- (void)scrollViewDidScroll:(id)arg1;
- (id)textColorForHeader:(id)arg1;
- (id)titleForHeader:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

