//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCOperaLayerViewController.h"

#import "SCMotionManagerListener-Protocol.h"
#import "SCOperaFadeTransitionCompatibleViewController-Protocol.h"
#import "SCOperaLayerViewControllerMediaContainer-Protocol.h"
#import "SCOperaPinchGestureCompatibleViewController-Protocol.h"
#import "SCOperaRotatingLayerPinchControllerDelegate-Protocol.h"

@class NSNotificationCenter, NSString, SCCAEAGLView, SCFrameableContainerView, SCImageProcessColorFilterSession, SCOperaGLVideoLayerView, SCOperaRotatingLayerPinchController, SCOperaRotatingViewTransformManipulator, UIImage, UIView;

@interface SCOperaGLImageLayerViewController : SCOperaLayerViewController <SCOperaRotatingLayerPinchControllerDelegate, SCMotionManagerListener, SCOperaLayerViewControllerMediaContainer, SCOperaFadeTransitionCompatibleViewController, SCOperaPinchGestureCompatibleViewController>
{
    SCOperaGLVideoLayerView *_layerView;
    SCOperaRotatingViewTransformManipulator *_rotatingViewManipulator;
    SCFrameableContainerView *_containerView;
    SCCAEAGLView *_glView;
    NSNotificationCenter *_notificationCenter;
    UIImage *_imageAsset;
    _Bool _isRotatingImageLayout;
    _Bool _isListeningForMotionUpdates;
    SCImageProcessColorFilterSession *_imageProcessPixelSession;
    SCOperaRotatingLayerPinchController *_pinchController;
    _Bool _shouldRestoreToOppositeState;
    _Bool _hasFullyAppearedOnScreen;
    _Bool _playbackStarted;
    UIView *_pinchGestureTarget;
}

- (void).cxx_destruct;
- (struct CGSize)_contentSize;
- (id)_glCommandsForKey:(id)arg1;
- (void)_handlePinchScaleSuppressionUpdate:(_Bool)arg1;
- (void)_listenToMotionManagerIfNecessary;
- (void)_resetHorizontalPageOffset;
- (void)_resetTrackingParams;
- (struct CGAffineTransform)_rotateTransform;
- (void)_setupImageProcessSessionIfNecessary;
- (void)_setupPinchController;
- (void)_startPlaybackIfNecessary;
- (void)_stopListenToMotionManagerIfNecessary;
- (void)_stopPlaybackIfNecessary;
- (void)_updateImageProcessSessionWithPreviousLayer:(id)arg1 currentLayer:(id)arg2;
- (void)_updateLayerLayout:(_Bool)arg1;
- (id)currentViewParameters;
- (void)didReceiveUpdateProperties:(id)arg1;
- (void)didUpdateRotation:(double)arg1 translation:(struct CGVector)arg2;
- (id)fadingViewsForFadeTransition;
- (id)initWithConfiguration:(id)arg1 eventAnnouncer:(id)arg2 sharedResourceManager:(id)arg3;
- (id)initWithConfiguration:(id)arg1 eventAnnouncer:(id)arg2 sharedResourceManager:(id)arg3 notificationCenter:(id)arg4;
- (_Bool)isOverlay;
- (void)loadView;
- (double)mediaHeightToWidthAspectRatio;
- (struct CGRect)mediaViewFrame;
- (id)movingViewsForFadeTransition;
- (long long)pageabilityForRelativePosition:(unsigned long long)arg1 gestureRecognizer:(id)arg2;
- (void)pinchControllerDidFinishPinch:(double)arg1;
- (void)pinchControllerRequestsTransformUpdate:(double)arg1;
@property(nonatomic) __weak UIView *pinchGestureTarget; // @synthesize pinchGestureTarget=_pinchGestureTarget;
- (void)teardown;
- (void)updateViewWithHorizontalPageOffset:(double)arg1 isCurrentPage:(_Bool)arg2;
- (void)updateViewWithPreviousLayer:(id)arg1 currentLayer:(id)arg2;
- (void)viewDidFullyAppear;
- (void)viewDidFullyDisappear;
- (void)viewWillFullyAppear;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

