//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "SCOperaLayerView-Protocol.h"
#import "SCOperaUpNextCollectionViewCellDelegate-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegateFlowLayout-Protocol.h"

@class NSArray, NSMutableDictionary, NSString, SCOperaUpNextCollectionViewLayout, SCOperaUpNextHighlightBarView, UICollectionView;
@protocol SCImageDownloading;

@interface SCOperaUpNextLayerView : UIView <SCOperaUpNextCollectionViewCellDelegate, UICollectionViewDelegateFlowLayout, UICollectionViewDataSource, SCOperaLayerView>
{
    SCOperaUpNextCollectionViewLayout *_upNextCollectionViewLayout;
    UICollectionView *_upNextCollectionView;
    SCOperaUpNextHighlightBarView *_upNextHighlightBarView;
    NSMutableDictionary *_collectionViewCellSizes;
    NSArray *_upNextGroupViewModels;
    id <SCImageDownloading> _imageDownloader;
    long long _currentIndex;
    long long _activeState;
}

+ (id)layerViewWithFrame:(struct CGRect)arg1;
- (void).cxx_destruct;
- (id)_cellAtIndex:(long long)arg1;
- (void)_hideIfNecessary;
- (double)_horizontalContentOffsetForIndex:(long long)arg1;
- (void)_scrollIfNecessary;
- (void)_setupViews;
- (struct CGSize)_sizeForCellAtIndex:(long long)arg1;
- (void)_updateCollectionViewActiveState:(long long)arg1 animated:(_Bool)arg2;
- (void)_updateCollectionViewFocusStateAnimated:(_Bool)arg1;
@property(nonatomic) long long activeState; // @synthesize activeState=_activeState;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
@property(nonatomic) long long currentIndex; // @synthesize currentIndex=_currentIndex;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
@property(retain, nonatomic) id <SCImageDownloading> imageDownloader; // @synthesize imageDownloader=_imageDownloader;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)setActiveState:(long long)arg1 animated:(_Bool)arg2;
- (void)setCurrentIndex:(long long)arg1 scroll:(_Bool)arg2;
@property(retain, nonatomic) NSArray *upNextGroupViewModels; // @synthesize upNextGroupViewModels=_upNextGroupViewModels;
- (void)setVisible:(_Bool)arg1 animationDuration:(double)arg2;
- (void)upNextCollectionViewCell:(id)arg1 wantsDesiredSize:(struct CGSize)arg2;
- (void)updateViewWithRelativeHorizontalContentOffset:(double)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

