//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCOperaLayerViewController.h"

#import "SCOperaEventListener-Protocol.h"

@class NSString, SCFrameableContainerView, SCOperaStoryProgressIndicatorLayerView;

@interface SCOperaStoryProgressIndicatorLayerViewController : SCOperaLayerViewController <SCOperaEventListener>
{
    SCOperaStoryProgressIndicatorLayerView *_layerView;
    SCFrameableContainerView *_containerView;
    _Bool _didObservePageTap;
}

- (void).cxx_destruct;
- (id)initWithConfiguration:(id)arg1 eventAnnouncer:(id)arg2 sharedResourceManager:(id)arg3;
- (void)loadView;
- (void)operaViewDidSendEvent:(id)arg1 context:(id)arg2 params:(id)arg3;
- (void)updateViewWithPreviousLayer:(id)arg1 currentLayer:(id)arg2;
- (void)viewDidLayoutSubviews;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

