//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class UIBezierPath, UIView;

@interface SCOperaRotatingViewTransformManipulator : NSObject
{
    UIView *_targetView;
    double _lastScale;
    double _lastRotation;
    UIBezierPath *_maskBezierPath;
    double _minRollDegree;
    double _maxRollDegree;
}

- (void).cxx_destruct;
- (void)_updateMaxAndMinRollDegree;
- (void)applyCircularMaskWithDiameter:(double)arg1 xOffset:(double)arg2 yOffset:(double)arg3;
- (id)initWithTargetView:(id)arg1;
@property(readonly, nonatomic) double maxRollDegree; // @synthesize maxRollDegree=_maxRollDegree;
@property(readonly, nonatomic) double minRollDegree; // @synthesize minRollDegree=_minRollDegree;
- (void)removeCircularMask;
- (void)resetTargetViewTransform;
- (void)resetTrackingParams;
- (void)updateTargetViewWithPinchScale:(double)arg1;
- (void)updateTargetViewWitheRotation:(double)arg1;

@end

