//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSString;

@interface SCOpenAddFriendsActionData : NSObject <NSCopying>
{
    NSString *_destinationTab;
    long long _placement;
}

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, copy, nonatomic) NSString *destinationTab; // @synthesize destinationTab=_destinationTab;
- (unsigned long long)hash;
- (id)initWithDestinationTab:(id)arg1 placement:(long long)arg2;
- (_Bool)isEqual:(id)arg1;
@property(readonly, nonatomic) long long placement; // @synthesize placement=_placement;

@end

