//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCOperaLayer-Protocol.h"

@class NSString, SCOperaPage;

@interface SCOperaArrowLayer : NSObject <SCOperaLayer>
{
    _Bool _hasGradient;
    SCOperaPage *_page;
    unsigned long long _direction;
    double _opacity;
    NSString *_text;
    double _liveAreaPercentXInset;
    double _liveAreaPercentYInset;
}

+ (id)layerWithProperties:(id)arg1 page:(id)arg2;
- (void).cxx_destruct;
@property(readonly, nonatomic) unsigned long long direction; // @synthesize direction=_direction;
@property(readonly, nonatomic) _Bool hasGradient; // @synthesize hasGradient=_hasGradient;
- (id)initWithProperties:(id)arg1 page:(id)arg2;
- (_Bool)isEqual:(id)arg1;
@property(readonly, nonatomic) double liveAreaPercentXInset; // @synthesize liveAreaPercentXInset=_liveAreaPercentXInset;
@property(readonly, nonatomic) double liveAreaPercentYInset; // @synthesize liveAreaPercentYInset=_liveAreaPercentYInset;
@property(readonly, nonatomic) double opacity; // @synthesize opacity=_opacity;
@property(nonatomic) __weak SCOperaPage *page; // @synthesize page=_page;
@property(readonly, copy, nonatomic) NSString *text; // @synthesize text=_text;
- (unsigned long long)type;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

