//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCOperaLayerViewController.h"

#import "SCOperaBlockingViewController-Protocol.h"

@class NSString, SCOperaGestureToolTipsLayerView;
@protocol SCOperaBlockingViewControllerDelegate;

@interface SCOperaGestureToolTipsLayerViewController : SCOperaLayerViewController <SCOperaBlockingViewController>
{
    SCOperaGestureToolTipsLayerView *_layerView;
    _Bool _isDismissing;
    id <SCOperaBlockingViewControllerDelegate> _blockingViewControllerDelegate;
}

- (void).cxx_destruct;
- (void)_didUpdateSubviewsVisible:(_Bool)arg1;
@property(nonatomic) __weak id <SCOperaBlockingViewControllerDelegate> blockingViewControllerDelegate; // @synthesize blockingViewControllerDelegate=_blockingViewControllerDelegate;
- (void)didTryPagingWhenPagingDisabled;
- (_Bool)isBeingDismissed;
- (_Bool)isBlocking;
- (_Bool)isRecyclable;
- (void)loadView;
- (long long)pageabilityForRelativePosition:(unsigned long long)arg1 gestureRecognizer:(id)arg2;
- (_Bool)shouldBlockOtherLayersFromDisplayingWithCurrentPage:(id)arg1;
- (void)updateViewWithPreviousLayer:(id)arg1 currentLayer:(id)arg2;
- (void)viewDidFullyAppear;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

