//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class SCUserSession, UILabel;

@interface SCPermissionSettingsTableViewCell : UITableViewCell
{
    SCUserSession *_userSession;
    UILabel *_title;
    UILabel *_explanation;
    UILabel *_permissionIndicator;
}

+ (id)getPermissionExplanationText:(long long)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *explanation; // @synthesize explanation=_explanation;
- (id)initWithReuseIdentifier:(id)arg1 userSession:(id)arg2;
- (id)permissionExplanationLabel;
@property(retain, nonatomic) UILabel *permissionIndicator; // @synthesize permissionIndicator=_permissionIndicator;
- (id)permissionIndicatorLabel;
- (id)permissionTitleLabel;
- (void)setPermissionIndicatorText:(long long)arg1;
- (void)setPermissionTitleText:(long long)arg1;
- (void)setPermissionType:(long long)arg1;
@property(retain, nonatomic) UILabel *title; // @synthesize title=_title;

@end

