//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SCPreviewSnapSaver : NSObject
{
}

+ (id)shared;
+ (void)showPhotoAccessDeniedAlertView:(_Bool)arg1;
- (void)_saveImage:(id)arg1 loggingParameters:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_saveImageSnapWithPreview:(id)arg1 loggingParameters:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_saveVideo:(id)arg1 loggingParameters:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_saveVideoSnapWithPreview:(id)arg1 loggingParameters:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)saveSnapToSnapAlbumWithPreview:(id)arg1 loggingParameters:(id)arg2 completion:(CDUnknownBlockType)arg3;

@end

