//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "SCHeaderDataSource-Protocol.h"

@class NSString, SCHeader, SCPrivacyPolicyContentScrollView, UIButton;

@interface SCPrivacyPolicyView : UIView <SCHeaderDataSource>
{
    SCHeader *_header;
    SCPrivacyPolicyContentScrollView *_contentScrollView;
    UIButton *_okButton;
}

- (void).cxx_destruct;
- (void)_initContentScrollViewWithLinkDelegate:(id)arg1;
- (void)_initHeaderWithDelegate:(id)arg1;
- (void)_initOKButtonWithTarget:(id)arg1 selector:(SEL)arg2;
- (id)backgroundColorForHeader;
- (id)imageForLeftButtonInState:(unsigned long long)arg1;
- (id)imageForRightButtonInState:(unsigned long long)arg1;
- (id)initWithFrame:(struct CGRect)arg1 headerDelegate:(id)arg2 dismissActionDelegate:(id)arg3 linkDelegate:(id)arg4;
- (id)textColorForHeader:(id)arg1;
- (id)titleForHeader:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

