//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSArray, NSString;

@interface SCPrivateStoriesExistingStoryInfo : NSObject <NSCopying>
{
    NSString *_storyIdentifier;
    NSString *_storyName;
    NSArray *_viewerIdsPermitted;
}

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)hash;
- (id)initWithStoryIdentifier:(id)arg1 storyName:(id)arg2 viewerIdsPermitted:(id)arg3;
- (_Bool)isEqual:(id)arg1;
@property(readonly, copy, nonatomic) NSString *storyIdentifier; // @synthesize storyIdentifier=_storyIdentifier;
@property(readonly, copy, nonatomic) NSString *storyName; // @synthesize storyName=_storyName;
@property(readonly, copy, nonatomic) NSArray *viewerIdsPermitted; // @synthesize viewerIdsPermitted=_viewerIdsPermitted;

@end

