//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCFeature.h"

#import "SCPreviewFeatureMuteSwitch-Protocol.h"

@class SCLabeledGrowingButton, SCPreviewConfiguration, SCPreviewView;
@protocol SCPreviewFeatureMuteSwitchDelegate;

@interface SCPreviewFeatureMuteSwitchImpl : SCFeature <SCPreviewFeatureMuteSwitch>
{
    SCPreviewView *_previewView;
    SCPreviewConfiguration *_configuration;
    SCLabeledGrowingButton *_button;
    _Bool _needsHintLabel;
    id <SCPreviewFeatureMuteSwitchDelegate> _delegate;
}

- (void).cxx_destruct;
- (void)_buttonPressed;
- (void)_setupHintLabel;
@property(readonly, nonatomic) SCLabeledGrowingButton *button;
- (void)configureWithView:(id)arg1;
@property(nonatomic) __weak id <SCPreviewFeatureMuteSwitchDelegate> delegate; // @synthesize delegate=_delegate;
- (id)initWithPreviewConfiguration:(id)arg1;
@property(nonatomic) _Bool needsHintLabel; // @synthesize needsHintLabel=_needsHintLabel;
- (void)setUIEnabled:(_Bool)arg1;

@end

