//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class Story;

@interface SCProfileHeaderViewStoryConfiguration : NSObject <NSCopying>
{
    _Bool _isMyStory;
    _Bool _isSharedStory;
    _Bool _showProgress;
    Story *_story;
}

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (unsigned long long)hash;
- (id)initWithStory:(id)arg1 isMyStory:(_Bool)arg2 isSharedStory:(_Bool)arg3 showProgress:(_Bool)arg4;
- (_Bool)isEqual:(id)arg1;
@property(readonly, nonatomic) _Bool isMyStory; // @synthesize isMyStory=_isMyStory;
@property(readonly, nonatomic) _Bool isSharedStory; // @synthesize isSharedStory=_isSharedStory;
@property(readonly, nonatomic) _Bool showProgress; // @synthesize showProgress=_showProgress;
@property(readonly, copy, nonatomic) Story *story; // @synthesize story=_story;

@end

