//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSString, SCAvatarCircleBackgroundViewModel, SCBitmojiAvatarViewModel, SCProfileHeaderViewStoryConfiguration, SCStoryRingViewModel;

@interface SCProfileHeaderViewConfiguration : NSObject <NSCopying>
{
    _Bool _forceShowBitmoji;
    NSString *_username;
    SCBitmojiAvatarViewModel *_bitmojiAvatarViewModel;
    SCAvatarCircleBackgroundViewModel *_backgroundViewModel;
    SCStoryRingViewModel *_ringViewModel;
    SCProfileHeaderViewStoryConfiguration *_storyConfiguration;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) SCAvatarCircleBackgroundViewModel *backgroundViewModel; // @synthesize backgroundViewModel=_backgroundViewModel;
@property(readonly, copy, nonatomic) SCBitmojiAvatarViewModel *bitmojiAvatarViewModel; // @synthesize bitmojiAvatarViewModel=_bitmojiAvatarViewModel;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
@property(readonly, nonatomic) _Bool forceShowBitmoji; // @synthesize forceShowBitmoji=_forceShowBitmoji;
- (unsigned long long)hash;
- (id)initWithUsername:(id)arg1 forceShowBitmoji:(_Bool)arg2 bitmojiAvatarViewModel:(id)arg3 backgroundViewModel:(id)arg4 ringViewModel:(id)arg5 storyConfiguration:(id)arg6;
- (_Bool)isEqual:(id)arg1;
@property(readonly, copy, nonatomic) SCStoryRingViewModel *ringViewModel; // @synthesize ringViewModel=_ringViewModel;
@property(readonly, copy, nonatomic) SCProfileHeaderViewStoryConfiguration *storyConfiguration; // @synthesize storyConfiguration=_storyConfiguration;
@property(readonly, copy, nonatomic) NSString *username; // @synthesize username=_username;

@end

