//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCEventListener-Protocol.h"
#import "SCUnifiedActionMenuDataProvider-Protocol.h"

@class NSString, SCCheetahPublicUserStory, SCDiscoverFeedActionSheetNotificationStatusManager, SCDiscoverFeedActionSheetSubscribeStatusManager, SCScopedAccess;
@protocol SCUnifiedActionMenuDataProviderDelegate;

@interface SCPublicUserActionSheetDataProvider : NSObject <SCEventListener, SCUnifiedActionMenuDataProvider>
{
    SCCheetahPublicUserStory *_publicUserStory;
    unsigned long long _storyDedupeFp;
    SCDiscoverFeedActionSheetSubscribeStatusManager *_subscribeStatusManager;
    SCDiscoverFeedActionSheetNotificationStatusManager *_notificationStatusManager;
    SCScopedAccess *_snapchattersDataFetcher;
    unsigned long long _subscribeState;
    unsigned long long _notificationState;
    id <SCUnifiedActionMenuDataProviderDelegate> _delegate;
}

- (void).cxx_destruct;
- (id)_actionSheetViewModelForSnapchatter:(id)arg1;
- (void)_convertSnapchatterFromStoryWithCompletionBlock:(CDUnknownBlockType)arg1;
- (void)_fetchSnapchatterWithCompletionBlock:(CDUnknownBlockType)arg1;
- (void)_notificationStateDidUpdateForStoryDedupeFp:(id)arg1;
- (void)_subscribeStateDidUpdateForStoryDedupeFp:(id)arg1;
- (void)dealloc;
@property(nonatomic) __weak id <SCUnifiedActionMenuDataProviderDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didTriggerEventWithEventName:(id)arg1 announcerIdentifier:(id)arg2 extraData:(id)arg3;
- (id)initWithPublicUserStory:(id)arg1 storyDedupeFp:(unsigned long long)arg2 subscribeStatusManager:(id)arg3 notificationStatusManager:(id)arg4;
- (void)reload;
- (void)updateViewModelWithCompletionBlock:(CDUnknownBlockType)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

