//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class CLLocation, NSArray, NSDate, NSString;

@interface SCRankingAutoSuggestCache : NSObject
{
    _Bool _prefetch;
    NSString *_keyword;
    NSArray *_suggestions;
    NSDate *_cacheDate;
    CLLocation *_location;
}

+ (id)cacheKeyForKeyword:(id)arg1;
+ (id)cacheWithKeyword:(id)arg1 suggestions:(id)arg2 location:(id)arg3;
- (void).cxx_destruct;
@property(retain, nonatomic) NSDate *cacheDate; // @synthesize cacheDate=_cacheDate;
- (_Bool)isValid:(id)arg1;
@property(retain, nonatomic) NSString *keyword; // @synthesize keyword=_keyword;
@property(retain, nonatomic) CLLocation *location; // @synthesize location=_location;
@property(nonatomic) _Bool prefetch; // @synthesize prefetch=_prefetch;
@property(retain, nonatomic) NSArray *suggestions; // @synthesize suggestions=_suggestions;

@end

