//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCNetworkReconnectListener-Protocol.h"

@class NSFileManager, NSMutableDictionary, NSMutableSet, NSString, NSURL, SCQueuePerformer, SCUserSession;

@interface SCRequestQueue : NSObject <SCNetworkReconnectListener>
{
    SCUserSession *_userSession;
    SCQueuePerformer *_performer;
    NSURL *_folderURL;
    NSFileManager *_fileManager;
    NSMutableDictionary *_contentIdToPendingQueueItem;
    NSMutableDictionary *_contentIdToObserverIdToCallbackMap;
    NSMutableDictionary *_contentIdToUnexpiredSuccessQueueItems;
    NSMutableSet *_contentIdsWithPendingNetworkRequests;
}

- (void).cxx_destruct;
- (void)_addCallbackToMapWithContentId:(id)arg1 observerId:(id)arg2 callback:(id)arg3;
- (void)_cancelRequestWithContentId:(id)arg1;
- (id)_contentIdFromRequestId:(id)arg1;
- (id)_contentIdFromRequestIdentifier:(id)arg1;
- (void)_createFoldersIfNeeded;
- (void)_deletePendingItem:(id)arg1;
- (void)_deletePendingItemAndPersistSuccessResult:(id)arg1;
- (void)_loadValidItemsFromDisk;
- (_Bool)_persistPendingQueueItemWithContentId:(id)arg1;
- (_Bool)_persistSuccessQueueItems;
- (void)_registerSubscriptionWithContentId:(id)arg1 observerId:(id)arg2 callbackPerformer:(id)arg3 statusBlock:(CDUnknownBlockType)arg4;
- (void)_retryPendingRequests;
- (void)_submitNetworkRequestWithContentId:(id)arg1;
- (void)cancelRequestWithContentId:(id)arg1;
- (void)cancelRequestWithRequestId:(id)arg1;
- (void)cancelSubscriptionWithObserverId:(id)arg1 contentId:(id)arg2;
- (void)didReconnectToNetwork;
- (void)enqueueRequestWithSchema:(id)arg1 callbackPerformer:(id)arg2 enqueueResultBlock:(CDUnknownBlockType)arg3;
- (id)initWithFolderURL:(id)arg1 userSession:(id)arg2;
- (id)subscribeToUpdateOnContentId:(id)arg1 callbackPerformer:(id)arg2 statusBlock:(CDUnknownBlockType)arg3;
- (id)subscribeToUpdateOnRequestIdentifier:(id)arg1 callbackPerformer:(id)arg2 statusBlock:(CDUnknownBlockType)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

