//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class SCActionModel, SCSettingViewModel, UIColor;

@interface SCSettingViewCellViewModel : NSObject <NSCopying>
{
    SCSettingViewModel *_settingViewModel;
    SCActionModel *_longPressActionModel;
    UIColor *_backgroundColor;
    unsigned long long _roundedCorners;
    double _cornerRadius;
    UIColor *_borderColor;
    double _borderWidth;
    struct CGSize _preferredSize;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(readonly, copy, nonatomic) UIColor *borderColor; // @synthesize borderColor=_borderColor;
@property(readonly, nonatomic) double borderWidth; // @synthesize borderWidth=_borderWidth;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, nonatomic) double cornerRadius; // @synthesize cornerRadius=_cornerRadius;
- (unsigned long long)hash;
- (id)initWithSettingViewModel:(id)arg1 longPressActionModel:(id)arg2 preferredSize:(struct CGSize)arg3 backgroundColor:(id)arg4 roundedCorners:(unsigned long long)arg5 cornerRadius:(double)arg6 borderColor:(id)arg7 borderWidth:(double)arg8;
- (_Bool)isEqual:(id)arg1;
@property(readonly, copy, nonatomic) SCActionModel *longPressActionModel; // @synthesize longPressActionModel=_longPressActionModel;
@property(readonly, nonatomic) struct CGSize preferredSize; // @synthesize preferredSize=_preferredSize;
@property(readonly, nonatomic) unsigned long long roundedCorners; // @synthesize roundedCorners=_roundedCorners;
@property(readonly, copy, nonatomic) SCSettingViewModel *settingViewModel; // @synthesize settingViewModel=_settingViewModel;

@end

