//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSDate, NSString, SCSearchFormsPickerConfiguration;

@interface SCSearchFormsField : NSObject <NSCopying>
{
    unsigned long long _subtype;
    NSString *_textEntryField_titleText;
    NSString *_textEntryField_prefilledText;
    _Bool _textEntryField_canEdit;
    _Bool _textEntryField_isNumber;
    SCSearchFormsPickerConfiguration *_pickerField_pickerConfig;
    _Bool _pickerField_canSelect;
    NSString *_onOffSwitch_titleText;
    _Bool _onOffSwitch_canSwitch;
    _Bool _onOffSwitch_preselectedValue;
    NSString *_datePickerField_titleText;
    NSDate *_datePickerField_preselectedDate;
}

+ (id)datePickerFieldWithTitleText:(id)arg1 preselectedDate:(id)arg2;
+ (id)onOffSwitchWithTitleText:(id)arg1 canSwitch:(_Bool)arg2 preselectedValue:(_Bool)arg3;
+ (id)pickerFieldWithPickerConfig:(id)arg1 canSelect:(_Bool)arg2;
+ (id)textEntryFieldWithTitleText:(id)arg1 prefilledText:(id)arg2 canEdit:(_Bool)arg3 isNumber:(_Bool)arg4;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)hash;
- (id)internalInit;
- (_Bool)isEqual:(id)arg1;
- (void)matchTextEntryField:(CDUnknownBlockType)arg1 pickerField:(CDUnknownBlockType)arg2 onOffSwitch:(CDUnknownBlockType)arg3 datePickerField:(CDUnknownBlockType)arg4;

@end

