//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSArray, NSString, SCSearchQuery;

@interface SCSearchDiscoverStoriesSectionDataModel : NSObject <NSCopying>
{
    SCSearchQuery *_searchQuery;
    NSArray *_discoverStories;
    NSString *_resultContentIdentifier;
}

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, copy, nonatomic) NSArray *discoverStories; // @synthesize discoverStories=_discoverStories;
- (unsigned long long)hash;
- (id)initWithSearchQuery:(id)arg1 discoverStories:(id)arg2 resultContentIdentifier:(id)arg3;
- (_Bool)isEqual:(id)arg1;
@property(readonly, copy, nonatomic) NSString *resultContentIdentifier; // @synthesize resultContentIdentifier=_resultContentIdentifier;
@property(readonly, copy, nonatomic) SCSearchQuery *searchQuery; // @synthesize searchQuery=_searchQuery;

@end

