//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"
#import "NSObject-Protocol.h"

@class NSArray, NSString, UIImage;

@protocol SCSearchStoryRatingViewConfiguration <NSObject, NSCoding, NSCopying>
@property(readonly, copy, nonatomic) NSArray *flagLoggingKeys;
@property(readonly, copy, nonatomic) NSArray *flagTexts;
@property(readonly, copy, nonatomic) NSString *queryText;
@property(readonly, copy, nonatomic) NSArray *questionsConfiguration;
@property(readonly, copy, nonatomic) NSArray *ratingLoggingKeys;
@property(readonly, copy, nonatomic) UIImage *screenshot;
@property(readonly, nonatomic) long long style;
@property(readonly, copy, nonatomic) NSString *title;
@end

