//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSDictionary, NSNumber, NSString, SCSearchDynamicStory;

@interface SCSearchSportsGame : NSObject <NSCopying>
{
    SCSearchDynamicStory *_dynamicStory;
    NSString *_homeTeam;
    NSString *_awayTeam;
    NSNumber *_homeTeamScore;
    NSNumber *_awayTeamScore;
    NSString *_homeImageUrl;
    NSString *_awayImageUrl;
    NSString *_gameStatus;
    NSDictionary *_debugInfo;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *awayImageUrl; // @synthesize awayImageUrl=_awayImageUrl;
@property(readonly, copy, nonatomic) NSString *awayTeam; // @synthesize awayTeam=_awayTeam;
@property(readonly, copy, nonatomic) NSNumber *awayTeamScore; // @synthesize awayTeamScore=_awayTeamScore;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, copy, nonatomic) NSDictionary *debugInfo; // @synthesize debugInfo=_debugInfo;
@property(readonly, copy, nonatomic) SCSearchDynamicStory *dynamicStory; // @synthesize dynamicStory=_dynamicStory;
@property(readonly, copy, nonatomic) NSString *gameStatus; // @synthesize gameStatus=_gameStatus;
- (unsigned long long)hash;
@property(readonly, copy, nonatomic) NSString *homeImageUrl; // @synthesize homeImageUrl=_homeImageUrl;
@property(readonly, copy, nonatomic) NSString *homeTeam; // @synthesize homeTeam=_homeTeam;
@property(readonly, copy, nonatomic) NSNumber *homeTeamScore; // @synthesize homeTeamScore=_homeTeamScore;
- (id)initWithDynamicStory:(id)arg1 homeTeam:(id)arg2 awayTeam:(id)arg3 homeTeamScore:(id)arg4 awayTeamScore:(id)arg5 homeImageUrl:(id)arg6 awayImageUrl:(id)arg7 gameStatus:(id)arg8 debugInfo:(id)arg9;
- (_Bool)isEqual:(id)arg1;

@end

