//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSString, SCSearchQuery;

@interface SCSearchSpellCorrectionSectionDataModel : NSObject <NSCopying>
{
    SCSearchQuery *_searchQuery;
    NSString *_spellCorrectedQueryText;
    NSString *_escapeHatchQueryText;
}

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, copy, nonatomic) NSString *escapeHatchQueryText; // @synthesize escapeHatchQueryText=_escapeHatchQueryText;
- (unsigned long long)hash;
- (id)initWithSearchQuery:(id)arg1 spellCorrectedQueryText:(id)arg2 escapeHatchQueryText:(id)arg3;
- (_Bool)isEqual:(id)arg1;
@property(readonly, copy, nonatomic) SCSearchQuery *searchQuery; // @synthesize searchQuery=_searchQuery;
@property(readonly, copy, nonatomic) NSString *spellCorrectedQueryText; // @synthesize spellCorrectedQueryText=_spellCorrectedQueryText;

@end

