//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSString, UITableView, UITapGestureRecognizer;
@protocol SCSearchFormsPickerViewDelegate;

@interface SCSearchFormsPickerView : UIView <UIGestureRecognizerDelegate>
{
    UITableView *_pickerView;
    UITapGestureRecognizer *_tapGestureRecognizer;
    double _presentationOffset;
    struct CGRect _currentMaskRect;
    id <SCSearchFormsPickerViewDelegate> _delegate;
}

- (void).cxx_destruct;
- (void)_didTap:(id)arg1;
- (void)animateDismissal;
- (void)animatePresentation;
@property(nonatomic) __weak id <SCSearchFormsPickerViewDelegate> delegate; // @synthesize delegate=_delegate;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (id)initWithPicker:(id)arg1;
- (void)layoutSubviews;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

