//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCExperimentContext.h"

@interface SCSearchSendToCellExperimentContext : SCExperimentContext
{
    _Bool _shouldEnableSendToCell;
    double _sendToCellCacheLengthMinutes;
}

- (id)experimentName;
@property(readonly, nonatomic) double sendToCellCacheLengthMinutes; // @synthesize sendToCellCacheLengthMinutes=_sendToCellCacheLengthMinutes;
- (void)setupParameters;
@property(readonly, nonatomic) _Bool shouldEnableSendToCell; // @synthesize shouldEnableSendToCell=_shouldEnableSendToCell;

@end

