//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"
#import "SCComposerJsConvertible-Protocol.h"

@class NSString;

@interface SCSearchV2Configuration : NSObject <SCComposerJsConvertible, NSCopying>
{
    _Bool _enableRecents;
    _Bool _enableFeedStates;
    _Bool _enableDragToDismiss;
    _Bool _expandedFriendsAndGroupsSections;
    _Bool _useSimplifiedIndexes;
    _Bool _enableProfileTapActions;
    _Bool _enableDescriptiveAddButtons;
    NSString *_customSearchServiceUrl;
}

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(copy, nonatomic) NSString *customSearchServiceUrl; // @synthesize customSearchServiceUrl=_customSearchServiceUrl;
@property(nonatomic) _Bool enableDescriptiveAddButtons; // @synthesize enableDescriptiveAddButtons=_enableDescriptiveAddButtons;
@property(nonatomic) _Bool enableDragToDismiss; // @synthesize enableDragToDismiss=_enableDragToDismiss;
@property(nonatomic) _Bool enableFeedStates; // @synthesize enableFeedStates=_enableFeedStates;
@property(nonatomic) _Bool enableProfileTapActions; // @synthesize enableProfileTapActions=_enableProfileTapActions;
@property(nonatomic) _Bool enableRecents; // @synthesize enableRecents=_enableRecents;
@property(nonatomic) _Bool expandedFriendsAndGroupsSections; // @synthesize expandedFriendsAndGroupsSections=_expandedFriendsAndGroupsSections;
- (id)initWithCustomSearchServiceUrl:(id)arg1 enableRecents:(_Bool)arg2 enableFeedStates:(_Bool)arg3 enableDragToDismiss:(_Bool)arg4 expandedFriendsAndGroupsSections:(_Bool)arg5 useSimplifiedIndexes:(_Bool)arg6 enableProfileTapActions:(_Bool)arg7 enableDescriptiveAddButtons:(_Bool)arg8;
@property(nonatomic) _Bool useSimplifiedIndexes; // @synthesize useSimplifiedIndexes=_useSimplifiedIndexes;
- (id)toJavaScript;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

