//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCPaymentsSettingsTableViewCell.h"

@class UIImageView, UILabel;

@interface SCShippingMethodTableViewCell : SCPaymentsSettingsTableViewCell
{
    UIImageView *_checkmarkImageView;
    UILabel *_shippingMethodLabel;
    UILabel *_priceLabel;
    _Bool _isCellSelected;
}

- (void).cxx_destruct;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (_Bool)isCellSelected;
- (void)layoutSubviews;
- (void)prepareForReuse;
- (void)setCellSelected:(_Bool)arg1;
- (void)setDeselectedLayout;
- (void)setItem:(id)arg1;
- (void)setMode:(unsigned long long)arg1;
- (void)setSelectedLayout;
- (void)setShippingMethod:(id)arg1;

@end

