//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSString;

@interface SCShareFriend : NSObject <NSCoding>
{
    NSString *_name;
    NSString *_display;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *display; // @synthesize display=_display;
- (void)encodeWithCoder:(id)arg1;
- (unsigned long long)hash;
- (id)initWithCoder:(id)arg1;
- (id)initWithName:(id)arg1 display:(id)arg2;
- (_Bool)isEqual:(id)arg1;
- (_Bool)matches:(id)arg1;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;

@end

