//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCLensCameraScreenDataProviderProtocol-Protocol.h"
#import "SCLensDataFetcherListener-Protocol.h"
#import "SCTraceEnabled-Protocol.h"

@class NSString, SCLens, SCLensDataProviderListenerAnnouncer;
@protocol SCLensDataFetcher;

@interface SCSingleLensCameraLensDataProvider : NSObject <SCTraceEnabled, SCLensDataFetcherListener, SCLensCameraScreenDataProviderProtocol>
{
    SCLens *_lens;
    _Bool _fetchingLensContent;
    _Bool _fetchingLensImage;
    NSString *_applicableContext;
    id <SCLensDataFetcher> _lensDataFetcher;
    SCLensDataProviderListenerAnnouncer *_announcer;
    _Bool showBirthdayReplyLens;
}

- (void).cxx_destruct;
- (void)_observeLensFuture:(id)arg1;
- (void)addListener:(id)arg1;
- (id)applicableContext;
- (id)categoryIds;
- (void)fetchLens:(id)arg1;
- (void)fetchLensesIfNeeded;
- (id)firstApplicableLens;
- (id)initWithLens:(id)arg1 dataFetcher:(id)arg2 applicableContext:(id)arg3;
- (id)initWithLensFuture:(id)arg1 placeholderLens:(id)arg2 dataFetcher:(id)arg3 applicableContext:(id)arg4;
- (_Bool)isFetchingLens:(id)arg1;
- (_Bool)isRegressorNeeded;
- (void)lensDataFetcher:(id)arg1 didFinishLoadingContentForAsset:(id)arg2 content:(id)arg3 error:(id)arg4;
- (void)lensDataFetcher:(id)arg1 didFinishLoadingContentForLens:(id)arg2 contentPath:(id)arg3 error:(id)arg4;
- (void)lensDataFetcher:(id)arg1 didFinishLoadingFilterOverlayImageForLens:(id)arg2 imagePath:(id)arg3 error:(id)arg4;
- (void)lensDataFetcher:(id)arg1 didFinishLoadingImageForLens:(id)arg2 image:(id)arg3 error:(id)arg4;
- (void)lensDataFetcher:(id)arg1 willStartLoadingAsset:(id)arg2;
- (void)lensDataFetcher:(id)arg1 willStartLoadingContentForLens:(id)arg2;
- (void)lensDataFetcher:(id)arg1 willStartLoadingFilterOverlayImagePathForLens:(id)arg2;
- (void)lensDataFetcher:(id)arg1 willStartLoadingImageForLens:(id)arg2;
- (id)lensForId:(id)arg1;
- (id)lensToPreselect;
- (id)lenses;
- (id)originalLens;
- (void)removeListener:(id)arg1;
- (id)selectedLens;
- (void)setCategoryIds:(id)arg1 devicePosition:(unsigned long long)arg2;
- (void)setCategoryIds:(id)arg1 devicePosition:(unsigned long long)arg2 applicableContext:(id)arg3;
- (void)setDevicePosition:(unsigned long long)arg1;
- (void)setSelectedLens:(id)arg1;
@property(nonatomic) _Bool showBirthdayReplyLens; // @synthesize showBirthdayReplyLens;
- (id)startUpdatingLensData;
- (void)stopUpdatingLensDataWithToken:(id)arg1;
- (void)updateLens:(id)arg1;
- (void)warmUp;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

