//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSArray, NSDate, NSDictionary, NSString, SCAdResponseAdDataV2, SCSnapAdsIdentifier;

@interface SCSnapAdsAdResponse : NSObject <NSCopying, NSCoding>
{
    _Bool _shouldLoopStoryAd;
    _Bool _isV2Response;
    NSArray *_thirdPartyImpressionTrackURLs;
    NSArray *_thirdPartyImpressionClickURLs;
    SCSnapAdsIdentifier *_identifier;
    NSString *_adKey;
    NSString *_adId;
    NSString *_serveItemId;
    NSString *_adLineItemId;
    NSString *_adServeRequestId;
    long long _adType;
    NSString *_placementId;
    double _timeStampMillis;
    NSArray *_mediaUrls;
    unsigned long long _adProductType;
    NSString *_adSlugOverride;
    NSString *_brandName;
    NSString *_headline;
    NSDictionary *_responseJsonDict;
    NSArray *_adSnapTypes;
    NSArray *_adSnapKeys;
    NSArray *_mediaDurationsMillis;
    NSArray *_bottomSnapMediaDurationsMillis;
    NSString *_tileImageUrl;
    NSString *_tileLogoUrl;
    NSString *_tileHeadline;
    NSDictionary *_adSnapKeyToAdToLensModelMap;
    NSString *_politicalAdPayingAdvertiserName;
    NSDate *_resolvedTimestampInSec;
    NSArray *_renditions;
    SCAdResponseAdDataV2 *_adDataV2;
}

- (void).cxx_destruct;
- (id)_adToLensV1FromV2:(id)arg1;
@property(readonly, nonatomic) SCAdResponseAdDataV2 *adDataV2; // @synthesize adDataV2=_adDataV2;
@property(readonly, copy, nonatomic) NSString *adId; // @synthesize adId=_adId;
@property(readonly, copy, nonatomic) NSString *adKey; // @synthesize adKey=_adKey;
@property(readonly, copy, nonatomic) NSString *adLineItemId; // @synthesize adLineItemId=_adLineItemId;
@property(readonly, nonatomic) unsigned long long adProductType; // @synthesize adProductType=_adProductType;
@property(readonly, copy, nonatomic) NSString *adServeRequestId; // @synthesize adServeRequestId=_adServeRequestId;
@property(readonly, copy, nonatomic) NSString *adSlugOverride; // @synthesize adSlugOverride=_adSlugOverride;
@property(readonly, copy, nonatomic) NSDictionary *adSnapKeyToAdToLensModelMap; // @synthesize adSnapKeyToAdToLensModelMap=_adSnapKeyToAdToLensModelMap;
@property(readonly, copy, nonatomic) NSArray *adSnapKeys; // @synthesize adSnapKeys=_adSnapKeys;
@property(readonly, copy, nonatomic) NSArray *adSnapTypes; // @synthesize adSnapTypes=_adSnapTypes;
@property(readonly, nonatomic) long long adType; // @synthesize adType=_adType;
@property(readonly, copy, nonatomic) NSArray *bottomSnapMediaDurationsMillis; // @synthesize bottomSnapMediaDurationsMillis=_bottomSnapMediaDurationsMillis;
@property(readonly, copy, nonatomic) NSString *brandName; // @synthesize brandName=_brandName;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)endpointAtIndex:(long long)arg1;
- (id)getAdDataV2;
- (id)getAdId;
- (id)getAdKey;
- (id)getAdKeyAtIndex:(long long)arg1;
- (id)getAdKeyFromEndpoint:(id)arg1;
- (id)getAdLineItemId;
- (id)getAdPlacementId;
- (unsigned long long)getAdProductType;
- (id)getAdRequestClientId;
- (id)getAdServeRequestId;
- (id)getAdSlugOverride;
- (id)getAdSnapKeyToAdToLensModelMap;
- (id)getAdSnapKeys;
- (id)getAdSnapTypes;
- (long long)getAdType;
- (long long)getBottomSnapMediaDurationMillis;
- (id)getBottomSnapMediaDurationsMillis;
- (id)getBrandName;
- (id)getDataAtIndex:(long long)arg1;
- (id)getEndpoint;
- (id)getFirstAdSnapKey;
- (id)getHeadline;
- (id)getIdentifier;
- (_Bool)getIsV2Response;
- (long long)getMediaDurationMillis;
- (id)getMediaDurationsMillis;
- (id)getMediaUrls;
- (id)getPoliticalAdPayingAdvertiserName;
- (id)getRenditions;
- (id)getResolvedTimestampInSec;
- (id)getResponseJsonDict;
- (id)getServeItemId;
- (_Bool)getShouldLoopStoryAd;
- (id)getTileHeadline;
- (id)getTileImageUrl;
- (id)getTileLogoUrl;
- (double)getTimeStampMillis;
@property(readonly, copy, nonatomic) NSString *headline; // @synthesize headline=_headline;
@property(readonly, nonatomic) SCSnapAdsIdentifier *identifier; // @synthesize identifier=_identifier;
- (id)initWithAdDataV2:(id)arg1 adIdentifier:(id)arg2 adProductType:(unsigned long long)arg3;
- (id)initWithAdDataV2:(id)arg1 adIdentifier:(id)arg2 adProductType:(unsigned long long)arg3 mediaDurationsMillis:(id)arg4 bottomSnapMediaDurationsMillis:(id)arg5 responseJsonDict:(id)arg6;
- (id)initWithCoder:(id)arg1;
- (id)initWithSnapAdsIdentifier:(id)arg1 adKey:(id)arg2 adId:(id)arg3 serveItemId:(id)arg4 adLineItemId:(id)arg5 adServeRequestId:(id)arg6 mediaUrls:(id)arg7 adType:(long long)arg8 mediaDurationsMillis:(id)arg9 adProductType:(unsigned long long)arg10 adSlugOverride:(id)arg11 brandName:(id)arg12 headline:(id)arg13 responseJsonDict:(id)arg14 adSnapTypes:(id)arg15 adSnapKeys:(id)arg16 tileImageUrl:(id)arg17 tileLogoUrl:(id)arg18 tileHeadline:(id)arg19 shouldLoopStoryAd:(_Bool)arg20 adSnapKeyToAdToLensModelMap:(id)arg21 politicalAdPayingAdvertiserName:(id)arg22 bottomSnapMediaDurationsMillis:(id)arg23 renditions:(id)arg24 thirdPartyImpressionTrackURLs:(id)arg25 thirdPartyImpressionClickURLs:(id)arg26;
- (_Bool)isExpiredWithTTL:(double)arg1 withNow:(double)arg2;
- (_Bool)isNoFill;
- (_Bool)isStoryAd;
- (_Bool)isSuccess;
@property(readonly, nonatomic) _Bool isV2Response; // @synthesize isV2Response=_isV2Response;
- (_Bool)isValid;
@property(readonly, copy, nonatomic) NSArray *mediaDurationsMillis; // @synthesize mediaDurationsMillis=_mediaDurationsMillis;
@property(readonly, copy, nonatomic) NSArray *mediaUrls; // @synthesize mediaUrls=_mediaUrls;
@property(readonly, copy, nonatomic) NSString *placementId; // @synthesize placementId=_placementId;
@property(readonly, copy, nonatomic) NSString *politicalAdPayingAdvertiserName; // @synthesize politicalAdPayingAdvertiserName=_politicalAdPayingAdvertiserName;
@property(readonly, copy, nonatomic) NSArray *renditions; // @synthesize renditions=_renditions;
@property(readonly, nonatomic) NSDate *resolvedTimestampInSec; // @synthesize resolvedTimestampInSec=_resolvedTimestampInSec;
@property(readonly, copy, nonatomic) NSDictionary *responseJsonDict; // @synthesize responseJsonDict=_responseJsonDict;
@property(readonly, copy, nonatomic) NSString *serveItemId; // @synthesize serveItemId=_serveItemId;
@property(readonly, nonatomic) _Bool shouldLoopStoryAd; // @synthesize shouldLoopStoryAd=_shouldLoopStoryAd;
@property(readonly, copy, nonatomic) NSArray *thirdPartyImpressionClickURLs; // @synthesize thirdPartyImpressionClickURLs=_thirdPartyImpressionClickURLs;
@property(readonly, copy, nonatomic) NSArray *thirdPartyImpressionTrackURLs; // @synthesize thirdPartyImpressionTrackURLs=_thirdPartyImpressionTrackURLs;
@property(readonly, copy, nonatomic) NSString *tileHeadline; // @synthesize tileHeadline=_tileHeadline;
@property(readonly, copy, nonatomic) NSString *tileImageUrl; // @synthesize tileImageUrl=_tileImageUrl;
@property(readonly, copy, nonatomic) NSString *tileLogoUrl; // @synthesize tileLogoUrl=_tileLogoUrl;
@property(readonly, nonatomic) double timeStampMillis; // @synthesize timeStampMillis=_timeStampMillis;

@end

