//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCSpectaclesBoomboxMediaCell.h"

#import "SCSpectaclesBoomboxPhotoPlaybackSessionDelegate-Protocol.h"

@class NSString, SCSpectaclesBoomboxPhotoPlaybackSession;

@interface SCSpectaclesBoomboxGLPhotoCell : SCSpectaclesBoomboxMediaCell <SCSpectaclesBoomboxPhotoPlaybackSessionDelegate>
{
    SCSpectaclesBoomboxPhotoPlaybackSession *_playbackSession;
}

- (void).cxx_destruct;
- (void)_loadAsset:(id)arg1;
- (void)_loadPlaybackSessionWithCompletion:(CDUnknownBlockType)arg1;
- (void)cleanup;
- (void)fastReverse;
- (void)photoPlaybackSessionDidLoadFirstFrame:(id)arg1;
- (void)play;
- (void)reset;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

