//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class SCSponsoredSlug, UIImageView, UILabel;

@interface SCSponsoredSlugInteractiveView : UIView
{
    SCSponsoredSlug *_slug;
    double _fadeoutDuration;
    UILabel *_label;
    UIImageView *_icon;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) double fadeoutDuration; // @synthesize fadeoutDuration=_fadeoutDuration;
@property(retain, nonatomic) UIImageView *icon; // @synthesize icon=_icon;
- (id)initWithSlug:(id)arg1 tappablePadding:(struct UIEdgeInsets)arg2;
@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
@property(readonly, nonatomic) SCSponsoredSlug *slug; // @synthesize slug=_slug;

@end

