//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary;

@interface SCSpectaclesMediaListReconciler : NSObject
{
    NSArray *_mediaList;
    NSArray *_contentList;
    NSDictionary *_contentForName;
}

- (void).cxx_destruct;
- (id)_btClassicTaskForContent:(id)arg1 component:(unsigned long long)arg2;
- (_Bool)_containsFileType:(unsigned long long)arg1 contentName:(id)arg2;
- (_Bool)_isContentFullySynced:(id)arg1;
- (void)_updateFilesizeIfNecessaryForFile:(id)arg1 content:(id)arg2;
@property(retain, nonatomic) NSDictionary *contentForName; // @synthesize contentForName=_contentForName;
@property(retain, nonatomic) NSArray *contentList; // @synthesize contentList=_contentList;
- (id)contentToDelete;
- (id)initWithMediaList:(id)arg1 contentList:(id)arg2;
@property(retain, nonatomic) NSArray *mediaList; // @synthesize mediaList=_mediaList;
- (id)necessaryDeletionLogicTasks;
- (id)necessaryMediaTransferTasks;
- (id)necessaryMetadataTasks;
- (void)updateContentWithMediaList;

@end

