//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SCSpectaclesMfiAuthenticator : NSObject
{
    struct EyewearAuthenticator *_authenticator;
}

@property(nonatomic) struct EyewearAuthenticator *authenticator; // @synthesize authenticator=_authenticator;
- (void)dealloc;
- (id)generateMFIChallenge;
- (id)init;
- (_Bool)setMfiCert:(id)arg1;
- (_Bool)verifyMfiResponse:(id)arg1;
- (_Bool)verifyScCert:(id)arg1 publicKey:(id)arg2 magicVersion:(id)arg3;

@end

