//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface SCSpectaclesCache : NSObject
{
    NSString *_userId;
}

+ (id)_directoryForUserId:(id)arg1;
+ (id)cachedUUID;
+ (void)clearCacheExceptUserId:(id)arg1;
+ (id)idleAnalyticsDirectory;
+ (id)logDirectory;
+ (id)spectaclesDirectory;
+ (unsigned long long)totalSizeOfCacheFiles;
- (void).cxx_destruct;
- (id)URLForCacheFileWithSuffix:(id)arg1;
- (void)_createCacheIfNecessary;
- (id)initWithUserId:(id)arg1;
@property(copy, nonatomic) NSString *userId; // @synthesize userId=_userId;
- (id)userDirectory;

@end

