//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class SCLazy, SCStoriesAuthDataProvider;

@interface SCStoriesAuthServices : NSObject
{
    SCStoriesAuthDataProvider *_storiesAuthDataProvider;
    SCLazy *_lazyOurStoriesDescriptionDataCoordinator;
}

- (void).cxx_destruct;
- (id)initWithStoriesAuthDataProvider:(id)arg1 lazyOurStoriesDescriptionDataCoordinator:(id)arg2;
@property(readonly, nonatomic) SCLazy *lazyOurStoriesDescriptionDataCoordinator; // @synthesize lazyOurStoriesDescriptionDataCoordinator=_lazyOurStoriesDescriptionDataCoordinator;
@property(readonly, nonatomic) SCStoriesAuthDataProvider *storiesAuthDataProvider; // @synthesize storiesAuthDataProvider=_storiesAuthDataProvider;

@end

