//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSArray, NSString;

@interface SCStoriesFriendStoriesUpdateRequest : NSObject <NSCopying>
{
    unsigned long long _subtype;
    _Bool _fetchUFSRankedStories_forceNonDelta;
    NSString *_fetchUFSRankedStories_fetchTriggerIdentifier;
    NSString *_deleteFriendStories_username;
    NSString *_deleteCustomStories_publicationId;
    NSString *_deleteGroupChat_groupChatId;
    NSString *_deleteFriendStorySnaps_username;
    NSArray *_deleteFriendStorySnaps_storySnapClientIds;
    NSString *_deleteCustomStorySnaps_publicationId;
    NSArray *_deleteCustomStorySnaps_storySnapClientIds;
    NSString *_deleteStorySnapsWithInvalidMedia_mediaId;
}

+ (id)deleteCustomStoriesWithPublicationId:(id)arg1;
+ (id)deleteCustomStorySnapsWithPublicationId:(id)arg1 storySnapClientIds:(id)arg2;
+ (id)deleteFriendStoriesWithUsername:(id)arg1;
+ (id)deleteFriendStorySnapsWithUsername:(id)arg1 storySnapClientIds:(id)arg2;
+ (id)deleteGroupChatWithGroupChatId:(id)arg1;
+ (id)deleteStorySnapsWithInvalidMediaWithMediaId:(id)arg1;
+ (id)fetchUFSRankedStoriesWithForceNonDelta:(_Bool)arg1 fetchTriggerIdentifier:(id)arg2;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)hash;
- (id)internalInit;
- (_Bool)isEqual:(id)arg1;
- (void)matchFetchUFSRankedStories:(CDUnknownBlockType)arg1 deleteFriendStories:(CDUnknownBlockType)arg2 deleteCustomStories:(CDUnknownBlockType)arg3 deleteGroupChat:(CDUnknownBlockType)arg4 deleteFriendStorySnaps:(CDUnknownBlockType)arg5 deleteCustomStorySnaps:(CDUnknownBlockType)arg6 deleteStorySnapsWithInvalidMedia:(CDUnknownBlockType)arg7;

@end

