//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class SCStoriesNonStreamingContent, SCStoriesStreamingContent;

@interface SCStoriesContent : NSObject
{
    _Bool _retrievalSuccess;
    SCStoriesStreamingContent *_streamingContent;
    SCStoriesNonStreamingContent *_nonStreamingContent;
}

+ (id)storiesContentWithRetrievalFailure;
- (void).cxx_destruct;
- (id)initWithContentResult:(id)arg1 withOverlayData:(id)arg2;
- (id)initWithSnapData:(id)arg1 overlayData:(id)arg2 overlayMetadata:(id)arg3 unarchivingFailed:(_Bool)arg4;
@property(readonly, copy, nonatomic) SCStoriesNonStreamingContent *nonStreamingContent; // @synthesize nonStreamingContent=_nonStreamingContent;
@property(readonly, nonatomic) _Bool retrievalSuccess; // @synthesize retrievalSuccess=_retrievalSuccess;
@property(readonly, copy, nonatomic) SCStoriesStreamingContent *streamingContent; // @synthesize streamingContent=_streamingContent;

@end

