//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SCStoriesViewingUtil : NSObject
{
}

+ (_Bool)allowActionMenuOnStory:(id)arg1 friendStories:(id)arg2 viewLocation:(long long)arg3 experimentManager:(id)arg4 viewContext:(id)arg5;

@end

