//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, SCDocObjectContext, SCQueuePerformer;
@protocol SCDocObjectObservationToken;

@interface SCStoriesSummariesObserver : NSObject
{
    SCQueuePerformer *_performer;
    SCDocObjectContext *_docObjectContext;
    id <SCDocObjectObservationToken> _summaryObservationToken;
    NSDictionary *_summaries;
}

- (void).cxx_destruct;
- (id)_fetchAndObserveForSummaryIds:(id)arg1;
- (void)_updateSummaryFetchedResult:(id)arg1;
- (id)initWithPerformer:(id)arg1 docObjectContext:(id)arg2;
- (void)storiesSummaryFilteredByIds:(id)arg1 completion:(CDUnknownBlockType)arg2;

@end

