//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCTChatMessage-Protocol.h"

@class NSString;
@protocol SOJUConversationMessage;

@interface SCTV3ChatMessage : NSObject <SCTChatMessage>
{
    id <SOJUConversationMessage> _wireMessage;
}

- (void).cxx_destruct;
- (id)conversationId;
@property(readonly, copy) NSString *description;
- (id)extendedPresences;
- (id)initWithSOJUMessage:(id)arg1;
- (id)legacyPresences;
- (id)presencesMetadata;
- (id)receiveTimestamp;
- (id)senderUsername;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

