//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCUnifiedProfileBaseCollectionViewCell.h"

@class CAGradientLayer, SCUnifiedProfileSquadmojiView, UIView;
@protocol SCImageDownloading;

@interface SCUnifiedProfileGroupMembersCollectionViewCell : SCUnifiedProfileBaseCollectionViewCell
{
    UIView *_membersBackgroundView;
    CAGradientLayer *_shadowGradient;
    SCUnifiedProfileSquadmojiView *_foregroundSquadmojiView;
    UIView *_whiteBackgroundView;
    CAGradientLayer *_whiteGradient;
    SCUnifiedProfileSquadmojiView *_backgroundSquadmojiView;
    id _viewModel;
    id <SCImageDownloading> _imageDownloader;
}

+ (unsigned long long)_numBitmojisInForeground:(unsigned long long)arg1;
+ (struct CGSize)sizeWithViewModel:(id)arg1 constrainedToSize:(struct CGSize)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) id <SCImageDownloading> imageDownloader; // @synthesize imageDownloader=_imageDownloader;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)setViewModel:(id)arg1;
- (id)viewModel;

@end

