//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SCActionHandling-Protocol.h"
#import "SCEventAnnouncing-Protocol.h"
#import "SCOperaPresenterDelegate-Protocol.h"
#import "SCUnifiedActionMenuPresenterDelegate-Protocol.h"
#import "SCUnifiedProfileSavedInChatActionMenuActionHandlerDelegate-Protocol.h"
#import "SCUnifiedProfileSavedInChatMediaOperaPresenterDelegate-Protocol.h"

@class NSString, SCEventListenerAnnouncer, SCLazy, SCOperaPlaylistStoriesPlugin, SCOperaPresenter, SCProfileChatMediaDataSource, SCUnifiedActionMenuPresenter, SCUnifiedProfileSavedInChatMediaOperaPresenter, SCUserSession, UIViewController;
@protocol SCProfileChatMediaOperaBaseViewProviding, SCUnifiedProfileSavedInChatFolderPlayerDelegate;

@interface SCUnifiedProfileSavedInChatFolderActionHandler : NSObject <SCUnifiedProfileSavedInChatMediaOperaPresenterDelegate, SCOperaPresenterDelegate, SCActionHandling, SCEventAnnouncing, SCUnifiedActionMenuPresenterDelegate, SCUnifiedProfileSavedInChatActionMenuActionHandlerDelegate>
{
    SCProfileChatMediaDataSource *_profileChatMediaDataSource;
    SCUserSession *_userSession;
    SCEventListenerAnnouncer *_eventAnnouncer;
    NSString *_sessionId;
    unsigned long long _openSource;
    SCLazy *_eraseMessageController;
    SCUnifiedProfileSavedInChatMediaOperaPresenter *_mediaOperaPresenter;
    SCUnifiedActionMenuPresenter *_actionMenuPresenter;
    SCOperaPresenter *_operaPresenter;
    SCOperaPlaylistStoriesPlugin *_storiesPlugin;
    _Bool _chatMediaIsVisible;
    id <SCUnifiedProfileSavedInChatFolderPlayerDelegate> _playerDelegate;
    UIViewController *_presentingViewController;
    id <SCProfileChatMediaOperaBaseViewProviding> _baseViewProvider;
}

+ (id)announcerIdentifier;
- (void).cxx_destruct;
- (void)_deleteMedia:(id)arg1;
- (void)_eraseMessage:(id)arg1;
- (_Bool)_handleActionWithSender:(id)arg1 actionModel:(id)arg2 fromSourceView:(id)arg3;
- (void)_presentChatMediaWithId:(id)arg1 baseView:(id)arg2 operaBaseViewProvider:(id)arg3;
- (void)_presentStory:(id)arg1 baseView:(id)arg2;
- (void)_saveMedia:(id)arg1;
- (void)_saveToCameraRoll:(id)arg1;
- (void)_sendTo:(id)arg1;
- (void)_unsaveMedia:(id)arg1;
- (void)addListener:(id)arg1;
@property(nonatomic) __weak id <SCProfileChatMediaOperaBaseViewProviding> baseViewProvider; // @synthesize baseViewProvider=_baseViewProvider;
- (void)dismissUnifiedProfileSavedInChatActionMenuActionHandler:(id)arg1;
- (void)handleActionFromUnifiedProfileSavedInChatActionMenuActionHandler:(id)arg1 actionModel:(id)arg2;
- (_Bool)handleActionWithSender:(id)arg1 actionModel:(id)arg2 fromSourceView:(id)arg3;
- (id)initWithProfileChatMediaDataSource:(id)arg1 userSession:(id)arg2 sessionId:(id)arg3 openSource:(unsigned long long)arg4;
- (_Bool)isChatMediaCellVisible;
- (_Bool)isPresentingChatMedia;
- (_Bool)isPresentingStory;
- (void)operaPresenter:(id)arg1 didBeginPlayingPlaylistGroupDataModel:(id)arg2;
- (void)operaPresenter:(id)arg1 didFinishViewingPlaylistGroupDataModel:(id)arg2 nextGroupDataModel:(id)arg3;
- (void)operaPresenterDidCancelDismissing:(id)arg1;
- (void)operaPresenterDidFailToPresent:(id)arg1;
- (void)operaPresenterDidFinishDismissing:(id)arg1;
- (void)operaPresenterDidFinishPresenting:(id)arg1 transitionAnimator:(id)arg2;
- (void)operaPresenterDidTearDown:(id)arg1;
- (void)operaPresenterWillBeginAnimatingToDismiss:(id)arg1;
- (void)operaPresenterWillBeginDismissing:(id)arg1 transitionAnimator:(id)arg2;
- (void)operaPresenterWillBeginPresenting:(id)arg1 transitionAnimator:(id)arg2;
@property(nonatomic) __weak id <SCUnifiedProfileSavedInChatFolderPlayerDelegate> playerDelegate; // @synthesize playerDelegate=_playerDelegate;
@property(nonatomic) __weak UIViewController *presentingViewController; // @synthesize presentingViewController=_presentingViewController;
- (void)removeListener:(id)arg1;
- (void)savedInChatMediaOperaPresenter:(id)arg1 didBeginPlayingChatMediaWithId:(id)arg2;
- (void)savedInChatMediaOperaPresenterDidTearDown:(id)arg1;
- (void)unifiedActionMenuPresenterDidDismiss:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

