//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class SCSearchActionButtonViewModel, SCUnifiedActionMenuContextualItemAccessoryImageViewModel;

@interface SCUnifiedActionMenuContextualItemAccessoryViewModel : NSObject <NSCopying>
{
    unsigned long long _subtype;
    SCSearchActionButtonViewModel *_button_buttonAccessoryViewModel;
    SCUnifiedActionMenuContextualItemAccessoryImageViewModel *_image_imageAccessoryViewModel;
}

+ (id)buttonWithButtonAccessoryViewModel:(id)arg1;
+ (id)imageWithImageAccessoryViewModel:(id)arg1;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)hash;
- (id)internalInit;
- (_Bool)isEqual:(id)arg1;
- (void)matchButton:(CDUnknownBlockType)arg1 image:(CDUnknownBlockType)arg2;

@end

