//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCOnboardingTooltipManager.h"

@class SCBarracudaDiscoverFeedOnboardingTooltip, SCFeatureSettingsManager, SCFriendsPageOnboardingView, SCFriendsSwipeTeachingTooltip, SCUserSession, UIView;

@interface SCViewPageOnboardingTooltipManager : SCOnboardingTooltipManager
{
    SCUserSession *_userSession;
    SCFeatureSettingsManager *_featureSettingsManager;
    UIView *_cameraView;
    SCFriendsPageOnboardingView *_friendsPageOnboardingView;
    SCFriendsSwipeTeachingTooltip *_swipeTeachingTooltip;
    SCBarracudaDiscoverFeedOnboardingTooltip *_discoverFeedOnboardingTooltip;
}

- (void).cxx_destruct;
- (_Bool)_friendsPageOnboardingTooltipEnabled;
- (void)_setupFriendsPageOnboardingView;
@property(retain, nonatomic) SCBarracudaDiscoverFeedOnboardingTooltip *discoverFeedOnboardingTooltip; // @synthesize discoverFeedOnboardingTooltip=_discoverFeedOnboardingTooltip;
- (void)hideTooltip;
- (id)initWithUserSession:(id)arg1;
- (void)markTooltipCompleted:(id)arg1;
@property(retain, nonatomic) SCFriendsSwipeTeachingTooltip *swipeTeachingTooltip; // @synthesize swipeTeachingTooltip=_swipeTeachingTooltip;
- (void)setupWithParentView:(id)arg1;
- (_Bool)shouldDisplayTooltip;
- (void)showTooltip;

@end

