//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@interface SCViewControllerLifecycleEvent : NSObject <NSCopying>
{
    unsigned long long _subtype;
    _Bool _viewWillAppear_animated;
    _Bool _viewDidAppear_animated;
    _Bool _viewWillDisappear_animated;
    _Bool _viewDidDisappear_animated;
}

+ (id)viewDidAppearWithAnimated:(_Bool)arg1;
+ (id)viewDidDisappearWithAnimated:(_Bool)arg1;
+ (id)viewDidLoad;
+ (id)viewWillAppearWithAnimated:(_Bool)arg1;
+ (id)viewWillDisappearWithAnimated:(_Bool)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)hash;
- (id)internalInit;
- (_Bool)isEqual:(id)arg1;
- (void)matchViewDidLoad:(CDUnknownBlockType)arg1 viewWillAppear:(CDUnknownBlockType)arg2 viewDidAppear:(CDUnknownBlockType)arg3 viewWillDisappear:(CDUnknownBlockType)arg4 viewDidDisappear:(CDUnknownBlockType)arg5;

@end

