//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSNumber, NSURL, SCWebBrowserConfig;
@protocol SCWebBrowserDelegate;

@protocol SCWebBrowser <NSObject>
+ (_Bool)isPreloadingSupported;
- (id)initWithConfig:(SCWebBrowserConfig *)arg1 delegate:(id <SCWebBrowserDelegate>)arg2;
@property(readonly, nonatomic) NSURL *initialURL;
- (void)loadURL:(NSURL *)arg1;
- (void)reset;
@property(readonly, nonatomic) NSNumber *visibleContentYOffset;
@end

