//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "CAAnimationDelegate-Protocol.h"

@class CAGradientLayer, NSString;

@interface SIGActivityIndicatorView : UIView <CAAnimationDelegate>
{
    CDUnknownBlockType _pendingAnimationCompletionCallback;
    _Bool _stopRequested;
    _Bool _didLayoutSubviews;
    _Bool _waitingToAnimate;
    CAGradientLayer *_gradientLayer;
    CAGradientLayer *_secondGradientLayer;
    CAGradientLayer *_finalGradientLayer;
    _Bool _animating;
    _Bool _hidesWhenStopped;
}

- (void).cxx_destruct;
- (void)_continueAnimating;
- (void)_endingAnimationCompleted;
@property(nonatomic) _Bool hidesWhenStopped; // @synthesize hidesWhenStopped=_hidesWhenStopped;
- (id)initWithFrame:(struct CGRect)arg1;
- (struct CGSize)intrinsicContentSize;
@property(readonly, nonatomic, getter=isAnimating) _Bool animating; // @synthesize animating=_animating;
- (void)layoutSubviews;
- (void)startAnimating;
- (void)stopAnimatingWithCompletion:(CDUnknownBlockType)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

