//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SOJUBroadcastStoriesOrderingOrderingResponse-Protocol.h"

@class NSArray, NSString;

@interface SOJUBroadcastStoriesOrderingOrderingResponse : NSObject <SOJUBroadcastStoriesOrderingOrderingResponse>
{
    NSArray *_recentOrder;
    NSArray *_autoAdvanceOrder;
    NSArray *_qualityProgrammingOrder;
    NSArray *_storyScores;
}

+ (_Bool)canInitFromProto;
+ (unsigned long long *)fasterCodingKeys;
+ (unsigned long long)fasterCodingVersion;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSArray *autoAdvanceOrder; // @synthesize autoAdvanceOrder=_autoAdvanceOrder;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)decodeWithFasterDecoder:(id)arg1;
@property(readonly, copy) NSString *description;
- (void)encodeWithCoder:(id)arg1;
- (void)encodeWithFasterCoder:(id)arg1;
@property(readonly) unsigned long long hash;
- (id)initWithCoder:(id)arg1;
- (id)initWithJSONDictionary:(id)arg1;
- (id)initWithRecentOrder:(id)arg1 autoAdvanceOrder:(id)arg2 qualityProgrammingOrder:(id)arg3 storyScores:(id)arg4;
- (_Bool)isEqual:(id)arg1;
- (_Bool)preferFasterCoding;
@property(readonly, copy, nonatomic) NSArray *qualityProgrammingOrder; // @synthesize qualityProgrammingOrder=_qualityProgrammingOrder;
@property(readonly, copy, nonatomic) NSArray *recentOrder; // @synthesize recentOrder=_recentOrder;
- (void)setObject:(id)arg1 forUInt64Key:(unsigned long long)arg2;
@property(readonly, copy, nonatomic) NSArray *storyScores; // @synthesize storyScores=_storyScores;
- (id)toDictionary;
- (id)toJson;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

