//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "SOJUUnlockablesOndemandAutoApprovalResult-Protocol.h"

@class NSString;

@interface SOJUUnlockablesOndemandAutoApprovalResult : NSObject <SOJUUnlockablesOndemandAutoApprovalResult>
{
    NSString *_status;
    NSString *_rejectionCode;
    NSString *_undecidedCode;
}

+ (_Bool)canInitFromProto;
+ (unsigned long long *)fasterCodingKeys;
+ (unsigned long long)fasterCodingVersion;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)decodeWithFasterDecoder:(id)arg1;
@property(readonly, copy) NSString *description;
- (void)encodeWithCoder:(id)arg1;
- (void)encodeWithFasterCoder:(id)arg1;
@property(readonly) unsigned long long hash;
- (id)initWithCoder:(id)arg1;
- (id)initWithJSONDictionary:(id)arg1;
- (id)initWithStatus:(id)arg1 rejectionCode:(id)arg2 undecidedCode:(id)arg3;
- (_Bool)isEqual:(id)arg1;
- (_Bool)preferFasterCoding;
@property(readonly, copy, nonatomic) NSString *rejectionCode; // @synthesize rejectionCode=_rejectionCode;
- (long long)rejectionCodeEnum;
- (void)setObject:(id)arg1 forUInt64Key:(unsigned long long)arg2;
@property(readonly, copy, nonatomic) NSString *status; // @synthesize status=_status;
- (long long)statusEnum;
- (id)toDictionary;
- (id)toJson;
@property(readonly, copy, nonatomic) NSString *undecidedCode; // @synthesize undecidedCode=_undecidedCode;
- (long long)undecidedCodeEnum;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

