//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"
#import "SCOperaViewersContextTableDataEntry-Protocol.h"

@class NSDate, NSString;

@interface StoryNote : NSObject <NSCoding, SCOperaViewersContextTableDataEntry>
{
    _Bool _screenshotted;
    _Bool _saved;
    NSString *_viewer;
    NSDate *_timestamp;
}

+ (CDUnknownBlockType)sortComparator;
- (void).cxx_destruct;
- (id)avatarViewProperties;
@property(readonly, copy) NSString *description;
- (id)displayName;
- (void)encodeWithCoder:(id)arg1;
- (id)iconKey;
- (id)initWithCoder:(id)arg1;
- (id)initWithSoju:(id)arg1;
@property(nonatomic) _Bool saved; // @synthesize saved=_saved;
@property(nonatomic) _Bool screenshotted; // @synthesize screenshotted=_screenshotted;
@property(retain, nonatomic) NSDate *timestamp; // @synthesize timestamp=_timestamp;
@property(retain, nonatomic) NSString *viewer; // @synthesize viewer=_viewer;
- (id)username;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

