//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSString, NSURL, UIColor;

@protocol SVGContext
- (NSURL *)absoluteURL:(NSString *)arg1;
- (UIColor *)colorForSVGColorString:(NSString *)arg1;
- (UIColor *)currentColor;
- (double)explicitLineScaling;
- (NSString *)isoLanguage;
- (id)objectAtURL:(NSString *)arg1;
- (id)objectNamed:(NSString *)arg1;
- (NSURL *)relativeURL:(NSString *)arg1;
- (void)setCurrentColor:(UIColor *)arg1;
@end

