//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface TCV3CognacSession : NSObject
{
    struct Handle<std::__1::shared_ptr<talkcorev3::CognacSession>, std::__1::shared_ptr<talkcorev3::CognacSession>> _cppRefHandle;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)activate;
- (void)background;
- (void)deactivate;
- (void)dispose;
- (id)getState;
- (id)initWithCpp:(const shared_ptr_913ee57f *)arg1;
- (_Bool)isConnected;
- (void)processTypingActivity:(long long)arg1;
- (void)sendMessage:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setPublishingAudio:(_Bool)arg1;
- (void)updateMuteStatus:(_Bool)arg1;

@end

