//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface UIView (Draggable)
- (void)adjustAnchorPointForGestureRecognizer:(id)arg1;
- (_Bool)cancelsTouchesInView;
- (void)disableDragging;
- (id)dragGestureRecognizer;
- (CDUnknownBlockType)draggingEndedBlock;
- (CDUnknownBlockType)draggingMovedBlock;
- (CDUnknownBlockType)draggingStartedBlock;
- (void)enableDragging;
- (struct CGRect)handle;
- (void)handleDrag:(id)arg1;
- (void)setCancelsTouchesInView:(_Bool)arg1;
- (void)setDragGestureRecognizer:(id)arg1;
- (void)setDraggingEndedBlock:(CDUnknownBlockType)arg1;
- (void)setDraggingMovedBlock:(CDUnknownBlockType)arg1;
- (void)setDraggingStartedBlock:(CDUnknownBlockType)arg1;
- (void)setHandle:(struct CGRect)arg1;
@end

